// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: addressiq/v1/common.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package addressiq.v1;

@kotlin.jvm.JvmName("-initializeappUser")
public inline fun appUser(block: addressiq.v1.AppUserKt.Dsl.() -> kotlin.Unit): addressiq.v1.Common.AppUser =
  addressiq.v1.AppUserKt.Dsl._create(addressiq.v1.Common.AppUser.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `addressiq.v1.AppUser`
 */
public object AppUserKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: addressiq.v1.Common.AppUser.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: addressiq.v1.Common.AppUser.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): addressiq.v1.Common.AppUser = _builder.build()

    /**
     * `string id = 1 [json_name = "id"];`
     */
    public var id: kotlin.String
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * `string id = 1 [json_name = "id"];`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `string organization_id = 2 [json_name = "organizationId"];`
     */
    public var organizationId: kotlin.String
      @JvmName("getOrganizationId")
      get() = _builder.getOrganizationId()
      @JvmName("setOrganizationId")
      set(value) {
        _builder.setOrganizationId(value)
      }
    /**
     * `string organization_id = 2 [json_name = "organizationId"];`
     */
    public fun clearOrganizationId() {
      _builder.clearOrganizationId()
    }

    /**
     * `string app_id = 3 [json_name = "appId"];`
     */
    public var appId: kotlin.String
      @JvmName("getAppId")
      get() = _builder.getAppId()
      @JvmName("setAppId")
      set(value) {
        _builder.setAppId(value)
      }
    /**
     * `string app_id = 3 [json_name = "appId"];`
     */
    public fun clearAppId() {
      _builder.clearAppId()
    }

    /**
     * `string app_user_id = 4 [json_name = "appUserId"];`
     */
    public var appUserId: kotlin.String
      @JvmName("getAppUserId")
      get() = _builder.getAppUserId()
      @JvmName("setAppUserId")
      set(value) {
        _builder.setAppUserId(value)
      }
    /**
     * `string app_user_id = 4 [json_name = "appUserId"];`
     */
    public fun clearAppUserId() {
      _builder.clearAppUserId()
    }

    /**
     * ```
     * PII fields are NOT carried on the wire — only their hashes for
     * matching/dedup. Mobile SDKs encrypt locally before transit.
     * ```
     *
     * `string phone_hash = 5 [json_name = "phoneHash"];`
     */
    public var phoneHash: kotlin.String
      @JvmName("getPhoneHash")
      get() = _builder.getPhoneHash()
      @JvmName("setPhoneHash")
      set(value) {
        _builder.setPhoneHash(value)
      }
    /**
     * ```
     * PII fields are NOT carried on the wire — only their hashes for
     * matching/dedup. Mobile SDKs encrypt locally before transit.
     * ```
     *
     * `string phone_hash = 5 [json_name = "phoneHash"];`
     */
    public fun clearPhoneHash() {
      _builder.clearPhoneHash()
    }

    /**
     * `string email_hash = 6 [json_name = "emailHash"];`
     */
    public var emailHash: kotlin.String
      @JvmName("getEmailHash")
      get() = _builder.getEmailHash()
      @JvmName("setEmailHash")
      set(value) {
        _builder.setEmailHash(value)
      }
    /**
     * `string email_hash = 6 [json_name = "emailHash"];`
     */
    public fun clearEmailHash() {
      _builder.clearEmailHash()
    }

    /**
     * ```
     * APP_USER_ID | PHONE | EMAIL | GENERATED
     * ```
     *
     * `string identity_source = 7 [json_name = "identitySource"];`
     */
    public var identitySource: kotlin.String
      @JvmName("getIdentitySource")
      get() = _builder.getIdentitySource()
      @JvmName("setIdentitySource")
      set(value) {
        _builder.setIdentitySource(value)
      }
    /**
     * ```
     * APP_USER_ID | PHONE | EMAIL | GENERATED
     * ```
     *
     * `string identity_source = 7 [json_name = "identitySource"];`
     */
    public fun clearIdentitySource() {
      _builder.clearIdentitySource()
    }
  }
}
public inline fun addressiq.v1.Common.AppUser.copy(block: `addressiq.v1`.AppUserKt.Dsl.() -> kotlin.Unit): addressiq.v1.Common.AppUser =
  `addressiq.v1`.AppUserKt.Dsl._create(this.toBuilder()).apply { block() }._build()

