// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: addressiq/v1/common.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package addressiq.v1;

@kotlin.jvm.JvmName("-initializegeoPoint")
public inline fun geoPoint(block: addressiq.v1.GeoPointKt.Dsl.() -> kotlin.Unit): addressiq.v1.Common.GeoPoint =
  addressiq.v1.GeoPointKt.Dsl._create(addressiq.v1.Common.GeoPoint.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `addressiq.v1.GeoPoint`
 */
public object GeoPointKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: addressiq.v1.Common.GeoPoint.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: addressiq.v1.Common.GeoPoint.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): addressiq.v1.Common.GeoPoint = _builder.build()

    /**
     * <code>double lat = 1 [json_name = "lat"];</code>
     */
    public var lat: kotlin.Double
      @JvmName("getLat")
      get() = _builder.getLat()
      @JvmName("setLat")
      set(value) {
        _builder.setLat(value)
      }
    /**
     * `double lat = 1 [json_name = "lat"];`
     */
    public fun clearLat() {
      _builder.clearLat()
    }

    /**
     * <code>double lon = 2 [json_name = "lon"];</code>
     */
    public var lon: kotlin.Double
      @JvmName("getLon")
      get() = _builder.getLon()
      @JvmName("setLon")
      set(value) {
        _builder.setLon(value)
      }
    /**
     * `double lon = 2 [json_name = "lon"];`
     */
    public fun clearLon() {
      _builder.clearLon()
    }
  }
}
public inline fun addressiq.v1.Common.GeoPoint.copy(block: `addressiq.v1`.GeoPointKt.Dsl.() -> kotlin.Unit): addressiq.v1.Common.GeoPoint =
  `addressiq.v1`.GeoPointKt.Dsl._create(this.toBuilder()).apply { block() }._build()

