// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: addressiq/v1/sdk.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package addressiq.v1;

@kotlin.jvm.JvmName("-initializeinvalidateSessionResponse")
public inline fun invalidateSessionResponse(block: addressiq.v1.InvalidateSessionResponseKt.Dsl.() -> kotlin.Unit): addressiq.v1.Sdk.InvalidateSessionResponse =
  addressiq.v1.InvalidateSessionResponseKt.Dsl._create(addressiq.v1.Sdk.InvalidateSessionResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `addressiq.v1.InvalidateSessionResponse`
 */
public object InvalidateSessionResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: addressiq.v1.Sdk.InvalidateSessionResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: addressiq.v1.Sdk.InvalidateSessionResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): addressiq.v1.Sdk.InvalidateSessionResponse = _builder.build()

    /**
     * <code>bool revoked = 1 [json_name = "revoked"];</code>
     */
    public var revoked: kotlin.Boolean
      @JvmName("getRevoked")
      get() = _builder.getRevoked()
      @JvmName("setRevoked")
      set(value) {
        _builder.setRevoked(value)
      }
    /**
     * `bool revoked = 1 [json_name = "revoked"];`
     */
    public fun clearRevoked() {
      _builder.clearRevoked()
    }
  }
}
public inline fun addressiq.v1.Sdk.InvalidateSessionResponse.copy(block: `addressiq.v1`.InvalidateSessionResponseKt.Dsl.() -> kotlin.Unit): addressiq.v1.Sdk.InvalidateSessionResponse =
  `addressiq.v1`.InvalidateSessionResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

