// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: addressiq/v1/sdk.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package addressiq.v1;

@kotlin.jvm.JvmName("-initializeinvalidateSessionRequest")
public inline fun invalidateSessionRequest(block: addressiq.v1.InvalidateSessionRequestKt.Dsl.() -> kotlin.Unit): addressiq.v1.Sdk.InvalidateSessionRequest =
  addressiq.v1.InvalidateSessionRequestKt.Dsl._create(addressiq.v1.Sdk.InvalidateSessionRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `addressiq.v1.InvalidateSessionRequest`
 */
public object InvalidateSessionRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: addressiq.v1.Sdk.InvalidateSessionRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: addressiq.v1.Sdk.InvalidateSessionRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): addressiq.v1.Sdk.InvalidateSessionRequest = _builder.build()

    /**
     * `string app_user_id = 1 [json_name = "appUserId"];`
     */
    public var appUserId: kotlin.String
      @JvmName("getAppUserId")
      get() = _builder.getAppUserId()
      @JvmName("setAppUserId")
      set(value) {
        _builder.setAppUserId(value)
      }
    /**
     * `string app_user_id = 1 [json_name = "appUserId"];`
     */
    public fun clearAppUserId() {
      _builder.clearAppUserId()
    }

    /**
     * `string verification_code = 2 [json_name = "verificationCode"];`
     */
    public var verificationCode: kotlin.String
      @JvmName("getVerificationCode")
      get() = _builder.getVerificationCode()
      @JvmName("setVerificationCode")
      set(value) {
        _builder.setVerificationCode(value)
      }
    /**
     * `string verification_code = 2 [json_name = "verificationCode"];`
     */
    public fun clearVerificationCode() {
      _builder.clearVerificationCode()
    }
  }
}
public inline fun addressiq.v1.Sdk.InvalidateSessionRequest.copy(block: `addressiq.v1`.InvalidateSessionRequestKt.Dsl.() -> kotlin.Unit): addressiq.v1.Sdk.InvalidateSessionRequest =
  `addressiq.v1`.InvalidateSessionRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

