// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: addressiq/v1/verification.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package addressiq.v1;

@kotlin.jvm.JvmName("-initializelocation")
public inline fun location(block: addressiq.v1.LocationKt.Dsl.() -> kotlin.Unit): addressiq.v1.VerificationOuterClass.Location =
  addressiq.v1.LocationKt.Dsl._create(addressiq.v1.VerificationOuterClass.Location.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `addressiq.v1.Location`
 */
public object LocationKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: addressiq.v1.VerificationOuterClass.Location.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: addressiq.v1.VerificationOuterClass.Location.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): addressiq.v1.VerificationOuterClass.Location = _builder.build()

    /**
     * `string id = 1 [json_name = "id"];`
     */
    public var id: kotlin.String
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * `string id = 1 [json_name = "id"];`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `string location_code = 2 [json_name = "locationCode"];`
     */
    public var locationCode: kotlin.String
      @JvmName("getLocationCode")
      get() = _builder.getLocationCode()
      @JvmName("setLocationCode")
      set(value) {
        _builder.setLocationCode(value)
      }
    /**
     * `string location_code = 2 [json_name = "locationCode"];`
     */
    public fun clearLocationCode() {
      _builder.clearLocationCode()
    }

    /**
     * `.addressiq.v1.GeoPoint position = 3 [json_name = "position"];`
     */
    public var position: addressiq.v1.Common.GeoPoint
      @JvmName("getPosition")
      get() = _builder.getPosition()
      @JvmName("setPosition")
      set(value) {
        _builder.setPosition(value)
      }
    /**
     * `.addressiq.v1.GeoPoint position = 3 [json_name = "position"];`
     */
    public fun clearPosition() {
      _builder.clearPosition()
    }
    /**
     * `.addressiq.v1.GeoPoint position = 3 [json_name = "position"];`
     * @return Whether the position field is set.
     */
    public fun hasPosition(): kotlin.Boolean {
      return _builder.hasPosition()
    }

    /**
     * <code>int32 geofence_radius_m = 4 [json_name = "geofenceRadiusM"];</code>
     */
    public var geofenceRadiusM: kotlin.Int
      @JvmName("getGeofenceRadiusM")
      get() = _builder.getGeofenceRadiusM()
      @JvmName("setGeofenceRadiusM")
      set(value) {
        _builder.setGeofenceRadiusM(value)
      }
    /**
     * `int32 geofence_radius_m = 4 [json_name = "geofenceRadiusM"];`
     */
    public fun clearGeofenceRadiusM() {
      _builder.clearGeofenceRadiusM()
    }

    /**
     * <pre>
     * Phase 3 — adaptive radius the SDK MUST honor when registering OS geofences.
     * </pre>
     *
     * <code>int32 adaptive_geofence_radius_meters = 5 [json_name = "adaptiveGeofenceRadiusMeters"];</code>
     */
    public var adaptiveGeofenceRadiusMeters: kotlin.Int
      @JvmName("getAdaptiveGeofenceRadiusMeters")
      get() = _builder.getAdaptiveGeofenceRadiusMeters()
      @JvmName("setAdaptiveGeofenceRadiusMeters")
      set(value) {
        _builder.setAdaptiveGeofenceRadiusMeters(value)
      }
    /**
     * ```
     * Phase 3 — adaptive radius the SDK MUST honor when registering OS geofences.
     * ```
     *
     * `int32 adaptive_geofence_radius_meters = 5 [json_name = "adaptiveGeofenceRadiusMeters"];`
     */
    public fun clearAdaptiveGeofenceRadiusMeters() {
      _builder.clearAdaptiveGeofenceRadiusMeters()
    }

    /**
     * `.addressiq.v1.EnvironmentBucket environment = 6 [json_name = "environment"];`
     */
    public var environment: addressiq.v1.Common.EnvironmentBucket
      @JvmName("getEnvironment")
      get() = _builder.getEnvironment()
      @JvmName("setEnvironment")
      set(value) {
        _builder.setEnvironment(value)
      }
    public var environmentValue: kotlin.Int
      @JvmName("getEnvironmentValue")
      get() = _builder.getEnvironmentValue()
      @JvmName("setEnvironmentValue")
      set(value) {
        _builder.setEnvironmentValue(value)
      }
    /**
     * `.addressiq.v1.EnvironmentBucket environment = 6 [json_name = "environment"];`
     */
    public fun clearEnvironment() {
      _builder.clearEnvironment()
    }
  }
}
public inline fun addressiq.v1.VerificationOuterClass.Location.copy(block: `addressiq.v1`.LocationKt.Dsl.() -> kotlin.Unit): addressiq.v1.VerificationOuterClass.Location =
  `addressiq.v1`.LocationKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val addressiq.v1.VerificationOuterClass.LocationOrBuilder.positionOrNull: addressiq.v1.Common.GeoPoint?
  get() = if (hasPosition()) getPosition() else null

