// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: addressiq/v1/common.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package addressiq.v1;

@kotlin.jvm.JvmName("-initializeorganization")
public inline fun organization(block: addressiq.v1.OrganizationKt.Dsl.() -> kotlin.Unit): addressiq.v1.Common.Organization =
  addressiq.v1.OrganizationKt.Dsl._create(addressiq.v1.Common.Organization.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `addressiq.v1.Organization`
 */
public object OrganizationKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: addressiq.v1.Common.Organization.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: addressiq.v1.Common.Organization.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): addressiq.v1.Common.Organization = _builder.build()

    /**
     * `string id = 1 [json_name = "id"];`
     */
    public var id: kotlin.String
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * `string id = 1 [json_name = "id"];`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `string name = 2 [json_name = "name"];`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * `string name = 2 [json_name = "name"];`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `string slug = 3 [json_name = "slug"];`
     */
    public var slug: kotlin.String
      @JvmName("getSlug")
      get() = _builder.getSlug()
      @JvmName("setSlug")
      set(value) {
        _builder.setSlug(value)
      }
    /**
     * `string slug = 3 [json_name = "slug"];`
     */
    public fun clearSlug() {
      _builder.clearSlug()
    }

    /**
     * `string country = 4 [json_name = "country"];`
     */
    public var country: kotlin.String
      @JvmName("getCountry")
      get() = _builder.getCountry()
      @JvmName("setCountry")
      set(value) {
        _builder.setCountry(value)
      }
    /**
     * `string country = 4 [json_name = "country"];`
     */
    public fun clearCountry() {
      _builder.clearCountry()
    }

    /**
     * `string status = 5 [json_name = "status"];`
     */
    public var status: kotlin.String
      @JvmName("getStatus")
      get() = _builder.getStatus()
      @JvmName("setStatus")
      set(value) {
        _builder.setStatus(value)
      }
    /**
     * `string status = 5 [json_name = "status"];`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }
  }
}
public inline fun addressiq.v1.Common.Organization.copy(block: `addressiq.v1`.OrganizationKt.Dsl.() -> kotlin.Unit): addressiq.v1.Common.Organization =
  `addressiq.v1`.OrganizationKt.Dsl._create(this.toBuilder()).apply { block() }._build()

