// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: addressiq/v1/sdk.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package addressiq.v1;

@kotlin.jvm.JvmName("-initializepermissionState")
public inline fun permissionState(block: addressiq.v1.PermissionStateKt.Dsl.() -> kotlin.Unit): addressiq.v1.Sdk.PermissionState =
  addressiq.v1.PermissionStateKt.Dsl._create(addressiq.v1.Sdk.PermissionState.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `addressiq.v1.PermissionState`
 */
public object PermissionStateKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: addressiq.v1.Sdk.PermissionState.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: addressiq.v1.Sdk.PermissionState.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): addressiq.v1.Sdk.PermissionState = _builder.build()

    /**
     * `.addressiq.v1.PermissionStatus foreground_location = 1 [json_name = "foregroundLocation"];`
     */
    public var foregroundLocation: addressiq.v1.Sdk.PermissionStatus
      @JvmName("getForegroundLocation")
      get() = _builder.getForegroundLocation()
      @JvmName("setForegroundLocation")
      set(value) {
        _builder.setForegroundLocation(value)
      }
    public var foregroundLocationValue: kotlin.Int
      @JvmName("getForegroundLocationValue")
      get() = _builder.getForegroundLocationValue()
      @JvmName("setForegroundLocationValue")
      set(value) {
        _builder.setForegroundLocationValue(value)
      }
    /**
     * `.addressiq.v1.PermissionStatus foreground_location = 1 [json_name = "foregroundLocation"];`
     */
    public fun clearForegroundLocation() {
      _builder.clearForegroundLocation()
    }

    /**
     * `.addressiq.v1.PermissionStatus background_location = 2 [json_name = "backgroundLocation"];`
     */
    public var backgroundLocation: addressiq.v1.Sdk.PermissionStatus
      @JvmName("getBackgroundLocation")
      get() = _builder.getBackgroundLocation()
      @JvmName("setBackgroundLocation")
      set(value) {
        _builder.setBackgroundLocation(value)
      }
    public var backgroundLocationValue: kotlin.Int
      @JvmName("getBackgroundLocationValue")
      get() = _builder.getBackgroundLocationValue()
      @JvmName("setBackgroundLocationValue")
      set(value) {
        _builder.setBackgroundLocationValue(value)
      }
    /**
     * `.addressiq.v1.PermissionStatus background_location = 2 [json_name = "backgroundLocation"];`
     */
    public fun clearBackgroundLocation() {
      _builder.clearBackgroundLocation()
    }

    /**
     * `.addressiq.v1.PermissionStatus notifications = 3 [json_name = "notifications"];`
     */
    public var notifications: addressiq.v1.Sdk.PermissionStatus
      @JvmName("getNotifications")
      get() = _builder.getNotifications()
      @JvmName("setNotifications")
      set(value) {
        _builder.setNotifications(value)
      }
    public var notificationsValue: kotlin.Int
      @JvmName("getNotificationsValue")
      get() = _builder.getNotificationsValue()
      @JvmName("setNotificationsValue")
      set(value) {
        _builder.setNotificationsValue(value)
      }
    /**
     * `.addressiq.v1.PermissionStatus notifications = 3 [json_name = "notifications"];`
     */
    public fun clearNotifications() {
      _builder.clearNotifications()
    }
  }
}
public inline fun addressiq.v1.Sdk.PermissionState.copy(block: `addressiq.v1`.PermissionStateKt.Dsl.() -> kotlin.Unit): addressiq.v1.Sdk.PermissionState =
  `addressiq.v1`.PermissionStateKt.Dsl._create(this.toBuilder()).apply { block() }._build()

