// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: addressiq/v1/common.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package addressiq.v1;

@kotlin.jvm.JvmName("-initializesdkError")
public inline fun sdkError(block: addressiq.v1.SdkErrorKt.Dsl.() -> kotlin.Unit): addressiq.v1.Common.SdkError =
  addressiq.v1.SdkErrorKt.Dsl._create(addressiq.v1.Common.SdkError.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `addressiq.v1.SdkError`
 */
public object SdkErrorKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: addressiq.v1.Common.SdkError.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: addressiq.v1.Common.SdkError.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): addressiq.v1.Common.SdkError = _builder.build()

    /**
     * `.addressiq.v1.ErrorCode code = 1 [json_name = "code"];`
     */
    public var code: addressiq.v1.Common.ErrorCode
      @JvmName("getCode")
      get() = _builder.getCode()
      @JvmName("setCode")
      set(value) {
        _builder.setCode(value)
      }
    public var codeValue: kotlin.Int
      @JvmName("getCodeValue")
      get() = _builder.getCodeValue()
      @JvmName("setCodeValue")
      set(value) {
        _builder.setCodeValue(value)
      }
    /**
     * `.addressiq.v1.ErrorCode code = 1 [json_name = "code"];`
     */
    public fun clearCode() {
      _builder.clearCode()
    }

    /**
     * `string message = 2 [json_name = "message"];`
     */
    public var message: kotlin.String
      @JvmName("getMessage")
      get() = _builder.getMessage()
      @JvmName("setMessage")
      set(value) {
        _builder.setMessage(value)
      }
    /**
     * `string message = 2 [json_name = "message"];`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }

    /**
     * `string docs_url = 3 [json_name = "docsUrl"];`
     */
    public var docsUrl: kotlin.String
      @JvmName("getDocsUrl")
      get() = _builder.getDocsUrl()
      @JvmName("setDocsUrl")
      set(value) {
        _builder.setDocsUrl(value)
      }
    /**
     * `string docs_url = 3 [json_name = "docsUrl"];`
     */
    public fun clearDocsUrl() {
      _builder.clearDocsUrl()
    }
  }
}
public inline fun addressiq.v1.Common.SdkError.copy(block: `addressiq.v1`.SdkErrorKt.Dsl.() -> kotlin.Unit): addressiq.v1.Common.SdkError =
  `addressiq.v1`.SdkErrorKt.Dsl._create(this.toBuilder()).apply { block() }._build()

