// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: addressiq/v1/sdk.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package addressiq.v1;

@kotlin.jvm.JvmName("-initializesdkUser")
public inline fun sdkUser(block: addressiq.v1.SdkUserKt.Dsl.() -> kotlin.Unit): addressiq.v1.Sdk.SdkUser =
  addressiq.v1.SdkUserKt.Dsl._create(addressiq.v1.Sdk.SdkUser.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `addressiq.v1.SdkUser`
 */
public object SdkUserKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: addressiq.v1.Sdk.SdkUser.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: addressiq.v1.Sdk.SdkUser.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): addressiq.v1.Sdk.SdkUser = _builder.build()

    /**
     * `string app_user_id = 1 [json_name = "appUserId"];`
     */
    public var appUserId: kotlin.String
      @JvmName("getAppUserId")
      get() = _builder.getAppUserId()
      @JvmName("setAppUserId")
      set(value) {
        _builder.setAppUserId(value)
      }
    /**
     * `string app_user_id = 1 [json_name = "appUserId"];`
     */
    public fun clearAppUserId() {
      _builder.clearAppUserId()
    }

    /**
     * ```
     * encrypted at rest on device — wire = plaintext under HTTPS
     * ```
     *
     * `string phone = 2 [json_name = "phone"];`
     */
    public var phone: kotlin.String
      @JvmName("getPhone")
      get() = _builder.getPhone()
      @JvmName("setPhone")
      set(value) {
        _builder.setPhone(value)
      }
    /**
     * ```
     * encrypted at rest on device — wire = plaintext under HTTPS
     * ```
     *
     * `string phone = 2 [json_name = "phone"];`
     */
    public fun clearPhone() {
      _builder.clearPhone()
    }

    /**
     * `string email = 3 [json_name = "email"];`
     */
    public var email: kotlin.String
      @JvmName("getEmail")
      get() = _builder.getEmail()
      @JvmName("setEmail")
      set(value) {
        _builder.setEmail(value)
      }
    /**
     * `string email = 3 [json_name = "email"];`
     */
    public fun clearEmail() {
      _builder.clearEmail()
    }

    /**
     * `string first_name = 4 [json_name = "firstName"];`
     */
    public var firstName: kotlin.String
      @JvmName("getFirstName")
      get() = _builder.getFirstName()
      @JvmName("setFirstName")
      set(value) {
        _builder.setFirstName(value)
      }
    /**
     * `string first_name = 4 [json_name = "firstName"];`
     */
    public fun clearFirstName() {
      _builder.clearFirstName()
    }

    /**
     * `string last_name = 5 [json_name = "lastName"];`
     */
    public var lastName: kotlin.String
      @JvmName("getLastName")
      get() = _builder.getLastName()
      @JvmName("setLastName")
      set(value) {
        _builder.setLastName(value)
      }
    /**
     * `string last_name = 5 [json_name = "lastName"];`
     */
    public fun clearLastName() {
      _builder.clearLastName()
    }
  }
}
public inline fun addressiq.v1.Sdk.SdkUser.copy(block: `addressiq.v1`.SdkUserKt.Dsl.() -> kotlin.Unit): addressiq.v1.Sdk.SdkUser =
  `addressiq.v1`.SdkUserKt.Dsl._create(this.toBuilder()).apply { block() }._build()

