// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: addressiq/v1/telemetry.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package addressiq.v1;

@kotlin.jvm.JvmName("-initializesecurityEnvelope")
public inline fun securityEnvelope(block: addressiq.v1.SecurityEnvelopeKt.Dsl.() -> kotlin.Unit): addressiq.v1.Telemetry.SecurityEnvelope =
  addressiq.v1.SecurityEnvelopeKt.Dsl._create(addressiq.v1.Telemetry.SecurityEnvelope.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `addressiq.v1.SecurityEnvelope`
 */
public object SecurityEnvelopeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: addressiq.v1.Telemetry.SecurityEnvelope.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: addressiq.v1.Telemetry.SecurityEnvelope.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): addressiq.v1.Telemetry.SecurityEnvelope = _builder.build()

    /**
     * `string device_fingerprint_hash = 1 [json_name = "deviceFingerprintHash"];`
     */
    public var deviceFingerprintHash: kotlin.String
      @JvmName("getDeviceFingerprintHash")
      get() = _builder.getDeviceFingerprintHash()
      @JvmName("setDeviceFingerprintHash")
      set(value) {
        _builder.setDeviceFingerprintHash(value)
      }
    /**
     * `string device_fingerprint_hash = 1 [json_name = "deviceFingerprintHash"];`
     */
    public fun clearDeviceFingerprintHash() {
      _builder.clearDeviceFingerprintHash()
    }

    /**
     * `string attestation_token = 2 [json_name = "attestationToken"];`
     */
    public var attestationToken: kotlin.String
      @JvmName("getAttestationToken")
      get() = _builder.getAttestationToken()
      @JvmName("setAttestationToken")
      set(value) {
        _builder.setAttestationToken(value)
      }
    /**
     * `string attestation_token = 2 [json_name = "attestationToken"];`
     */
    public fun clearAttestationToken() {
      _builder.clearAttestationToken()
    }

    /**
     * `.addressiq.v1.IntegrityVerdict integrity_verdict = 3 [json_name = "integrityVerdict"];`
     */
    public var integrityVerdict: addressiq.v1.Telemetry.IntegrityVerdict
      @JvmName("getIntegrityVerdict")
      get() = _builder.getIntegrityVerdict()
      @JvmName("setIntegrityVerdict")
      set(value) {
        _builder.setIntegrityVerdict(value)
      }
    public var integrityVerdictValue: kotlin.Int
      @JvmName("getIntegrityVerdictValue")
      get() = _builder.getIntegrityVerdictValue()
      @JvmName("setIntegrityVerdictValue")
      set(value) {
        _builder.setIntegrityVerdictValue(value)
      }
    /**
     * `.addressiq.v1.IntegrityVerdict integrity_verdict = 3 [json_name = "integrityVerdict"];`
     */
    public fun clearIntegrityVerdict() {
      _builder.clearIntegrityVerdict()
    }
  }
}
public inline fun addressiq.v1.Telemetry.SecurityEnvelope.copy(block: `addressiq.v1`.SecurityEnvelopeKt.Dsl.() -> kotlin.Unit): addressiq.v1.Telemetry.SecurityEnvelope =
  `addressiq.v1`.SecurityEnvelopeKt.Dsl._create(this.toBuilder()).apply { block() }._build()

