// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: addressiq/v1/telemetry.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package addressiq.v1;

@kotlin.jvm.JvmName("-initializetransitEventBatch")
public inline fun transitEventBatch(block: addressiq.v1.TransitEventBatchKt.Dsl.() -> kotlin.Unit): addressiq.v1.Telemetry.TransitEventBatch =
  addressiq.v1.TransitEventBatchKt.Dsl._create(addressiq.v1.Telemetry.TransitEventBatch.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `addressiq.v1.TransitEventBatch`
 */
public object TransitEventBatchKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: addressiq.v1.Telemetry.TransitEventBatch.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: addressiq.v1.Telemetry.TransitEventBatch.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): addressiq.v1.Telemetry.TransitEventBatch = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class EventsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .addressiq.v1.TransitEvent events = 1 [json_name = "events"];`
     */
     public val events: com.google.protobuf.kotlin.DslList<addressiq.v1.Telemetry.TransitEvent, EventsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getEventsList()
      )
    /**
     * `repeated .addressiq.v1.TransitEvent events = 1 [json_name = "events"];`
     * @param value The events to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addEvents")
    public fun com.google.protobuf.kotlin.DslList<addressiq.v1.Telemetry.TransitEvent, EventsProxy>.add(value: addressiq.v1.Telemetry.TransitEvent) {
      _builder.addEvents(value)
    }
    /**
     * `repeated .addressiq.v1.TransitEvent events = 1 [json_name = "events"];`
     * @param value The events to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignEvents")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<addressiq.v1.Telemetry.TransitEvent, EventsProxy>.plusAssign(value: addressiq.v1.Telemetry.TransitEvent) {
      add(value)
    }
    /**
     * `repeated .addressiq.v1.TransitEvent events = 1 [json_name = "events"];`
     * @param values The events to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllEvents")
    public fun com.google.protobuf.kotlin.DslList<addressiq.v1.Telemetry.TransitEvent, EventsProxy>.addAll(values: kotlin.collections.Iterable<addressiq.v1.Telemetry.TransitEvent>) {
      _builder.addAllEvents(values)
    }
    /**
     * `repeated .addressiq.v1.TransitEvent events = 1 [json_name = "events"];`
     * @param values The events to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllEvents")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<addressiq.v1.Telemetry.TransitEvent, EventsProxy>.plusAssign(values: kotlin.collections.Iterable<addressiq.v1.Telemetry.TransitEvent>) {
      addAll(values)
    }
    /**
     * `repeated .addressiq.v1.TransitEvent events = 1 [json_name = "events"];`
     * @param index The index to set the value at.
     * @param value The events to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setEvents")
    public operator fun com.google.protobuf.kotlin.DslList<addressiq.v1.Telemetry.TransitEvent, EventsProxy>.set(index: kotlin.Int, value: addressiq.v1.Telemetry.TransitEvent) {
      _builder.setEvents(index, value)
    }
    /**
     * `repeated .addressiq.v1.TransitEvent events = 1 [json_name = "events"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearEvents")
    public fun com.google.protobuf.kotlin.DslList<addressiq.v1.Telemetry.TransitEvent, EventsProxy>.clear() {
      _builder.clearEvents()
    }
  }
}
public inline fun addressiq.v1.Telemetry.TransitEventBatch.copy(block: `addressiq.v1`.TransitEventBatchKt.Dsl.() -> kotlin.Unit): addressiq.v1.Telemetry.TransitEventBatch =
  `addressiq.v1`.TransitEventBatchKt.Dsl._create(this.toBuilder()).apply { block() }._build()

