// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: addressiq/v1/telemetry.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package addressiq.v1;

@kotlin.jvm.JvmName("-initializetransitEventBatchAck")
public inline fun transitEventBatchAck(block: addressiq.v1.TransitEventBatchAckKt.Dsl.() -> kotlin.Unit): addressiq.v1.Telemetry.TransitEventBatchAck =
  addressiq.v1.TransitEventBatchAckKt.Dsl._create(addressiq.v1.Telemetry.TransitEventBatchAck.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `addressiq.v1.TransitEventBatchAck`
 */
public object TransitEventBatchAckKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: addressiq.v1.Telemetry.TransitEventBatchAck.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: addressiq.v1.Telemetry.TransitEventBatchAck.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): addressiq.v1.Telemetry.TransitEventBatchAck = _builder.build()

    /**
     * <code>int32 accepted = 1 [json_name = "accepted"];</code>
     */
    public var accepted: kotlin.Int
      @JvmName("getAccepted")
      get() = _builder.getAccepted()
      @JvmName("setAccepted")
      set(value) {
        _builder.setAccepted(value)
      }
    /**
     * `int32 accepted = 1 [json_name = "accepted"];`
     */
    public fun clearAccepted() {
      _builder.clearAccepted()
    }

    /**
     * <code>int32 deduplicated = 2 [json_name = "deduplicated"];</code>
     */
    public var deduplicated: kotlin.Int
      @JvmName("getDeduplicated")
      get() = _builder.getDeduplicated()
      @JvmName("setDeduplicated")
      set(value) {
        _builder.setDeduplicated(value)
      }
    /**
     * `int32 deduplicated = 2 [json_name = "deduplicated"];`
     */
    public fun clearDeduplicated() {
      _builder.clearDeduplicated()
    }
  }
}
public inline fun addressiq.v1.Telemetry.TransitEventBatchAck.copy(block: `addressiq.v1`.TransitEventBatchAckKt.Dsl.() -> kotlin.Unit): addressiq.v1.Telemetry.TransitEventBatchAck =
  `addressiq.v1`.TransitEventBatchAckKt.Dsl._create(this.toBuilder()).apply { block() }._build()

