// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: addressiq/v1/telemetry.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package addressiq.v1;

@kotlin.jvm.JvmName("-initializetransitEvent")
public inline fun transitEvent(block: addressiq.v1.TransitEventKt.Dsl.() -> kotlin.Unit): addressiq.v1.Telemetry.TransitEvent =
  addressiq.v1.TransitEventKt.Dsl._create(addressiq.v1.Telemetry.TransitEvent.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `addressiq.v1.TransitEvent`
 */
public object TransitEventKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: addressiq.v1.Telemetry.TransitEvent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: addressiq.v1.Telemetry.TransitEvent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): addressiq.v1.Telemetry.TransitEvent = _builder.build()

    /**
     * ```
     * UUID v4 generated client-side. Server dedups via 24h Redis SETNX.
     * ```
     *
     * `string event_id = 1 [json_name = "eventId"];`
     */
    public var eventId: kotlin.String
      @JvmName("getEventId")
      get() = _builder.getEventId()
      @JvmName("setEventId")
      set(value) {
        _builder.setEventId(value)
      }
    /**
     * ```
     * UUID v4 generated client-side. Server dedups via 24h Redis SETNX.
     * ```
     *
     * `string event_id = 1 [json_name = "eventId"];`
     */
    public fun clearEventId() {
      _builder.clearEventId()
    }

    /**
     * `string location_id = 2 [json_name = "locationId"];`
     */
    public var locationId: kotlin.String
      @JvmName("getLocationId")
      get() = _builder.getLocationId()
      @JvmName("setLocationId")
      set(value) {
        _builder.setLocationId(value)
      }
    /**
     * `string location_id = 2 [json_name = "locationId"];`
     */
    public fun clearLocationId() {
      _builder.clearLocationId()
    }

    /**
     * `.addressiq.v1.TransitEventType event_type = 3 [json_name = "eventType"];`
     */
    public var eventType: addressiq.v1.Telemetry.TransitEventType
      @JvmName("getEventType")
      get() = _builder.getEventType()
      @JvmName("setEventType")
      set(value) {
        _builder.setEventType(value)
      }
    public var eventTypeValue: kotlin.Int
      @JvmName("getEventTypeValue")
      get() = _builder.getEventTypeValue()
      @JvmName("setEventTypeValue")
      set(value) {
        _builder.setEventTypeValue(value)
      }
    /**
     * `.addressiq.v1.TransitEventType event_type = 3 [json_name = "eventType"];`
     */
    public fun clearEventType() {
      _builder.clearEventType()
    }

    /**
     * ```
     * optional (events without GPS are valid)
     * ```
     *
     * `.addressiq.v1.GeoPoint position = 4 [json_name = "position"];`
     */
    public var position: addressiq.v1.Common.GeoPoint
      @JvmName("getPosition")
      get() = _builder.getPosition()
      @JvmName("setPosition")
      set(value) {
        _builder.setPosition(value)
      }
    /**
     * ```
     * optional (events without GPS are valid)
     * ```
     *
     * `.addressiq.v1.GeoPoint position = 4 [json_name = "position"];`
     */
    public fun clearPosition() {
      _builder.clearPosition()
    }
    /**
     * ```
     * optional (events without GPS are valid)
     * ```
     *
     * `.addressiq.v1.GeoPoint position = 4 [json_name = "position"];`
     * @return Whether the position field is set.
     */
    public fun hasPosition(): kotlin.Boolean {
      return _builder.hasPosition()
    }

    /**
     * <code>double accuracy_m = 5 [json_name = "accuracyM"];</code>
     */
    public var accuracyM: kotlin.Double
      @JvmName("getAccuracyM")
      get() = _builder.getAccuracyM()
      @JvmName("setAccuracyM")
      set(value) {
        _builder.setAccuracyM(value)
      }
    /**
     * `double accuracy_m = 5 [json_name = "accuracyM"];`
     */
    public fun clearAccuracyM() {
      _builder.clearAccuracyM()
    }

    /**
     * <code>double distance_from_pin_m = 6 [json_name = "distanceFromPinM"];</code>
     */
    public var distanceFromPinM: kotlin.Double
      @JvmName("getDistanceFromPinM")
      get() = _builder.getDistanceFromPinM()
      @JvmName("setDistanceFromPinM")
      set(value) {
        _builder.setDistanceFromPinM(value)
      }
    /**
     * `double distance_from_pin_m = 6 [json_name = "distanceFromPinM"];`
     */
    public fun clearDistanceFromPinM() {
      _builder.clearDistanceFromPinM()
    }

    /**
     * `.addressiq.v1.ActivityType activity_type = 7 [json_name = "activityType"];`
     */
    public var activityType: addressiq.v1.Telemetry.ActivityType
      @JvmName("getActivityType")
      get() = _builder.getActivityType()
      @JvmName("setActivityType")
      set(value) {
        _builder.setActivityType(value)
      }
    public var activityTypeValue: kotlin.Int
      @JvmName("getActivityTypeValue")
      get() = _builder.getActivityTypeValue()
      @JvmName("setActivityTypeValue")
      set(value) {
        _builder.setActivityTypeValue(value)
      }
    /**
     * `.addressiq.v1.ActivityType activity_type = 7 [json_name = "activityType"];`
     */
    public fun clearActivityType() {
      _builder.clearActivityType()
    }

    /**
     * <pre>
     * 0..100
     * </pre>
     *
     * <code>int32 activity_confidence = 8 [json_name = "activityConfidence"];</code>
     */
    public var activityConfidence: kotlin.Int
      @JvmName("getActivityConfidence")
      get() = _builder.getActivityConfidence()
      @JvmName("setActivityConfidence")
      set(value) {
        _builder.setActivityConfidence(value)
      }
    /**
     * ```
     * 0..100
     * ```
     *
     * `int32 activity_confidence = 8 [json_name = "activityConfidence"];`
     */
    public fun clearActivityConfidence() {
      _builder.clearActivityConfidence()
    }

    /**
     * <pre>
     * 0..100
     * </pre>
     *
     * <code>int32 battery_level = 9 [json_name = "batteryLevel"];</code>
     */
    public var batteryLevel: kotlin.Int
      @JvmName("getBatteryLevel")
      get() = _builder.getBatteryLevel()
      @JvmName("setBatteryLevel")
      set(value) {
        _builder.setBatteryLevel(value)
      }
    /**
     * ```
     * 0..100
     * ```
     *
     * `int32 battery_level = 9 [json_name = "batteryLevel"];`
     */
    public fun clearBatteryLevel() {
      _builder.clearBatteryLevel()
    }

    /**
     * <code>bool is_charging = 10 [json_name = "isCharging"];</code>
     */
    public var isCharging: kotlin.Boolean
      @JvmName("getIsCharging")
      get() = _builder.getIsCharging()
      @JvmName("setIsCharging")
      set(value) {
        _builder.setIsCharging(value)
      }
    /**
     * `bool is_charging = 10 [json_name = "isCharging"];`
     */
    public fun clearIsCharging() {
      _builder.clearIsCharging()
    }

    /**
     * `.addressiq.v1.DeviceOs device_os = 11 [json_name = "deviceOs"];`
     */
    public var deviceOs: addressiq.v1.Telemetry.DeviceOs
      @JvmName("getDeviceOs")
      get() = _builder.getDeviceOs()
      @JvmName("setDeviceOs")
      set(value) {
        _builder.setDeviceOs(value)
      }
    public var deviceOsValue: kotlin.Int
      @JvmName("getDeviceOsValue")
      get() = _builder.getDeviceOsValue()
      @JvmName("setDeviceOsValue")
      set(value) {
        _builder.setDeviceOsValue(value)
      }
    /**
     * `.addressiq.v1.DeviceOs device_os = 11 [json_name = "deviceOs"];`
     */
    public fun clearDeviceOs() {
      _builder.clearDeviceOs()
    }

    /**
     * `string sdk_version = 12 [json_name = "sdkVersion"];`
     */
    public var sdkVersion: kotlin.String
      @JvmName("getSdkVersion")
      get() = _builder.getSdkVersion()
      @JvmName("setSdkVersion")
      set(value) {
        _builder.setSdkVersion(value)
      }
    /**
     * `string sdk_version = 12 [json_name = "sdkVersion"];`
     */
    public fun clearSdkVersion() {
      _builder.clearSdkVersion()
    }

    /**
     * `.google.protobuf.Timestamp device_timestamp = 13 [json_name = "deviceTimestamp"];`
     */
    public var deviceTimestamp: com.google.protobuf.Timestamp
      @JvmName("getDeviceTimestamp")
      get() = _builder.getDeviceTimestamp()
      @JvmName("setDeviceTimestamp")
      set(value) {
        _builder.setDeviceTimestamp(value)
      }
    /**
     * `.google.protobuf.Timestamp device_timestamp = 13 [json_name = "deviceTimestamp"];`
     */
    public fun clearDeviceTimestamp() {
      _builder.clearDeviceTimestamp()
    }
    /**
     * `.google.protobuf.Timestamp device_timestamp = 13 [json_name = "deviceTimestamp"];`
     * @return Whether the deviceTimestamp field is set.
     */
    public fun hasDeviceTimestamp(): kotlin.Boolean {
      return _builder.hasDeviceTimestamp()
    }

    /**
     * `.addressiq.v1.SecurityEnvelope security = 14 [json_name = "security"];`
     */
    public var security: addressiq.v1.Telemetry.SecurityEnvelope
      @JvmName("getSecurity")
      get() = _builder.getSecurity()
      @JvmName("setSecurity")
      set(value) {
        _builder.setSecurity(value)
      }
    /**
     * `.addressiq.v1.SecurityEnvelope security = 14 [json_name = "security"];`
     */
    public fun clearSecurity() {
      _builder.clearSecurity()
    }
    /**
     * `.addressiq.v1.SecurityEnvelope security = 14 [json_name = "security"];`
     * @return Whether the security field is set.
     */
    public fun hasSecurity(): kotlin.Boolean {
      return _builder.hasSecurity()
    }
  }
}
public inline fun addressiq.v1.Telemetry.TransitEvent.copy(block: `addressiq.v1`.TransitEventKt.Dsl.() -> kotlin.Unit): addressiq.v1.Telemetry.TransitEvent =
  `addressiq.v1`.TransitEventKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val addressiq.v1.Telemetry.TransitEventOrBuilder.positionOrNull: addressiq.v1.Common.GeoPoint?
  get() = if (hasPosition()) getPosition() else null

public val addressiq.v1.Telemetry.TransitEventOrBuilder.deviceTimestampOrNull: com.google.protobuf.Timestamp?
  get() = if (hasDeviceTimestamp()) getDeviceTimestamp() else null

public val addressiq.v1.Telemetry.TransitEventOrBuilder.securityOrNull: addressiq.v1.Telemetry.SecurityEnvelope?
  get() = if (hasSecurity()) getSecurity() else null

