// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: addressiq/v1/verification.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package addressiq.v1;

