// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: addressiq/v1/sdk.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package addressiq.v1;

@kotlin.jvm.JvmName("-initializeverificationLifecycleState")
public inline fun verificationLifecycleState(block: addressiq.v1.VerificationLifecycleStateKt.Dsl.() -> kotlin.Unit): addressiq.v1.Sdk.VerificationLifecycleState =
  addressiq.v1.VerificationLifecycleStateKt.Dsl._create(addressiq.v1.Sdk.VerificationLifecycleState.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `addressiq.v1.VerificationLifecycleState`
 */
public object VerificationLifecycleStateKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: addressiq.v1.Sdk.VerificationLifecycleState.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: addressiq.v1.Sdk.VerificationLifecycleState.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): addressiq.v1.Sdk.VerificationLifecycleState = _builder.build()

    /**
     * `.addressiq.v1.LifecycleState state = 1 [json_name = "state"];`
     */
    public var state: addressiq.v1.Sdk.LifecycleState
      @JvmName("getState")
      get() = _builder.getState()
      @JvmName("setState")
      set(value) {
        _builder.setState(value)
      }
    public var stateValue: kotlin.Int
      @JvmName("getStateValue")
      get() = _builder.getStateValue()
      @JvmName("setStateValue")
      set(value) {
        _builder.setStateValue(value)
      }
    /**
     * `.addressiq.v1.LifecycleState state = 1 [json_name = "state"];`
     */
    public fun clearState() {
      _builder.clearState()
    }

    /**
     * `string app_user_id = 2 [json_name = "appUserId"];`
     */
    public var appUserId: kotlin.String
      @JvmName("getAppUserId")
      get() = _builder.getAppUserId()
      @JvmName("setAppUserId")
      set(value) {
        _builder.setAppUserId(value)
      }
    /**
     * `string app_user_id = 2 [json_name = "appUserId"];`
     */
    public fun clearAppUserId() {
      _builder.clearAppUserId()
    }

    /**
     * `string verification_id = 3 [json_name = "verificationId"];`
     */
    public var verificationId: kotlin.String
      @JvmName("getVerificationId")
      get() = _builder.getVerificationId()
      @JvmName("setVerificationId")
      set(value) {
        _builder.setVerificationId(value)
      }
    /**
     * `string verification_id = 3 [json_name = "verificationId"];`
     */
    public fun clearVerificationId() {
      _builder.clearVerificationId()
    }

    /**
     * `string location_code = 4 [json_name = "locationCode"];`
     */
    public var locationCode: kotlin.String
      @JvmName("getLocationCode")
      get() = _builder.getLocationCode()
      @JvmName("setLocationCode")
      set(value) {
        _builder.setLocationCode(value)
      }
    /**
     * `string location_code = 4 [json_name = "locationCode"];`
     */
    public fun clearLocationCode() {
      _builder.clearLocationCode()
    }

    /**
     * <code>int64 paused_for_ms = 5 [json_name = "pausedForMs"];</code>
     */
    public var pausedForMs: kotlin.Long
      @JvmName("getPausedForMs")
      get() = _builder.getPausedForMs()
      @JvmName("setPausedForMs")
      set(value) {
        _builder.setPausedForMs(value)
      }
    /**
     * `int64 paused_for_ms = 5 [json_name = "pausedForMs"];`
     */
    public fun clearPausedForMs() {
      _builder.clearPausedForMs()
    }
  }
}
public inline fun addressiq.v1.Sdk.VerificationLifecycleState.copy(block: `addressiq.v1`.VerificationLifecycleStateKt.Dsl.() -> kotlin.Unit): addressiq.v1.Sdk.VerificationLifecycleState =
  `addressiq.v1`.VerificationLifecycleStateKt.Dsl._create(this.toBuilder()).apply { block() }._build()

