// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: addressiq/v1/verification.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package addressiq.v1;

@kotlin.jvm.JvmName("-initializeverification")
public inline fun verification(block: addressiq.v1.VerificationKt.Dsl.() -> kotlin.Unit): addressiq.v1.VerificationOuterClass.Verification =
  addressiq.v1.VerificationKt.Dsl._create(addressiq.v1.VerificationOuterClass.Verification.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `addressiq.v1.Verification`
 */
public object VerificationKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: addressiq.v1.VerificationOuterClass.Verification.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: addressiq.v1.VerificationOuterClass.Verification.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): addressiq.v1.VerificationOuterClass.Verification = _builder.build()

    /**
     * `string id = 1 [json_name = "id"];`
     */
    public var id: kotlin.String
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * `string id = 1 [json_name = "id"];`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `string verification_code = 2 [json_name = "verificationCode"];`
     */
    public var verificationCode: kotlin.String
      @JvmName("getVerificationCode")
      get() = _builder.getVerificationCode()
      @JvmName("setVerificationCode")
      set(value) {
        _builder.setVerificationCode(value)
      }
    /**
     * `string verification_code = 2 [json_name = "verificationCode"];`
     */
    public fun clearVerificationCode() {
      _builder.clearVerificationCode()
    }

    /**
     * `string organization_id = 3 [json_name = "organizationId"];`
     */
    public var organizationId: kotlin.String
      @JvmName("getOrganizationId")
      get() = _builder.getOrganizationId()
      @JvmName("setOrganizationId")
      set(value) {
        _builder.setOrganizationId(value)
      }
    /**
     * `string organization_id = 3 [json_name = "organizationId"];`
     */
    public fun clearOrganizationId() {
      _builder.clearOrganizationId()
    }

    /**
     * `string app_id = 4 [json_name = "appId"];`
     */
    public var appId: kotlin.String
      @JvmName("getAppId")
      get() = _builder.getAppId()
      @JvmName("setAppId")
      set(value) {
        _builder.setAppId(value)
      }
    /**
     * `string app_id = 4 [json_name = "appId"];`
     */
    public fun clearAppId() {
      _builder.clearAppId()
    }

    /**
     * `string branch_id = 5 [json_name = "branchId"];`
     */
    public var branchId: kotlin.String
      @JvmName("getBranchId")
      get() = _builder.getBranchId()
      @JvmName("setBranchId")
      set(value) {
        _builder.setBranchId(value)
      }
    /**
     * `string branch_id = 5 [json_name = "branchId"];`
     */
    public fun clearBranchId() {
      _builder.clearBranchId()
    }

    /**
     * `string app_user_id = 6 [json_name = "appUserId"];`
     */
    public var appUserId: kotlin.String
      @JvmName("getAppUserId")
      get() = _builder.getAppUserId()
      @JvmName("setAppUserId")
      set(value) {
        _builder.setAppUserId(value)
      }
    /**
     * `string app_user_id = 6 [json_name = "appUserId"];`
     */
    public fun clearAppUserId() {
      _builder.clearAppUserId()
    }

    /**
     * `string location_id = 7 [json_name = "locationId"];`
     */
    public var locationId: kotlin.String
      @JvmName("getLocationId")
      get() = _builder.getLocationId()
      @JvmName("setLocationId")
      set(value) {
        _builder.setLocationId(value)
      }
    /**
     * `string location_id = 7 [json_name = "locationId"];`
     */
    public fun clearLocationId() {
      _builder.clearLocationId()
    }

    /**
     * `.addressiq.v1.VerificationType type = 8 [json_name = "type"];`
     */
    public var type: addressiq.v1.VerificationOuterClass.VerificationType
      @JvmName("getType")
      get() = _builder.getType()
      @JvmName("setType")
      set(value) {
        _builder.setType(value)
      }
    public var typeValue: kotlin.Int
      @JvmName("getTypeValue")
      get() = _builder.getTypeValue()
      @JvmName("setTypeValue")
      set(value) {
        _builder.setTypeValue(value)
      }
    /**
     * `.addressiq.v1.VerificationType type = 8 [json_name = "type"];`
     */
    public fun clearType() {
      _builder.clearType()
    }

    /**
     * ```
     * slug
     * ```
     *
     * `string provider = 9 [json_name = "provider"];`
     */
    public var provider: kotlin.String
      @JvmName("getProvider")
      get() = _builder.getProvider()
      @JvmName("setProvider")
      set(value) {
        _builder.setProvider(value)
      }
    /**
     * ```
     * slug
     * ```
     *
     * `string provider = 9 [json_name = "provider"];`
     */
    public fun clearProvider() {
      _builder.clearProvider()
    }

    /**
     * `string provider_reference_id = 10 [json_name = "providerReferenceId"];`
     */
    public var providerReferenceId: kotlin.String
      @JvmName("getProviderReferenceId")
      get() = _builder.getProviderReferenceId()
      @JvmName("setProviderReferenceId")
      set(value) {
        _builder.setProviderReferenceId(value)
      }
    /**
     * `string provider_reference_id = 10 [json_name = "providerReferenceId"];`
     */
    public fun clearProviderReferenceId() {
      _builder.clearProviderReferenceId()
    }

    /**
     * `.addressiq.v1.VerificationStatus status = 11 [json_name = "status"];`
     */
    public var status: addressiq.v1.VerificationOuterClass.VerificationStatus
      @JvmName("getStatus")
      get() = _builder.getStatus()
      @JvmName("setStatus")
      set(value) {
        _builder.setStatus(value)
      }
    public var statusValue: kotlin.Int
      @JvmName("getStatusValue")
      get() = _builder.getStatusValue()
      @JvmName("setStatusValue")
      set(value) {
        _builder.setStatusValue(value)
      }
    /**
     * `.addressiq.v1.VerificationStatus status = 11 [json_name = "status"];`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * `.addressiq.v1.ReviewState review_state = 12 [json_name = "reviewState"];`
     */
    public var reviewState: addressiq.v1.VerificationOuterClass.ReviewState
      @JvmName("getReviewState")
      get() = _builder.getReviewState()
      @JvmName("setReviewState")
      set(value) {
        _builder.setReviewState(value)
      }
    public var reviewStateValue: kotlin.Int
      @JvmName("getReviewStateValue")
      get() = _builder.getReviewStateValue()
      @JvmName("setReviewStateValue")
      set(value) {
        _builder.setReviewStateValue(value)
      }
    /**
     * `.addressiq.v1.ReviewState review_state = 12 [json_name = "reviewState"];`
     */
    public fun clearReviewState() {
      _builder.clearReviewState()
    }

    /**
     * <code>double confidence_score = 13 [json_name = "confidenceScore"];</code>
     */
    public var confidenceScore: kotlin.Double
      @JvmName("getConfidenceScore")
      get() = _builder.getConfidenceScore()
      @JvmName("setConfidenceScore")
      set(value) {
        _builder.setConfidenceScore(value)
      }
    /**
     * `double confidence_score = 13 [json_name = "confidenceScore"];`
     */
    public fun clearConfidenceScore() {
      _builder.clearConfidenceScore()
    }

    /**
     * `.google.protobuf.Timestamp window_ends_at = 14 [json_name = "windowEndsAt"];`
     */
    public var windowEndsAt: com.google.protobuf.Timestamp
      @JvmName("getWindowEndsAt")
      get() = _builder.getWindowEndsAt()
      @JvmName("setWindowEndsAt")
      set(value) {
        _builder.setWindowEndsAt(value)
      }
    /**
     * `.google.protobuf.Timestamp window_ends_at = 14 [json_name = "windowEndsAt"];`
     */
    public fun clearWindowEndsAt() {
      _builder.clearWindowEndsAt()
    }
    /**
     * `.google.protobuf.Timestamp window_ends_at = 14 [json_name = "windowEndsAt"];`
     * @return Whether the windowEndsAt field is set.
     */
    public fun hasWindowEndsAt(): kotlin.Boolean {
      return _builder.hasWindowEndsAt()
    }

    /**
     * `.google.protobuf.Timestamp resolved_at = 15 [json_name = "resolvedAt"];`
     */
    public var resolvedAt: com.google.protobuf.Timestamp
      @JvmName("getResolvedAt")
      get() = _builder.getResolvedAt()
      @JvmName("setResolvedAt")
      set(value) {
        _builder.setResolvedAt(value)
      }
    /**
     * `.google.protobuf.Timestamp resolved_at = 15 [json_name = "resolvedAt"];`
     */
    public fun clearResolvedAt() {
      _builder.clearResolvedAt()
    }
    /**
     * `.google.protobuf.Timestamp resolved_at = 15 [json_name = "resolvedAt"];`
     * @return Whether the resolvedAt field is set.
     */
    public fun hasResolvedAt(): kotlin.Boolean {
      return _builder.hasResolvedAt()
    }
  }
}
public inline fun addressiq.v1.VerificationOuterClass.Verification.copy(block: `addressiq.v1`.VerificationKt.Dsl.() -> kotlin.Unit): addressiq.v1.VerificationOuterClass.Verification =
  `addressiq.v1`.VerificationKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val addressiq.v1.VerificationOuterClass.VerificationOrBuilder.windowEndsAtOrNull: com.google.protobuf.Timestamp?
  get() = if (hasWindowEndsAt()) getWindowEndsAt() else null

public val addressiq.v1.VerificationOuterClass.VerificationOrBuilder.resolvedAtOrNull: com.google.protobuf.Timestamp?
  get() = if (hasResolvedAt()) getResolvedAt() else null

