// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressiq/v1/common.proto

// Protobuf Java Version: 3.25.3
package addressiq.v1;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code addressiq.v1.EnvironmentBucket}
   */
  public enum EnvironmentBucket
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>ENVIRONMENT_BUCKET_UNSPECIFIED = 0;</code>
     */
    ENVIRONMENT_BUCKET_UNSPECIFIED(0),
    /**
     * <code>DENSE_URBAN = 1;</code>
     */
    DENSE_URBAN(1),
    /**
     * <code>URBAN = 2;</code>
     */
    URBAN(2),
    /**
     * <code>SUBURBAN = 3;</code>
     */
    SUBURBAN(3),
    /**
     * <code>RURAL = 4;</code>
     */
    RURAL(4),
    /**
     * <code>SPARSE_RURAL = 5;</code>
     */
    SPARSE_RURAL(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ENVIRONMENT_BUCKET_UNSPECIFIED = 0;</code>
     */
    public static final int ENVIRONMENT_BUCKET_UNSPECIFIED_VALUE = 0;
    /**
     * <code>DENSE_URBAN = 1;</code>
     */
    public static final int DENSE_URBAN_VALUE = 1;
    /**
     * <code>URBAN = 2;</code>
     */
    public static final int URBAN_VALUE = 2;
    /**
     * <code>SUBURBAN = 3;</code>
     */
    public static final int SUBURBAN_VALUE = 3;
    /**
     * <code>RURAL = 4;</code>
     */
    public static final int RURAL_VALUE = 4;
    /**
     * <code>SPARSE_RURAL = 5;</code>
     */
    public static final int SPARSE_RURAL_VALUE = 5;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EnvironmentBucket valueOf(int value) {
      return forNumber(value);
    }

    public static EnvironmentBucket forNumber(int value) {
      switch (value) {
        case 0: return ENVIRONMENT_BUCKET_UNSPECIFIED;
        case 1: return DENSE_URBAN;
        case 2: return URBAN;
        case 3: return SUBURBAN;
        case 4: return RURAL;
        case 5: return SPARSE_RURAL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EnvironmentBucket>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EnvironmentBucket> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EnvironmentBucket>() {
            @java.lang.Override
            public EnvironmentBucket findValueByNumber(int number) {
              return EnvironmentBucket.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return EnvironmentBucketVerifier.INSTANCE;
    }

    private static final class EnvironmentBucketVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new EnvironmentBucketVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return EnvironmentBucket.forNumber(number) != null;
            }
          };

    private final int value;

    private EnvironmentBucket(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:addressiq.v1.EnvironmentBucket)
  }

  /**
   * <pre>
   * The single closed set of error codes every SDK must carry. New entries
   * require a spec change in docs/sdk-contract.md §3.
   * </pre>
   *
   * Protobuf enum {@code addressiq.v1.ErrorCode}
   */
  public enum ErrorCode
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>ERROR_CODE_UNSPECIFIED = 0;</code>
     */
    ERROR_CODE_UNSPECIFIED(0),
    /**
     * <code>SDK_NOT_INITIALIZED = 1;</code>
     */
    SDK_NOT_INITIALIZED(1),
    /**
     * <code>INVALID_CONFIG = 2;</code>
     */
    INVALID_CONFIG(2),
    /**
     * <code>INVALID_USER = 3;</code>
     */
    INVALID_USER(3),
    /**
     * <code>NO_ACTIVE_SESSION = 4;</code>
     */
    NO_ACTIVE_SESSION(4),
    /**
     * <code>IDEMPOTENCY_KEY_REQUIRED = 5;</code>
     */
    IDEMPOTENCY_KEY_REQUIRED(5),
    /**
     * <code>IDEMPOTENCY_KEY_INVALID = 6;</code>
     */
    IDEMPOTENCY_KEY_INVALID(6),
    /**
     * <code>IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_PAYLOAD = 7;</code>
     */
    IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_PAYLOAD(7),
    /**
     * <code>PROVIDER_NOT_FOUND = 8;</code>
     */
    PROVIDER_NOT_FOUND(8),
    /**
     * <code>PROVIDER_DISABLED_FOR_ORG = 9;</code>
     */
    PROVIDER_DISABLED_FOR_ORG(9),
    /**
     * <code>PROVIDER_TYPE_MISMATCH = 10;</code>
     */
    PROVIDER_TYPE_MISMATCH(10),
    /**
     * <code>PRODUCT_NOT_SUBSCRIBED = 11;</code>
     */
    PRODUCT_NOT_SUBSCRIBED(11),
    /**
     * <code>PHOTO_HASH_REUSED = 12;</code>
     */
    PHOTO_HASH_REUSED(12),
    /**
     * <code>VERIFICATION_ILLEGAL_TRANSITION = 13;</code>
     */
    VERIFICATION_ILLEGAL_TRANSITION(13),
    /**
     * <code>BROWSER_VERIFICATION_NOT_SUPPORTED = 14;</code>
     */
    BROWSER_VERIFICATION_NOT_SUPPORTED(14),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ERROR_CODE_UNSPECIFIED = 0;</code>
     */
    public static final int ERROR_CODE_UNSPECIFIED_VALUE = 0;
    /**
     * <code>SDK_NOT_INITIALIZED = 1;</code>
     */
    public static final int SDK_NOT_INITIALIZED_VALUE = 1;
    /**
     * <code>INVALID_CONFIG = 2;</code>
     */
    public static final int INVALID_CONFIG_VALUE = 2;
    /**
     * <code>INVALID_USER = 3;</code>
     */
    public static final int INVALID_USER_VALUE = 3;
    /**
     * <code>NO_ACTIVE_SESSION = 4;</code>
     */
    public static final int NO_ACTIVE_SESSION_VALUE = 4;
    /**
     * <code>IDEMPOTENCY_KEY_REQUIRED = 5;</code>
     */
    public static final int IDEMPOTENCY_KEY_REQUIRED_VALUE = 5;
    /**
     * <code>IDEMPOTENCY_KEY_INVALID = 6;</code>
     */
    public static final int IDEMPOTENCY_KEY_INVALID_VALUE = 6;
    /**
     * <code>IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_PAYLOAD = 7;</code>
     */
    public static final int IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_PAYLOAD_VALUE = 7;
    /**
     * <code>PROVIDER_NOT_FOUND = 8;</code>
     */
    public static final int PROVIDER_NOT_FOUND_VALUE = 8;
    /**
     * <code>PROVIDER_DISABLED_FOR_ORG = 9;</code>
     */
    public static final int PROVIDER_DISABLED_FOR_ORG_VALUE = 9;
    /**
     * <code>PROVIDER_TYPE_MISMATCH = 10;</code>
     */
    public static final int PROVIDER_TYPE_MISMATCH_VALUE = 10;
    /**
     * <code>PRODUCT_NOT_SUBSCRIBED = 11;</code>
     */
    public static final int PRODUCT_NOT_SUBSCRIBED_VALUE = 11;
    /**
     * <code>PHOTO_HASH_REUSED = 12;</code>
     */
    public static final int PHOTO_HASH_REUSED_VALUE = 12;
    /**
     * <code>VERIFICATION_ILLEGAL_TRANSITION = 13;</code>
     */
    public static final int VERIFICATION_ILLEGAL_TRANSITION_VALUE = 13;
    /**
     * <code>BROWSER_VERIFICATION_NOT_SUPPORTED = 14;</code>
     */
    public static final int BROWSER_VERIFICATION_NOT_SUPPORTED_VALUE = 14;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ErrorCode valueOf(int value) {
      return forNumber(value);
    }

    public static ErrorCode forNumber(int value) {
      switch (value) {
        case 0: return ERROR_CODE_UNSPECIFIED;
        case 1: return SDK_NOT_INITIALIZED;
        case 2: return INVALID_CONFIG;
        case 3: return INVALID_USER;
        case 4: return NO_ACTIVE_SESSION;
        case 5: return IDEMPOTENCY_KEY_REQUIRED;
        case 6: return IDEMPOTENCY_KEY_INVALID;
        case 7: return IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_PAYLOAD;
        case 8: return PROVIDER_NOT_FOUND;
        case 9: return PROVIDER_DISABLED_FOR_ORG;
        case 10: return PROVIDER_TYPE_MISMATCH;
        case 11: return PRODUCT_NOT_SUBSCRIBED;
        case 12: return PHOTO_HASH_REUSED;
        case 13: return VERIFICATION_ILLEGAL_TRANSITION;
        case 14: return BROWSER_VERIFICATION_NOT_SUPPORTED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ErrorCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ErrorCode>() {
            @java.lang.Override
            public ErrorCode findValueByNumber(int number) {
              return ErrorCode.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return ErrorCodeVerifier.INSTANCE;
    }

    private static final class ErrorCodeVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new ErrorCodeVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return ErrorCode.forNumber(number) != null;
            }
          };

    private final int value;

    private ErrorCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:addressiq.v1.ErrorCode)
  }

  public interface OrganizationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:addressiq.v1.Organization)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string slug = 3 [json_name = "slug"];</code>
     * @return The slug.
     */
    java.lang.String getSlug();
    /**
     * <code>string slug = 3 [json_name = "slug"];</code>
     * @return The bytes for slug.
     */
    com.google.protobuf.ByteString
        getSlugBytes();

    /**
     * <code>string country = 4 [json_name = "country"];</code>
     * @return The country.
     */
    java.lang.String getCountry();
    /**
     * <code>string country = 4 [json_name = "country"];</code>
     * @return The bytes for country.
     */
    com.google.protobuf.ByteString
        getCountryBytes();

    /**
     * <code>string status = 5 [json_name = "status"];</code>
     * @return The status.
     */
    java.lang.String getStatus();
    /**
     * <code>string status = 5 [json_name = "status"];</code>
     * @return The bytes for status.
     */
    com.google.protobuf.ByteString
        getStatusBytes();
  }
  /**
   * Protobuf type {@code addressiq.v1.Organization}
   */
  public  static final class Organization extends
      com.google.protobuf.GeneratedMessageLite<
          Organization, Organization.Builder> implements
      // @@protoc_insertion_point(message_implements:addressiq.v1.Organization)
      OrganizationOrBuilder {
    private Organization() {
      id_ = "";
      name_ = "";
      slug_ = "";
      country_ = "";
      status_ = "";
    }
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.String id_;
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      return id_;
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(id_);
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The id to set.
     */
    private void setId(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      id_ = value;
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     */
    private void clearId() {

      id_ = getDefaultInstance().getId();
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The bytes for id to set.
     */
    private void setIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      id_ = value.toStringUtf8();

    }

    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.String name_;
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      return name_;
    }
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(name_);
    }
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @param value The name to set.
     */
    private void setName(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      name_ = value;
    }
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     */
    private void clearName() {

      name_ = getDefaultInstance().getName();
    }
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @param value The bytes for name to set.
     */
    private void setNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      name_ = value.toStringUtf8();

    }

    public static final int SLUG_FIELD_NUMBER = 3;
    private java.lang.String slug_;
    /**
     * <code>string slug = 3 [json_name = "slug"];</code>
     * @return The slug.
     */
    @java.lang.Override
    public java.lang.String getSlug() {
      return slug_;
    }
    /**
     * <code>string slug = 3 [json_name = "slug"];</code>
     * @return The bytes for slug.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSlugBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(slug_);
    }
    /**
     * <code>string slug = 3 [json_name = "slug"];</code>
     * @param value The slug to set.
     */
    private void setSlug(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      slug_ = value;
    }
    /**
     * <code>string slug = 3 [json_name = "slug"];</code>
     */
    private void clearSlug() {

      slug_ = getDefaultInstance().getSlug();
    }
    /**
     * <code>string slug = 3 [json_name = "slug"];</code>
     * @param value The bytes for slug to set.
     */
    private void setSlugBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      slug_ = value.toStringUtf8();

    }

    public static final int COUNTRY_FIELD_NUMBER = 4;
    private java.lang.String country_;
    /**
     * <code>string country = 4 [json_name = "country"];</code>
     * @return The country.
     */
    @java.lang.Override
    public java.lang.String getCountry() {
      return country_;
    }
    /**
     * <code>string country = 4 [json_name = "country"];</code>
     * @return The bytes for country.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCountryBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(country_);
    }
    /**
     * <code>string country = 4 [json_name = "country"];</code>
     * @param value The country to set.
     */
    private void setCountry(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      country_ = value;
    }
    /**
     * <code>string country = 4 [json_name = "country"];</code>
     */
    private void clearCountry() {

      country_ = getDefaultInstance().getCountry();
    }
    /**
     * <code>string country = 4 [json_name = "country"];</code>
     * @param value The bytes for country to set.
     */
    private void setCountryBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      country_ = value.toStringUtf8();

    }

    public static final int STATUS_FIELD_NUMBER = 5;
    private java.lang.String status_;
    /**
     * <code>string status = 5 [json_name = "status"];</code>
     * @return The status.
     */
    @java.lang.Override
    public java.lang.String getStatus() {
      return status_;
    }
    /**
     * <code>string status = 5 [json_name = "status"];</code>
     * @return The bytes for status.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStatusBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(status_);
    }
    /**
     * <code>string status = 5 [json_name = "status"];</code>
     * @param value The status to set.
     */
    private void setStatus(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      status_ = value;
    }
    /**
     * <code>string status = 5 [json_name = "status"];</code>
     */
    private void clearStatus() {

      status_ = getDefaultInstance().getStatus();
    }
    /**
     * <code>string status = 5 [json_name = "status"];</code>
     * @param value The bytes for status to set.
     */
    private void setStatusBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      status_ = value.toStringUtf8();

    }

    public static addressiq.v1.Common.Organization parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static addressiq.v1.Common.Organization parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static addressiq.v1.Common.Organization parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static addressiq.v1.Common.Organization parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static addressiq.v1.Common.Organization parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static addressiq.v1.Common.Organization parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static addressiq.v1.Common.Organization parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static addressiq.v1.Common.Organization parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static addressiq.v1.Common.Organization parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static addressiq.v1.Common.Organization parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static addressiq.v1.Common.Organization parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static addressiq.v1.Common.Organization parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(addressiq.v1.Common.Organization prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code addressiq.v1.Organization}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          addressiq.v1.Common.Organization, Builder> implements
        // @@protoc_insertion_point(builder_implements:addressiq.v1.Organization)
        addressiq.v1.Common.OrganizationOrBuilder {
      // Construct using addressiq.v1.Common.Organization.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string id = 1 [json_name = "id"];</code>
       * @return The id.
       */
      @java.lang.Override
      public java.lang.String getId() {
        return instance.getId();
      }
      /**
       * <code>string id = 1 [json_name = "id"];</code>
       * @return The bytes for id.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getIdBytes() {
        return instance.getIdBytes();
      }
      /**
       * <code>string id = 1 [json_name = "id"];</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        copyOnWrite();
        instance.setId(value);
        return this;
      }
      /**
       * <code>string id = 1 [json_name = "id"];</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        copyOnWrite();
        instance.clearId();
        return this;
      }
      /**
       * <code>string id = 1 [json_name = "id"];</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setIdBytes(value);
        return this;
      }

      /**
       * <code>string name = 2 [json_name = "name"];</code>
       * @return The name.
       */
      @java.lang.Override
      public java.lang.String getName() {
        return instance.getName();
      }
      /**
       * <code>string name = 2 [json_name = "name"];</code>
       * @return The bytes for name.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getNameBytes() {
        return instance.getNameBytes();
      }
      /**
       * <code>string name = 2 [json_name = "name"];</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        copyOnWrite();
        instance.setName(value);
        return this;
      }
      /**
       * <code>string name = 2 [json_name = "name"];</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        copyOnWrite();
        instance.clearName();
        return this;
      }
      /**
       * <code>string name = 2 [json_name = "name"];</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNameBytes(value);
        return this;
      }

      /**
       * <code>string slug = 3 [json_name = "slug"];</code>
       * @return The slug.
       */
      @java.lang.Override
      public java.lang.String getSlug() {
        return instance.getSlug();
      }
      /**
       * <code>string slug = 3 [json_name = "slug"];</code>
       * @return The bytes for slug.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getSlugBytes() {
        return instance.getSlugBytes();
      }
      /**
       * <code>string slug = 3 [json_name = "slug"];</code>
       * @param value The slug to set.
       * @return This builder for chaining.
       */
      public Builder setSlug(
          java.lang.String value) {
        copyOnWrite();
        instance.setSlug(value);
        return this;
      }
      /**
       * <code>string slug = 3 [json_name = "slug"];</code>
       * @return This builder for chaining.
       */
      public Builder clearSlug() {
        copyOnWrite();
        instance.clearSlug();
        return this;
      }
      /**
       * <code>string slug = 3 [json_name = "slug"];</code>
       * @param value The bytes for slug to set.
       * @return This builder for chaining.
       */
      public Builder setSlugBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSlugBytes(value);
        return this;
      }

      /**
       * <code>string country = 4 [json_name = "country"];</code>
       * @return The country.
       */
      @java.lang.Override
      public java.lang.String getCountry() {
        return instance.getCountry();
      }
      /**
       * <code>string country = 4 [json_name = "country"];</code>
       * @return The bytes for country.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getCountryBytes() {
        return instance.getCountryBytes();
      }
      /**
       * <code>string country = 4 [json_name = "country"];</code>
       * @param value The country to set.
       * @return This builder for chaining.
       */
      public Builder setCountry(
          java.lang.String value) {
        copyOnWrite();
        instance.setCountry(value);
        return this;
      }
      /**
       * <code>string country = 4 [json_name = "country"];</code>
       * @return This builder for chaining.
       */
      public Builder clearCountry() {
        copyOnWrite();
        instance.clearCountry();
        return this;
      }
      /**
       * <code>string country = 4 [json_name = "country"];</code>
       * @param value The bytes for country to set.
       * @return This builder for chaining.
       */
      public Builder setCountryBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setCountryBytes(value);
        return this;
      }

      /**
       * <code>string status = 5 [json_name = "status"];</code>
       * @return The status.
       */
      @java.lang.Override
      public java.lang.String getStatus() {
        return instance.getStatus();
      }
      /**
       * <code>string status = 5 [json_name = "status"];</code>
       * @return The bytes for status.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getStatusBytes() {
        return instance.getStatusBytes();
      }
      /**
       * <code>string status = 5 [json_name = "status"];</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(
          java.lang.String value) {
        copyOnWrite();
        instance.setStatus(value);
        return this;
      }
      /**
       * <code>string status = 5 [json_name = "status"];</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        copyOnWrite();
        instance.clearStatus();
        return this;
      }
      /**
       * <code>string status = 5 [json_name = "status"];</code>
       * @param value The bytes for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setStatusBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:addressiq.v1.Organization)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new addressiq.v1.Common.Organization();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "id_",
              "name_",
              "slug_",
              "country_",
              "status_",
            };
            java.lang.String info =
                "\u0000\u0005\u0000\u0000\u0001\u0005\u0005\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
                "\u0003\u0208\u0004\u0208\u0005\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<addressiq.v1.Common.Organization> parser = PARSER;
          if (parser == null) {
            synchronized (addressiq.v1.Common.Organization.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<addressiq.v1.Common.Organization>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:addressiq.v1.Organization)
    private static final addressiq.v1.Common.Organization DEFAULT_INSTANCE;
    static {
      Organization defaultInstance = new Organization();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Organization.class, defaultInstance);
    }

    public static addressiq.v1.Common.Organization getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Organization> PARSER;

    public static com.google.protobuf.Parser<Organization> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface AppUserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:addressiq.v1.AppUser)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string organization_id = 2 [json_name = "organizationId"];</code>
     * @return The organizationId.
     */
    java.lang.String getOrganizationId();
    /**
     * <code>string organization_id = 2 [json_name = "organizationId"];</code>
     * @return The bytes for organizationId.
     */
    com.google.protobuf.ByteString
        getOrganizationIdBytes();

    /**
     * <code>string app_id = 3 [json_name = "appId"];</code>
     * @return The appId.
     */
    java.lang.String getAppId();
    /**
     * <code>string app_id = 3 [json_name = "appId"];</code>
     * @return The bytes for appId.
     */
    com.google.protobuf.ByteString
        getAppIdBytes();

    /**
     * <code>string app_user_id = 4 [json_name = "appUserId"];</code>
     * @return The appUserId.
     */
    java.lang.String getAppUserId();
    /**
     * <code>string app_user_id = 4 [json_name = "appUserId"];</code>
     * @return The bytes for appUserId.
     */
    com.google.protobuf.ByteString
        getAppUserIdBytes();

    /**
     * <pre>
     * PII fields are NOT carried on the wire — only their hashes for
     * matching/dedup. Mobile SDKs encrypt locally before transit.
     * </pre>
     *
     * <code>string phone_hash = 5 [json_name = "phoneHash"];</code>
     * @return The phoneHash.
     */
    java.lang.String getPhoneHash();
    /**
     * <pre>
     * PII fields are NOT carried on the wire — only their hashes for
     * matching/dedup. Mobile SDKs encrypt locally before transit.
     * </pre>
     *
     * <code>string phone_hash = 5 [json_name = "phoneHash"];</code>
     * @return The bytes for phoneHash.
     */
    com.google.protobuf.ByteString
        getPhoneHashBytes();

    /**
     * <code>string email_hash = 6 [json_name = "emailHash"];</code>
     * @return The emailHash.
     */
    java.lang.String getEmailHash();
    /**
     * <code>string email_hash = 6 [json_name = "emailHash"];</code>
     * @return The bytes for emailHash.
     */
    com.google.protobuf.ByteString
        getEmailHashBytes();

    /**
     * <pre>
     * APP_USER_ID | PHONE | EMAIL | GENERATED
     * </pre>
     *
     * <code>string identity_source = 7 [json_name = "identitySource"];</code>
     * @return The identitySource.
     */
    java.lang.String getIdentitySource();
    /**
     * <pre>
     * APP_USER_ID | PHONE | EMAIL | GENERATED
     * </pre>
     *
     * <code>string identity_source = 7 [json_name = "identitySource"];</code>
     * @return The bytes for identitySource.
     */
    com.google.protobuf.ByteString
        getIdentitySourceBytes();
  }
  /**
   * Protobuf type {@code addressiq.v1.AppUser}
   */
  public  static final class AppUser extends
      com.google.protobuf.GeneratedMessageLite<
          AppUser, AppUser.Builder> implements
      // @@protoc_insertion_point(message_implements:addressiq.v1.AppUser)
      AppUserOrBuilder {
    private AppUser() {
      id_ = "";
      organizationId_ = "";
      appId_ = "";
      appUserId_ = "";
      phoneHash_ = "";
      emailHash_ = "";
      identitySource_ = "";
    }
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.String id_;
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      return id_;
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(id_);
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The id to set.
     */
    private void setId(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      id_ = value;
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     */
    private void clearId() {

      id_ = getDefaultInstance().getId();
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The bytes for id to set.
     */
    private void setIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      id_ = value.toStringUtf8();

    }

    public static final int ORGANIZATION_ID_FIELD_NUMBER = 2;
    private java.lang.String organizationId_;
    /**
     * <code>string organization_id = 2 [json_name = "organizationId"];</code>
     * @return The organizationId.
     */
    @java.lang.Override
    public java.lang.String getOrganizationId() {
      return organizationId_;
    }
    /**
     * <code>string organization_id = 2 [json_name = "organizationId"];</code>
     * @return The bytes for organizationId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOrganizationIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(organizationId_);
    }
    /**
     * <code>string organization_id = 2 [json_name = "organizationId"];</code>
     * @param value The organizationId to set.
     */
    private void setOrganizationId(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      organizationId_ = value;
    }
    /**
     * <code>string organization_id = 2 [json_name = "organizationId"];</code>
     */
    private void clearOrganizationId() {

      organizationId_ = getDefaultInstance().getOrganizationId();
    }
    /**
     * <code>string organization_id = 2 [json_name = "organizationId"];</code>
     * @param value The bytes for organizationId to set.
     */
    private void setOrganizationIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      organizationId_ = value.toStringUtf8();

    }

    public static final int APP_ID_FIELD_NUMBER = 3;
    private java.lang.String appId_;
    /**
     * <code>string app_id = 3 [json_name = "appId"];</code>
     * @return The appId.
     */
    @java.lang.Override
    public java.lang.String getAppId() {
      return appId_;
    }
    /**
     * <code>string app_id = 3 [json_name = "appId"];</code>
     * @return The bytes for appId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAppIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(appId_);
    }
    /**
     * <code>string app_id = 3 [json_name = "appId"];</code>
     * @param value The appId to set.
     */
    private void setAppId(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      appId_ = value;
    }
    /**
     * <code>string app_id = 3 [json_name = "appId"];</code>
     */
    private void clearAppId() {

      appId_ = getDefaultInstance().getAppId();
    }
    /**
     * <code>string app_id = 3 [json_name = "appId"];</code>
     * @param value The bytes for appId to set.
     */
    private void setAppIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      appId_ = value.toStringUtf8();

    }

    public static final int APP_USER_ID_FIELD_NUMBER = 4;
    private java.lang.String appUserId_;
    /**
     * <code>string app_user_id = 4 [json_name = "appUserId"];</code>
     * @return The appUserId.
     */
    @java.lang.Override
    public java.lang.String getAppUserId() {
      return appUserId_;
    }
    /**
     * <code>string app_user_id = 4 [json_name = "appUserId"];</code>
     * @return The bytes for appUserId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAppUserIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(appUserId_);
    }
    /**
     * <code>string app_user_id = 4 [json_name = "appUserId"];</code>
     * @param value The appUserId to set.
     */
    private void setAppUserId(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      appUserId_ = value;
    }
    /**
     * <code>string app_user_id = 4 [json_name = "appUserId"];</code>
     */
    private void clearAppUserId() {

      appUserId_ = getDefaultInstance().getAppUserId();
    }
    /**
     * <code>string app_user_id = 4 [json_name = "appUserId"];</code>
     * @param value The bytes for appUserId to set.
     */
    private void setAppUserIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      appUserId_ = value.toStringUtf8();

    }

    public static final int PHONE_HASH_FIELD_NUMBER = 5;
    private java.lang.String phoneHash_;
    /**
     * <pre>
     * PII fields are NOT carried on the wire — only their hashes for
     * matching/dedup. Mobile SDKs encrypt locally before transit.
     * </pre>
     *
     * <code>string phone_hash = 5 [json_name = "phoneHash"];</code>
     * @return The phoneHash.
     */
    @java.lang.Override
    public java.lang.String getPhoneHash() {
      return phoneHash_;
    }
    /**
     * <pre>
     * PII fields are NOT carried on the wire — only their hashes for
     * matching/dedup. Mobile SDKs encrypt locally before transit.
     * </pre>
     *
     * <code>string phone_hash = 5 [json_name = "phoneHash"];</code>
     * @return The bytes for phoneHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPhoneHashBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(phoneHash_);
    }
    /**
     * <pre>
     * PII fields are NOT carried on the wire — only their hashes for
     * matching/dedup. Mobile SDKs encrypt locally before transit.
     * </pre>
     *
     * <code>string phone_hash = 5 [json_name = "phoneHash"];</code>
     * @param value The phoneHash to set.
     */
    private void setPhoneHash(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      phoneHash_ = value;
    }
    /**
     * <pre>
     * PII fields are NOT carried on the wire — only their hashes for
     * matching/dedup. Mobile SDKs encrypt locally before transit.
     * </pre>
     *
     * <code>string phone_hash = 5 [json_name = "phoneHash"];</code>
     */
    private void clearPhoneHash() {

      phoneHash_ = getDefaultInstance().getPhoneHash();
    }
    /**
     * <pre>
     * PII fields are NOT carried on the wire — only their hashes for
     * matching/dedup. Mobile SDKs encrypt locally before transit.
     * </pre>
     *
     * <code>string phone_hash = 5 [json_name = "phoneHash"];</code>
     * @param value The bytes for phoneHash to set.
     */
    private void setPhoneHashBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      phoneHash_ = value.toStringUtf8();

    }

    public static final int EMAIL_HASH_FIELD_NUMBER = 6;
    private java.lang.String emailHash_;
    /**
     * <code>string email_hash = 6 [json_name = "emailHash"];</code>
     * @return The emailHash.
     */
    @java.lang.Override
    public java.lang.String getEmailHash() {
      return emailHash_;
    }
    /**
     * <code>string email_hash = 6 [json_name = "emailHash"];</code>
     * @return The bytes for emailHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailHashBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(emailHash_);
    }
    /**
     * <code>string email_hash = 6 [json_name = "emailHash"];</code>
     * @param value The emailHash to set.
     */
    private void setEmailHash(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      emailHash_ = value;
    }
    /**
     * <code>string email_hash = 6 [json_name = "emailHash"];</code>
     */
    private void clearEmailHash() {

      emailHash_ = getDefaultInstance().getEmailHash();
    }
    /**
     * <code>string email_hash = 6 [json_name = "emailHash"];</code>
     * @param value The bytes for emailHash to set.
     */
    private void setEmailHashBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      emailHash_ = value.toStringUtf8();

    }

    public static final int IDENTITY_SOURCE_FIELD_NUMBER = 7;
    private java.lang.String identitySource_;
    /**
     * <pre>
     * APP_USER_ID | PHONE | EMAIL | GENERATED
     * </pre>
     *
     * <code>string identity_source = 7 [json_name = "identitySource"];</code>
     * @return The identitySource.
     */
    @java.lang.Override
    public java.lang.String getIdentitySource() {
      return identitySource_;
    }
    /**
     * <pre>
     * APP_USER_ID | PHONE | EMAIL | GENERATED
     * </pre>
     *
     * <code>string identity_source = 7 [json_name = "identitySource"];</code>
     * @return The bytes for identitySource.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdentitySourceBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(identitySource_);
    }
    /**
     * <pre>
     * APP_USER_ID | PHONE | EMAIL | GENERATED
     * </pre>
     *
     * <code>string identity_source = 7 [json_name = "identitySource"];</code>
     * @param value The identitySource to set.
     */
    private void setIdentitySource(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      identitySource_ = value;
    }
    /**
     * <pre>
     * APP_USER_ID | PHONE | EMAIL | GENERATED
     * </pre>
     *
     * <code>string identity_source = 7 [json_name = "identitySource"];</code>
     */
    private void clearIdentitySource() {

      identitySource_ = getDefaultInstance().getIdentitySource();
    }
    /**
     * <pre>
     * APP_USER_ID | PHONE | EMAIL | GENERATED
     * </pre>
     *
     * <code>string identity_source = 7 [json_name = "identitySource"];</code>
     * @param value The bytes for identitySource to set.
     */
    private void setIdentitySourceBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      identitySource_ = value.toStringUtf8();

    }

    public static addressiq.v1.Common.AppUser parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static addressiq.v1.Common.AppUser parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static addressiq.v1.Common.AppUser parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static addressiq.v1.Common.AppUser parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static addressiq.v1.Common.AppUser parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static addressiq.v1.Common.AppUser parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static addressiq.v1.Common.AppUser parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static addressiq.v1.Common.AppUser parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static addressiq.v1.Common.AppUser parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static addressiq.v1.Common.AppUser parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static addressiq.v1.Common.AppUser parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static addressiq.v1.Common.AppUser parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(addressiq.v1.Common.AppUser prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code addressiq.v1.AppUser}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          addressiq.v1.Common.AppUser, Builder> implements
        // @@protoc_insertion_point(builder_implements:addressiq.v1.AppUser)
        addressiq.v1.Common.AppUserOrBuilder {
      // Construct using addressiq.v1.Common.AppUser.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string id = 1 [json_name = "id"];</code>
       * @return The id.
       */
      @java.lang.Override
      public java.lang.String getId() {
        return instance.getId();
      }
      /**
       * <code>string id = 1 [json_name = "id"];</code>
       * @return The bytes for id.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getIdBytes() {
        return instance.getIdBytes();
      }
      /**
       * <code>string id = 1 [json_name = "id"];</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        copyOnWrite();
        instance.setId(value);
        return this;
      }
      /**
       * <code>string id = 1 [json_name = "id"];</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        copyOnWrite();
        instance.clearId();
        return this;
      }
      /**
       * <code>string id = 1 [json_name = "id"];</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setIdBytes(value);
        return this;
      }

      /**
       * <code>string organization_id = 2 [json_name = "organizationId"];</code>
       * @return The organizationId.
       */
      @java.lang.Override
      public java.lang.String getOrganizationId() {
        return instance.getOrganizationId();
      }
      /**
       * <code>string organization_id = 2 [json_name = "organizationId"];</code>
       * @return The bytes for organizationId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getOrganizationIdBytes() {
        return instance.getOrganizationIdBytes();
      }
      /**
       * <code>string organization_id = 2 [json_name = "organizationId"];</code>
       * @param value The organizationId to set.
       * @return This builder for chaining.
       */
      public Builder setOrganizationId(
          java.lang.String value) {
        copyOnWrite();
        instance.setOrganizationId(value);
        return this;
      }
      /**
       * <code>string organization_id = 2 [json_name = "organizationId"];</code>
       * @return This builder for chaining.
       */
      public Builder clearOrganizationId() {
        copyOnWrite();
        instance.clearOrganizationId();
        return this;
      }
      /**
       * <code>string organization_id = 2 [json_name = "organizationId"];</code>
       * @param value The bytes for organizationId to set.
       * @return This builder for chaining.
       */
      public Builder setOrganizationIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setOrganizationIdBytes(value);
        return this;
      }

      /**
       * <code>string app_id = 3 [json_name = "appId"];</code>
       * @return The appId.
       */
      @java.lang.Override
      public java.lang.String getAppId() {
        return instance.getAppId();
      }
      /**
       * <code>string app_id = 3 [json_name = "appId"];</code>
       * @return The bytes for appId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getAppIdBytes() {
        return instance.getAppIdBytes();
      }
      /**
       * <code>string app_id = 3 [json_name = "appId"];</code>
       * @param value The appId to set.
       * @return This builder for chaining.
       */
      public Builder setAppId(
          java.lang.String value) {
        copyOnWrite();
        instance.setAppId(value);
        return this;
      }
      /**
       * <code>string app_id = 3 [json_name = "appId"];</code>
       * @return This builder for chaining.
       */
      public Builder clearAppId() {
        copyOnWrite();
        instance.clearAppId();
        return this;
      }
      /**
       * <code>string app_id = 3 [json_name = "appId"];</code>
       * @param value The bytes for appId to set.
       * @return This builder for chaining.
       */
      public Builder setAppIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAppIdBytes(value);
        return this;
      }

      /**
       * <code>string app_user_id = 4 [json_name = "appUserId"];</code>
       * @return The appUserId.
       */
      @java.lang.Override
      public java.lang.String getAppUserId() {
        return instance.getAppUserId();
      }
      /**
       * <code>string app_user_id = 4 [json_name = "appUserId"];</code>
       * @return The bytes for appUserId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getAppUserIdBytes() {
        return instance.getAppUserIdBytes();
      }
      /**
       * <code>string app_user_id = 4 [json_name = "appUserId"];</code>
       * @param value The appUserId to set.
       * @return This builder for chaining.
       */
      public Builder setAppUserId(
          java.lang.String value) {
        copyOnWrite();
        instance.setAppUserId(value);
        return this;
      }
      /**
       * <code>string app_user_id = 4 [json_name = "appUserId"];</code>
       * @return This builder for chaining.
       */
      public Builder clearAppUserId() {
        copyOnWrite();
        instance.clearAppUserId();
        return this;
      }
      /**
       * <code>string app_user_id = 4 [json_name = "appUserId"];</code>
       * @param value The bytes for appUserId to set.
       * @return This builder for chaining.
       */
      public Builder setAppUserIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAppUserIdBytes(value);
        return this;
      }

      /**
       * <pre>
       * PII fields are NOT carried on the wire — only their hashes for
       * matching/dedup. Mobile SDKs encrypt locally before transit.
       * </pre>
       *
       * <code>string phone_hash = 5 [json_name = "phoneHash"];</code>
       * @return The phoneHash.
       */
      @java.lang.Override
      public java.lang.String getPhoneHash() {
        return instance.getPhoneHash();
      }
      /**
       * <pre>
       * PII fields are NOT carried on the wire — only their hashes for
       * matching/dedup. Mobile SDKs encrypt locally before transit.
       * </pre>
       *
       * <code>string phone_hash = 5 [json_name = "phoneHash"];</code>
       * @return The bytes for phoneHash.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getPhoneHashBytes() {
        return instance.getPhoneHashBytes();
      }
      /**
       * <pre>
       * PII fields are NOT carried on the wire — only their hashes for
       * matching/dedup. Mobile SDKs encrypt locally before transit.
       * </pre>
       *
       * <code>string phone_hash = 5 [json_name = "phoneHash"];</code>
       * @param value The phoneHash to set.
       * @return This builder for chaining.
       */
      public Builder setPhoneHash(
          java.lang.String value) {
        copyOnWrite();
        instance.setPhoneHash(value);
        return this;
      }
      /**
       * <pre>
       * PII fields are NOT carried on the wire — only their hashes for
       * matching/dedup. Mobile SDKs encrypt locally before transit.
       * </pre>
       *
       * <code>string phone_hash = 5 [json_name = "phoneHash"];</code>
       * @return This builder for chaining.
       */
      public Builder clearPhoneHash() {
        copyOnWrite();
        instance.clearPhoneHash();
        return this;
      }
      /**
       * <pre>
       * PII fields are NOT carried on the wire — only their hashes for
       * matching/dedup. Mobile SDKs encrypt locally before transit.
       * </pre>
       *
       * <code>string phone_hash = 5 [json_name = "phoneHash"];</code>
       * @param value The bytes for phoneHash to set.
       * @return This builder for chaining.
       */
      public Builder setPhoneHashBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPhoneHashBytes(value);
        return this;
      }

      /**
       * <code>string email_hash = 6 [json_name = "emailHash"];</code>
       * @return The emailHash.
       */
      @java.lang.Override
      public java.lang.String getEmailHash() {
        return instance.getEmailHash();
      }
      /**
       * <code>string email_hash = 6 [json_name = "emailHash"];</code>
       * @return The bytes for emailHash.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getEmailHashBytes() {
        return instance.getEmailHashBytes();
      }
      /**
       * <code>string email_hash = 6 [json_name = "emailHash"];</code>
       * @param value The emailHash to set.
       * @return This builder for chaining.
       */
      public Builder setEmailHash(
          java.lang.String value) {
        copyOnWrite();
        instance.setEmailHash(value);
        return this;
      }
      /**
       * <code>string email_hash = 6 [json_name = "emailHash"];</code>
       * @return This builder for chaining.
       */
      public Builder clearEmailHash() {
        copyOnWrite();
        instance.clearEmailHash();
        return this;
      }
      /**
       * <code>string email_hash = 6 [json_name = "emailHash"];</code>
       * @param value The bytes for emailHash to set.
       * @return This builder for chaining.
       */
      public Builder setEmailHashBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEmailHashBytes(value);
        return this;
      }

      /**
       * <pre>
       * APP_USER_ID | PHONE | EMAIL | GENERATED
       * </pre>
       *
       * <code>string identity_source = 7 [json_name = "identitySource"];</code>
       * @return The identitySource.
       */
      @java.lang.Override
      public java.lang.String getIdentitySource() {
        return instance.getIdentitySource();
      }
      /**
       * <pre>
       * APP_USER_ID | PHONE | EMAIL | GENERATED
       * </pre>
       *
       * <code>string identity_source = 7 [json_name = "identitySource"];</code>
       * @return The bytes for identitySource.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getIdentitySourceBytes() {
        return instance.getIdentitySourceBytes();
      }
      /**
       * <pre>
       * APP_USER_ID | PHONE | EMAIL | GENERATED
       * </pre>
       *
       * <code>string identity_source = 7 [json_name = "identitySource"];</code>
       * @param value The identitySource to set.
       * @return This builder for chaining.
       */
      public Builder setIdentitySource(
          java.lang.String value) {
        copyOnWrite();
        instance.setIdentitySource(value);
        return this;
      }
      /**
       * <pre>
       * APP_USER_ID | PHONE | EMAIL | GENERATED
       * </pre>
       *
       * <code>string identity_source = 7 [json_name = "identitySource"];</code>
       * @return This builder for chaining.
       */
      public Builder clearIdentitySource() {
        copyOnWrite();
        instance.clearIdentitySource();
        return this;
      }
      /**
       * <pre>
       * APP_USER_ID | PHONE | EMAIL | GENERATED
       * </pre>
       *
       * <code>string identity_source = 7 [json_name = "identitySource"];</code>
       * @param value The bytes for identitySource to set.
       * @return This builder for chaining.
       */
      public Builder setIdentitySourceBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setIdentitySourceBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:addressiq.v1.AppUser)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new addressiq.v1.Common.AppUser();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "id_",
              "organizationId_",
              "appId_",
              "appUserId_",
              "phoneHash_",
              "emailHash_",
              "identitySource_",
            };
            java.lang.String info =
                "\u0000\u0007\u0000\u0000\u0001\u0007\u0007\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
                "\u0003\u0208\u0004\u0208\u0005\u0208\u0006\u0208\u0007\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<addressiq.v1.Common.AppUser> parser = PARSER;
          if (parser == null) {
            synchronized (addressiq.v1.Common.AppUser.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<addressiq.v1.Common.AppUser>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:addressiq.v1.AppUser)
    private static final addressiq.v1.Common.AppUser DEFAULT_INSTANCE;
    static {
      AppUser defaultInstance = new AppUser();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        AppUser.class, defaultInstance);
    }

    public static addressiq.v1.Common.AppUser getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<AppUser> PARSER;

    public static com.google.protobuf.Parser<AppUser> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface GeoPointOrBuilder extends
      // @@protoc_insertion_point(interface_extends:addressiq.v1.GeoPoint)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>double lat = 1 [json_name = "lat"];</code>
     * @return The lat.
     */
    double getLat();

    /**
     * <code>double lon = 2 [json_name = "lon"];</code>
     * @return The lon.
     */
    double getLon();
  }
  /**
   * Protobuf type {@code addressiq.v1.GeoPoint}
   */
  public  static final class GeoPoint extends
      com.google.protobuf.GeneratedMessageLite<
          GeoPoint, GeoPoint.Builder> implements
      // @@protoc_insertion_point(message_implements:addressiq.v1.GeoPoint)
      GeoPointOrBuilder {
    private GeoPoint() {
    }
    public static final int LAT_FIELD_NUMBER = 1;
    private double lat_;
    /**
     * <code>double lat = 1 [json_name = "lat"];</code>
     * @return The lat.
     */
    @java.lang.Override
    public double getLat() {
      return lat_;
    }
    /**
     * <code>double lat = 1 [json_name = "lat"];</code>
     * @param value The lat to set.
     */
    private void setLat(double value) {
      
      lat_ = value;
    }
    /**
     * <code>double lat = 1 [json_name = "lat"];</code>
     */
    private void clearLat() {

      lat_ = 0D;
    }

    public static final int LON_FIELD_NUMBER = 2;
    private double lon_;
    /**
     * <code>double lon = 2 [json_name = "lon"];</code>
     * @return The lon.
     */
    @java.lang.Override
    public double getLon() {
      return lon_;
    }
    /**
     * <code>double lon = 2 [json_name = "lon"];</code>
     * @param value The lon to set.
     */
    private void setLon(double value) {
      
      lon_ = value;
    }
    /**
     * <code>double lon = 2 [json_name = "lon"];</code>
     */
    private void clearLon() {

      lon_ = 0D;
    }

    public static addressiq.v1.Common.GeoPoint parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static addressiq.v1.Common.GeoPoint parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static addressiq.v1.Common.GeoPoint parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static addressiq.v1.Common.GeoPoint parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static addressiq.v1.Common.GeoPoint parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static addressiq.v1.Common.GeoPoint parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static addressiq.v1.Common.GeoPoint parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static addressiq.v1.Common.GeoPoint parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static addressiq.v1.Common.GeoPoint parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static addressiq.v1.Common.GeoPoint parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static addressiq.v1.Common.GeoPoint parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static addressiq.v1.Common.GeoPoint parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(addressiq.v1.Common.GeoPoint prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code addressiq.v1.GeoPoint}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          addressiq.v1.Common.GeoPoint, Builder> implements
        // @@protoc_insertion_point(builder_implements:addressiq.v1.GeoPoint)
        addressiq.v1.Common.GeoPointOrBuilder {
      // Construct using addressiq.v1.Common.GeoPoint.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>double lat = 1 [json_name = "lat"];</code>
       * @return The lat.
       */
      @java.lang.Override
      public double getLat() {
        return instance.getLat();
      }
      /**
       * <code>double lat = 1 [json_name = "lat"];</code>
       * @param value The lat to set.
       * @return This builder for chaining.
       */
      public Builder setLat(double value) {
        copyOnWrite();
        instance.setLat(value);
        return this;
      }
      /**
       * <code>double lat = 1 [json_name = "lat"];</code>
       * @return This builder for chaining.
       */
      public Builder clearLat() {
        copyOnWrite();
        instance.clearLat();
        return this;
      }

      /**
       * <code>double lon = 2 [json_name = "lon"];</code>
       * @return The lon.
       */
      @java.lang.Override
      public double getLon() {
        return instance.getLon();
      }
      /**
       * <code>double lon = 2 [json_name = "lon"];</code>
       * @param value The lon to set.
       * @return This builder for chaining.
       */
      public Builder setLon(double value) {
        copyOnWrite();
        instance.setLon(value);
        return this;
      }
      /**
       * <code>double lon = 2 [json_name = "lon"];</code>
       * @return This builder for chaining.
       */
      public Builder clearLon() {
        copyOnWrite();
        instance.clearLon();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:addressiq.v1.GeoPoint)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new addressiq.v1.Common.GeoPoint();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "lat_",
              "lon_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0000\u0002\u0000" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<addressiq.v1.Common.GeoPoint> parser = PARSER;
          if (parser == null) {
            synchronized (addressiq.v1.Common.GeoPoint.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<addressiq.v1.Common.GeoPoint>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:addressiq.v1.GeoPoint)
    private static final addressiq.v1.Common.GeoPoint DEFAULT_INSTANCE;
    static {
      GeoPoint defaultInstance = new GeoPoint();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        GeoPoint.class, defaultInstance);
    }

    public static addressiq.v1.Common.GeoPoint getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<GeoPoint> PARSER;

    public static com.google.protobuf.Parser<GeoPoint> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface SdkErrorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:addressiq.v1.SdkError)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.addressiq.v1.ErrorCode code = 1 [json_name = "code"];</code>
     * @return The enum numeric value on the wire for code.
     */
    int getCodeValue();
    /**
     * <code>.addressiq.v1.ErrorCode code = 1 [json_name = "code"];</code>
     * @return The code.
     */
    addressiq.v1.Common.ErrorCode getCode();

    /**
     * <code>string message = 2 [json_name = "message"];</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 2 [json_name = "message"];</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>string docs_url = 3 [json_name = "docsUrl"];</code>
     * @return The docsUrl.
     */
    java.lang.String getDocsUrl();
    /**
     * <code>string docs_url = 3 [json_name = "docsUrl"];</code>
     * @return The bytes for docsUrl.
     */
    com.google.protobuf.ByteString
        getDocsUrlBytes();
  }
  /**
   * Protobuf type {@code addressiq.v1.SdkError}
   */
  public  static final class SdkError extends
      com.google.protobuf.GeneratedMessageLite<
          SdkError, SdkError.Builder> implements
      // @@protoc_insertion_point(message_implements:addressiq.v1.SdkError)
      SdkErrorOrBuilder {
    private SdkError() {
      message_ = "";
      docsUrl_ = "";
    }
    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>.addressiq.v1.ErrorCode code = 1 [json_name = "code"];</code>
     * @return The enum numeric value on the wire for code.
     */
    @java.lang.Override
    public int getCodeValue() {
      return code_;
    }
    /**
     * <code>.addressiq.v1.ErrorCode code = 1 [json_name = "code"];</code>
     * @return The code.
     */
    @java.lang.Override
    public addressiq.v1.Common.ErrorCode getCode() {
      addressiq.v1.Common.ErrorCode result = addressiq.v1.Common.ErrorCode.forNumber(code_);
      return result == null ? addressiq.v1.Common.ErrorCode.UNRECOGNIZED : result;
    }
    /**
     * <code>.addressiq.v1.ErrorCode code = 1 [json_name = "code"];</code>
     * @param value The enum numeric value on the wire for code to set.
     */
    private void setCodeValue(int value) {
        code_ = value;
    }
    /**
     * <code>.addressiq.v1.ErrorCode code = 1 [json_name = "code"];</code>
     * @param value The code to set.
     */
    private void setCode(addressiq.v1.Common.ErrorCode value) {
      code_ = value.getNumber();

    }
    /**
     * <code>.addressiq.v1.ErrorCode code = 1 [json_name = "code"];</code>
     */
    private void clearCode() {

      code_ = 0;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private java.lang.String message_;
    /**
     * <code>string message = 2 [json_name = "message"];</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      return message_;
    }
    /**
     * <code>string message = 2 [json_name = "message"];</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(message_);
    }
    /**
     * <code>string message = 2 [json_name = "message"];</code>
     * @param value The message to set.
     */
    private void setMessage(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      message_ = value;
    }
    /**
     * <code>string message = 2 [json_name = "message"];</code>
     */
    private void clearMessage() {

      message_ = getDefaultInstance().getMessage();
    }
    /**
     * <code>string message = 2 [json_name = "message"];</code>
     * @param value The bytes for message to set.
     */
    private void setMessageBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      message_ = value.toStringUtf8();

    }

    public static final int DOCS_URL_FIELD_NUMBER = 3;
    private java.lang.String docsUrl_;
    /**
     * <code>string docs_url = 3 [json_name = "docsUrl"];</code>
     * @return The docsUrl.
     */
    @java.lang.Override
    public java.lang.String getDocsUrl() {
      return docsUrl_;
    }
    /**
     * <code>string docs_url = 3 [json_name = "docsUrl"];</code>
     * @return The bytes for docsUrl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDocsUrlBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(docsUrl_);
    }
    /**
     * <code>string docs_url = 3 [json_name = "docsUrl"];</code>
     * @param value The docsUrl to set.
     */
    private void setDocsUrl(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      docsUrl_ = value;
    }
    /**
     * <code>string docs_url = 3 [json_name = "docsUrl"];</code>
     */
    private void clearDocsUrl() {

      docsUrl_ = getDefaultInstance().getDocsUrl();
    }
    /**
     * <code>string docs_url = 3 [json_name = "docsUrl"];</code>
     * @param value The bytes for docsUrl to set.
     */
    private void setDocsUrlBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      docsUrl_ = value.toStringUtf8();

    }

    public static addressiq.v1.Common.SdkError parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static addressiq.v1.Common.SdkError parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static addressiq.v1.Common.SdkError parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static addressiq.v1.Common.SdkError parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static addressiq.v1.Common.SdkError parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static addressiq.v1.Common.SdkError parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static addressiq.v1.Common.SdkError parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static addressiq.v1.Common.SdkError parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static addressiq.v1.Common.SdkError parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static addressiq.v1.Common.SdkError parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static addressiq.v1.Common.SdkError parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static addressiq.v1.Common.SdkError parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(addressiq.v1.Common.SdkError prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code addressiq.v1.SdkError}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          addressiq.v1.Common.SdkError, Builder> implements
        // @@protoc_insertion_point(builder_implements:addressiq.v1.SdkError)
        addressiq.v1.Common.SdkErrorOrBuilder {
      // Construct using addressiq.v1.Common.SdkError.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.addressiq.v1.ErrorCode code = 1 [json_name = "code"];</code>
       * @return The enum numeric value on the wire for code.
       */
      @java.lang.Override
      public int getCodeValue() {
        return instance.getCodeValue();
      }
      /**
       * <code>.addressiq.v1.ErrorCode code = 1 [json_name = "code"];</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCodeValue(int value) {
        copyOnWrite();
        instance.setCodeValue(value);
        return this;
      }
      /**
       * <code>.addressiq.v1.ErrorCode code = 1 [json_name = "code"];</code>
       * @return The code.
       */
      @java.lang.Override
      public addressiq.v1.Common.ErrorCode getCode() {
        return instance.getCode();
      }
      /**
       * <code>.addressiq.v1.ErrorCode code = 1 [json_name = "code"];</code>
       * @param value The enum numeric value on the wire for code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(addressiq.v1.Common.ErrorCode value) {
        copyOnWrite();
        instance.setCode(value);
        return this;
      }
      /**
       * <code>.addressiq.v1.ErrorCode code = 1 [json_name = "code"];</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        copyOnWrite();
        instance.clearCode();
        return this;
      }

      /**
       * <code>string message = 2 [json_name = "message"];</code>
       * @return The message.
       */
      @java.lang.Override
      public java.lang.String getMessage() {
        return instance.getMessage();
      }
      /**
       * <code>string message = 2 [json_name = "message"];</code>
       * @return The bytes for message.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getMessageBytes() {
        return instance.getMessageBytes();
      }
      /**
       * <code>string message = 2 [json_name = "message"];</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        copyOnWrite();
        instance.setMessage(value);
        return this;
      }
      /**
       * <code>string message = 2 [json_name = "message"];</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        copyOnWrite();
        instance.clearMessage();
        return this;
      }
      /**
       * <code>string message = 2 [json_name = "message"];</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMessageBytes(value);
        return this;
      }

      /**
       * <code>string docs_url = 3 [json_name = "docsUrl"];</code>
       * @return The docsUrl.
       */
      @java.lang.Override
      public java.lang.String getDocsUrl() {
        return instance.getDocsUrl();
      }
      /**
       * <code>string docs_url = 3 [json_name = "docsUrl"];</code>
       * @return The bytes for docsUrl.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getDocsUrlBytes() {
        return instance.getDocsUrlBytes();
      }
      /**
       * <code>string docs_url = 3 [json_name = "docsUrl"];</code>
       * @param value The docsUrl to set.
       * @return This builder for chaining.
       */
      public Builder setDocsUrl(
          java.lang.String value) {
        copyOnWrite();
        instance.setDocsUrl(value);
        return this;
      }
      /**
       * <code>string docs_url = 3 [json_name = "docsUrl"];</code>
       * @return This builder for chaining.
       */
      public Builder clearDocsUrl() {
        copyOnWrite();
        instance.clearDocsUrl();
        return this;
      }
      /**
       * <code>string docs_url = 3 [json_name = "docsUrl"];</code>
       * @param value The bytes for docsUrl to set.
       * @return This builder for chaining.
       */
      public Builder setDocsUrlBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDocsUrlBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:addressiq.v1.SdkError)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new addressiq.v1.Common.SdkError();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "code_",
              "message_",
              "docsUrl_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\f\u0002\u0208" +
                "\u0003\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<addressiq.v1.Common.SdkError> parser = PARSER;
          if (parser == null) {
            synchronized (addressiq.v1.Common.SdkError.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<addressiq.v1.Common.SdkError>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:addressiq.v1.SdkError)
    private static final addressiq.v1.Common.SdkError DEFAULT_INSTANCE;
    static {
      SdkError defaultInstance = new SdkError();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        SdkError.class, defaultInstance);
    }

    public static addressiq.v1.Common.SdkError getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SdkError> PARSER;

    public static com.google.protobuf.Parser<SdkError> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
