// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressiq/v1/sdk.proto

// Protobuf Java Version: 3.25.3
package addressiq.v1;

public final class Sdk {
  private Sdk() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code addressiq.v1.LifecycleState}
   */
  public enum LifecycleState
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>LIFECYCLE_STATE_UNSPECIFIED = 0;</code>
     */
    LIFECYCLE_STATE_UNSPECIFIED(0),
    /**
     * <code>UNINITIALIZED = 1;</code>
     */
    UNINITIALIZED(1),
    /**
     * <code>IDLE = 2;</code>
     */
    IDLE(2),
    /**
     * <code>COLLECTING = 3;</code>
     */
    COLLECTING(3),
    /**
     * <code>PAUSED = 4;</code>
     */
    PAUSED(4),
    /**
     * <code>TERMINATED = 5;</code>
     */
    TERMINATED(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>LIFECYCLE_STATE_UNSPECIFIED = 0;</code>
     */
    public static final int LIFECYCLE_STATE_UNSPECIFIED_VALUE = 0;
    /**
     * <code>UNINITIALIZED = 1;</code>
     */
    public static final int UNINITIALIZED_VALUE = 1;
    /**
     * <code>IDLE = 2;</code>
     */
    public static final int IDLE_VALUE = 2;
    /**
     * <code>COLLECTING = 3;</code>
     */
    public static final int COLLECTING_VALUE = 3;
    /**
     * <code>PAUSED = 4;</code>
     */
    public static final int PAUSED_VALUE = 4;
    /**
     * <code>TERMINATED = 5;</code>
     */
    public static final int TERMINATED_VALUE = 5;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static LifecycleState valueOf(int value) {
      return forNumber(value);
    }

    public static LifecycleState forNumber(int value) {
      switch (value) {
        case 0: return LIFECYCLE_STATE_UNSPECIFIED;
        case 1: return UNINITIALIZED;
        case 2: return IDLE;
        case 3: return COLLECTING;
        case 4: return PAUSED;
        case 5: return TERMINATED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<LifecycleState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        LifecycleState> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<LifecycleState>() {
            @java.lang.Override
            public LifecycleState findValueByNumber(int number) {
              return LifecycleState.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return LifecycleStateVerifier.INSTANCE;
    }

    private static final class LifecycleStateVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new LifecycleStateVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return LifecycleState.forNumber(number) != null;
            }
          };

    private final int value;

    private LifecycleState(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:addressiq.v1.LifecycleState)
  }

  /**
   * Protobuf enum {@code addressiq.v1.PermissionStatus}
   */
  public enum PermissionStatus
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>PERMISSION_STATUS_UNSPECIFIED = 0;</code>
     */
    PERMISSION_STATUS_UNSPECIFIED(0),
    /**
     * <code>GRANTED = 1;</code>
     */
    GRANTED(1),
    /**
     * <code>DENIED = 2;</code>
     */
    DENIED(2),
    /**
     * <code>NOT_DETERMINED = 3;</code>
     */
    NOT_DETERMINED(3),
    /**
     * <code>BLOCKED = 4;</code>
     */
    BLOCKED(4),
    /**
     * <code>PERMISSION_UNAVAILABLE = 5;</code>
     */
    PERMISSION_UNAVAILABLE(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>PERMISSION_STATUS_UNSPECIFIED = 0;</code>
     */
    public static final int PERMISSION_STATUS_UNSPECIFIED_VALUE = 0;
    /**
     * <code>GRANTED = 1;</code>
     */
    public static final int GRANTED_VALUE = 1;
    /**
     * <code>DENIED = 2;</code>
     */
    public static final int DENIED_VALUE = 2;
    /**
     * <code>NOT_DETERMINED = 3;</code>
     */
    public static final int NOT_DETERMINED_VALUE = 3;
    /**
     * <code>BLOCKED = 4;</code>
     */
    public static final int BLOCKED_VALUE = 4;
    /**
     * <code>PERMISSION_UNAVAILABLE = 5;</code>
     */
    public static final int PERMISSION_UNAVAILABLE_VALUE = 5;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PermissionStatus valueOf(int value) {
      return forNumber(value);
    }

    public static PermissionStatus forNumber(int value) {
      switch (value) {
        case 0: return PERMISSION_STATUS_UNSPECIFIED;
        case 1: return GRANTED;
        case 2: return DENIED;
        case 3: return NOT_DETERMINED;
        case 4: return BLOCKED;
        case 5: return PERMISSION_UNAVAILABLE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PermissionStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PermissionStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PermissionStatus>() {
            @java.lang.Override
            public PermissionStatus findValueByNumber(int number) {
              return PermissionStatus.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return PermissionStatusVerifier.INSTANCE;
    }

    private static final class PermissionStatusVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new PermissionStatusVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return PermissionStatus.forNumber(number) != null;
            }
          };

    private final int value;

    private PermissionStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:addressiq.v1.PermissionStatus)
  }

  public interface SdkUserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:addressiq.v1.SdkUser)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string app_user_id = 1 [json_name = "appUserId"];</code>
     * @return The appUserId.
     */
    java.lang.String getAppUserId();
    /**
     * <code>string app_user_id = 1 [json_name = "appUserId"];</code>
     * @return The bytes for appUserId.
     */
    com.google.protobuf.ByteString
        getAppUserIdBytes();

    /**
     * <pre>
     * encrypted at rest on device — wire = plaintext under HTTPS
     * </pre>
     *
     * <code>string phone = 2 [json_name = "phone"];</code>
     * @return The phone.
     */
    java.lang.String getPhone();
    /**
     * <pre>
     * encrypted at rest on device — wire = plaintext under HTTPS
     * </pre>
     *
     * <code>string phone = 2 [json_name = "phone"];</code>
     * @return The bytes for phone.
     */
    com.google.protobuf.ByteString
        getPhoneBytes();

    /**
     * <code>string email = 3 [json_name = "email"];</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 3 [json_name = "email"];</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>string first_name = 4 [json_name = "firstName"];</code>
     * @return The firstName.
     */
    java.lang.String getFirstName();
    /**
     * <code>string first_name = 4 [json_name = "firstName"];</code>
     * @return The bytes for firstName.
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    /**
     * <code>string last_name = 5 [json_name = "lastName"];</code>
     * @return The lastName.
     */
    java.lang.String getLastName();
    /**
     * <code>string last_name = 5 [json_name = "lastName"];</code>
     * @return The bytes for lastName.
     */
    com.google.protobuf.ByteString
        getLastNameBytes();
  }
  /**
   * Protobuf type {@code addressiq.v1.SdkUser}
   */
  public  static final class SdkUser extends
      com.google.protobuf.GeneratedMessageLite<
          SdkUser, SdkUser.Builder> implements
      // @@protoc_insertion_point(message_implements:addressiq.v1.SdkUser)
      SdkUserOrBuilder {
    private SdkUser() {
      appUserId_ = "";
      phone_ = "";
      email_ = "";
      firstName_ = "";
      lastName_ = "";
    }
    public static final int APP_USER_ID_FIELD_NUMBER = 1;
    private java.lang.String appUserId_;
    /**
     * <code>string app_user_id = 1 [json_name = "appUserId"];</code>
     * @return The appUserId.
     */
    @java.lang.Override
    public java.lang.String getAppUserId() {
      return appUserId_;
    }
    /**
     * <code>string app_user_id = 1 [json_name = "appUserId"];</code>
     * @return The bytes for appUserId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAppUserIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(appUserId_);
    }
    /**
     * <code>string app_user_id = 1 [json_name = "appUserId"];</code>
     * @param value The appUserId to set.
     */
    private void setAppUserId(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      appUserId_ = value;
    }
    /**
     * <code>string app_user_id = 1 [json_name = "appUserId"];</code>
     */
    private void clearAppUserId() {

      appUserId_ = getDefaultInstance().getAppUserId();
    }
    /**
     * <code>string app_user_id = 1 [json_name = "appUserId"];</code>
     * @param value The bytes for appUserId to set.
     */
    private void setAppUserIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      appUserId_ = value.toStringUtf8();

    }

    public static final int PHONE_FIELD_NUMBER = 2;
    private java.lang.String phone_;
    /**
     * <pre>
     * encrypted at rest on device — wire = plaintext under HTTPS
     * </pre>
     *
     * <code>string phone = 2 [json_name = "phone"];</code>
     * @return The phone.
     */
    @java.lang.Override
    public java.lang.String getPhone() {
      return phone_;
    }
    /**
     * <pre>
     * encrypted at rest on device — wire = plaintext under HTTPS
     * </pre>
     *
     * <code>string phone = 2 [json_name = "phone"];</code>
     * @return The bytes for phone.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPhoneBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(phone_);
    }
    /**
     * <pre>
     * encrypted at rest on device — wire = plaintext under HTTPS
     * </pre>
     *
     * <code>string phone = 2 [json_name = "phone"];</code>
     * @param value The phone to set.
     */
    private void setPhone(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      phone_ = value;
    }
    /**
     * <pre>
     * encrypted at rest on device — wire = plaintext under HTTPS
     * </pre>
     *
     * <code>string phone = 2 [json_name = "phone"];</code>
     */
    private void clearPhone() {

      phone_ = getDefaultInstance().getPhone();
    }
    /**
     * <pre>
     * encrypted at rest on device — wire = plaintext under HTTPS
     * </pre>
     *
     * <code>string phone = 2 [json_name = "phone"];</code>
     * @param value The bytes for phone to set.
     */
    private void setPhoneBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      phone_ = value.toStringUtf8();

    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private java.lang.String email_;
    /**
     * <code>string email = 3 [json_name = "email"];</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      return email_;
    }
    /**
     * <code>string email = 3 [json_name = "email"];</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(email_);
    }
    /**
     * <code>string email = 3 [json_name = "email"];</code>
     * @param value The email to set.
     */
    private void setEmail(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      email_ = value;
    }
    /**
     * <code>string email = 3 [json_name = "email"];</code>
     */
    private void clearEmail() {

      email_ = getDefaultInstance().getEmail();
    }
    /**
     * <code>string email = 3 [json_name = "email"];</code>
     * @param value The bytes for email to set.
     */
    private void setEmailBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      email_ = value.toStringUtf8();

    }

    public static final int FIRST_NAME_FIELD_NUMBER = 4;
    private java.lang.String firstName_;
    /**
     * <code>string first_name = 4 [json_name = "firstName"];</code>
     * @return The firstName.
     */
    @java.lang.Override
    public java.lang.String getFirstName() {
      return firstName_;
    }
    /**
     * <code>string first_name = 4 [json_name = "firstName"];</code>
     * @return The bytes for firstName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(firstName_);
    }
    /**
     * <code>string first_name = 4 [json_name = "firstName"];</code>
     * @param value The firstName to set.
     */
    private void setFirstName(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      firstName_ = value;
    }
    /**
     * <code>string first_name = 4 [json_name = "firstName"];</code>
     */
    private void clearFirstName() {

      firstName_ = getDefaultInstance().getFirstName();
    }
    /**
     * <code>string first_name = 4 [json_name = "firstName"];</code>
     * @param value The bytes for firstName to set.
     */
    private void setFirstNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      firstName_ = value.toStringUtf8();

    }

    public static final int LAST_NAME_FIELD_NUMBER = 5;
    private java.lang.String lastName_;
    /**
     * <code>string last_name = 5 [json_name = "lastName"];</code>
     * @return The lastName.
     */
    @java.lang.Override
    public java.lang.String getLastName() {
      return lastName_;
    }
    /**
     * <code>string last_name = 5 [json_name = "lastName"];</code>
     * @return The bytes for lastName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(lastName_);
    }
    /**
     * <code>string last_name = 5 [json_name = "lastName"];</code>
     * @param value The lastName to set.
     */
    private void setLastName(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      lastName_ = value;
    }
    /**
     * <code>string last_name = 5 [json_name = "lastName"];</code>
     */
    private void clearLastName() {

      lastName_ = getDefaultInstance().getLastName();
    }
    /**
     * <code>string last_name = 5 [json_name = "lastName"];</code>
     * @param value The bytes for lastName to set.
     */
    private void setLastNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      lastName_ = value.toStringUtf8();

    }

    public static addressiq.v1.Sdk.SdkUser parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static addressiq.v1.Sdk.SdkUser parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static addressiq.v1.Sdk.SdkUser parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static addressiq.v1.Sdk.SdkUser parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static addressiq.v1.Sdk.SdkUser parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static addressiq.v1.Sdk.SdkUser parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static addressiq.v1.Sdk.SdkUser parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static addressiq.v1.Sdk.SdkUser parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static addressiq.v1.Sdk.SdkUser parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static addressiq.v1.Sdk.SdkUser parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static addressiq.v1.Sdk.SdkUser parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static addressiq.v1.Sdk.SdkUser parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(addressiq.v1.Sdk.SdkUser prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code addressiq.v1.SdkUser}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          addressiq.v1.Sdk.SdkUser, Builder> implements
        // @@protoc_insertion_point(builder_implements:addressiq.v1.SdkUser)
        addressiq.v1.Sdk.SdkUserOrBuilder {
      // Construct using addressiq.v1.Sdk.SdkUser.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string app_user_id = 1 [json_name = "appUserId"];</code>
       * @return The appUserId.
       */
      @java.lang.Override
      public java.lang.String getAppUserId() {
        return instance.getAppUserId();
      }
      /**
       * <code>string app_user_id = 1 [json_name = "appUserId"];</code>
       * @return The bytes for appUserId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getAppUserIdBytes() {
        return instance.getAppUserIdBytes();
      }
      /**
       * <code>string app_user_id = 1 [json_name = "appUserId"];</code>
       * @param value The appUserId to set.
       * @return This builder for chaining.
       */
      public Builder setAppUserId(
          java.lang.String value) {
        copyOnWrite();
        instance.setAppUserId(value);
        return this;
      }
      /**
       * <code>string app_user_id = 1 [json_name = "appUserId"];</code>
       * @return This builder for chaining.
       */
      public Builder clearAppUserId() {
        copyOnWrite();
        instance.clearAppUserId();
        return this;
      }
      /**
       * <code>string app_user_id = 1 [json_name = "appUserId"];</code>
       * @param value The bytes for appUserId to set.
       * @return This builder for chaining.
       */
      public Builder setAppUserIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAppUserIdBytes(value);
        return this;
      }

      /**
       * <pre>
       * encrypted at rest on device — wire = plaintext under HTTPS
       * </pre>
       *
       * <code>string phone = 2 [json_name = "phone"];</code>
       * @return The phone.
       */
      @java.lang.Override
      public java.lang.String getPhone() {
        return instance.getPhone();
      }
      /**
       * <pre>
       * encrypted at rest on device — wire = plaintext under HTTPS
       * </pre>
       *
       * <code>string phone = 2 [json_name = "phone"];</code>
       * @return The bytes for phone.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getPhoneBytes() {
        return instance.getPhoneBytes();
      }
      /**
       * <pre>
       * encrypted at rest on device — wire = plaintext under HTTPS
       * </pre>
       *
       * <code>string phone = 2 [json_name = "phone"];</code>
       * @param value The phone to set.
       * @return This builder for chaining.
       */
      public Builder setPhone(
          java.lang.String value) {
        copyOnWrite();
        instance.setPhone(value);
        return this;
      }
      /**
       * <pre>
       * encrypted at rest on device — wire = plaintext under HTTPS
       * </pre>
       *
       * <code>string phone = 2 [json_name = "phone"];</code>
       * @return This builder for chaining.
       */
      public Builder clearPhone() {
        copyOnWrite();
        instance.clearPhone();
        return this;
      }
      /**
       * <pre>
       * encrypted at rest on device — wire = plaintext under HTTPS
       * </pre>
       *
       * <code>string phone = 2 [json_name = "phone"];</code>
       * @param value The bytes for phone to set.
       * @return This builder for chaining.
       */
      public Builder setPhoneBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPhoneBytes(value);
        return this;
      }

      /**
       * <code>string email = 3 [json_name = "email"];</code>
       * @return The email.
       */
      @java.lang.Override
      public java.lang.String getEmail() {
        return instance.getEmail();
      }
      /**
       * <code>string email = 3 [json_name = "email"];</code>
       * @return The bytes for email.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getEmailBytes() {
        return instance.getEmailBytes();
      }
      /**
       * <code>string email = 3 [json_name = "email"];</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        copyOnWrite();
        instance.setEmail(value);
        return this;
      }
      /**
       * <code>string email = 3 [json_name = "email"];</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        copyOnWrite();
        instance.clearEmail();
        return this;
      }
      /**
       * <code>string email = 3 [json_name = "email"];</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEmailBytes(value);
        return this;
      }

      /**
       * <code>string first_name = 4 [json_name = "firstName"];</code>
       * @return The firstName.
       */
      @java.lang.Override
      public java.lang.String getFirstName() {
        return instance.getFirstName();
      }
      /**
       * <code>string first_name = 4 [json_name = "firstName"];</code>
       * @return The bytes for firstName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        return instance.getFirstNameBytes();
      }
      /**
       * <code>string first_name = 4 [json_name = "firstName"];</code>
       * @param value The firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstName(
          java.lang.String value) {
        copyOnWrite();
        instance.setFirstName(value);
        return this;
      }
      /**
       * <code>string first_name = 4 [json_name = "firstName"];</code>
       * @return This builder for chaining.
       */
      public Builder clearFirstName() {
        copyOnWrite();
        instance.clearFirstName();
        return this;
      }
      /**
       * <code>string first_name = 4 [json_name = "firstName"];</code>
       * @param value The bytes for firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setFirstNameBytes(value);
        return this;
      }

      /**
       * <code>string last_name = 5 [json_name = "lastName"];</code>
       * @return The lastName.
       */
      @java.lang.Override
      public java.lang.String getLastName() {
        return instance.getLastName();
      }
      /**
       * <code>string last_name = 5 [json_name = "lastName"];</code>
       * @return The bytes for lastName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        return instance.getLastNameBytes();
      }
      /**
       * <code>string last_name = 5 [json_name = "lastName"];</code>
       * @param value The lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastName(
          java.lang.String value) {
        copyOnWrite();
        instance.setLastName(value);
        return this;
      }
      /**
       * <code>string last_name = 5 [json_name = "lastName"];</code>
       * @return This builder for chaining.
       */
      public Builder clearLastName() {
        copyOnWrite();
        instance.clearLastName();
        return this;
      }
      /**
       * <code>string last_name = 5 [json_name = "lastName"];</code>
       * @param value The bytes for lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setLastNameBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:addressiq.v1.SdkUser)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new addressiq.v1.Sdk.SdkUser();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "appUserId_",
              "phone_",
              "email_",
              "firstName_",
              "lastName_",
            };
            java.lang.String info =
                "\u0000\u0005\u0000\u0000\u0001\u0005\u0005\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
                "\u0003\u0208\u0004\u0208\u0005\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<addressiq.v1.Sdk.SdkUser> parser = PARSER;
          if (parser == null) {
            synchronized (addressiq.v1.Sdk.SdkUser.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<addressiq.v1.Sdk.SdkUser>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:addressiq.v1.SdkUser)
    private static final addressiq.v1.Sdk.SdkUser DEFAULT_INSTANCE;
    static {
      SdkUser defaultInstance = new SdkUser();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        SdkUser.class, defaultInstance);
    }

    public static addressiq.v1.Sdk.SdkUser getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SdkUser> PARSER;

    public static com.google.protobuf.Parser<SdkUser> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface VerificationLifecycleStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:addressiq.v1.VerificationLifecycleState)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.addressiq.v1.LifecycleState state = 1 [json_name = "state"];</code>
     * @return The enum numeric value on the wire for state.
     */
    int getStateValue();
    /**
     * <code>.addressiq.v1.LifecycleState state = 1 [json_name = "state"];</code>
     * @return The state.
     */
    addressiq.v1.Sdk.LifecycleState getState();

    /**
     * <code>string app_user_id = 2 [json_name = "appUserId"];</code>
     * @return The appUserId.
     */
    java.lang.String getAppUserId();
    /**
     * <code>string app_user_id = 2 [json_name = "appUserId"];</code>
     * @return The bytes for appUserId.
     */
    com.google.protobuf.ByteString
        getAppUserIdBytes();

    /**
     * <code>string verification_id = 3 [json_name = "verificationId"];</code>
     * @return The verificationId.
     */
    java.lang.String getVerificationId();
    /**
     * <code>string verification_id = 3 [json_name = "verificationId"];</code>
     * @return The bytes for verificationId.
     */
    com.google.protobuf.ByteString
        getVerificationIdBytes();

    /**
     * <code>string location_code = 4 [json_name = "locationCode"];</code>
     * @return The locationCode.
     */
    java.lang.String getLocationCode();
    /**
     * <code>string location_code = 4 [json_name = "locationCode"];</code>
     * @return The bytes for locationCode.
     */
    com.google.protobuf.ByteString
        getLocationCodeBytes();

    /**
     * <code>int64 paused_for_ms = 5 [json_name = "pausedForMs"];</code>
     * @return The pausedForMs.
     */
    long getPausedForMs();
  }
  /**
   * Protobuf type {@code addressiq.v1.VerificationLifecycleState}
   */
  public  static final class VerificationLifecycleState extends
      com.google.protobuf.GeneratedMessageLite<
          VerificationLifecycleState, VerificationLifecycleState.Builder> implements
      // @@protoc_insertion_point(message_implements:addressiq.v1.VerificationLifecycleState)
      VerificationLifecycleStateOrBuilder {
    private VerificationLifecycleState() {
      appUserId_ = "";
      verificationId_ = "";
      locationCode_ = "";
    }
    public static final int STATE_FIELD_NUMBER = 1;
    private int state_;
    /**
     * <code>.addressiq.v1.LifecycleState state = 1 [json_name = "state"];</code>
     * @return The enum numeric value on the wire for state.
     */
    @java.lang.Override
    public int getStateValue() {
      return state_;
    }
    /**
     * <code>.addressiq.v1.LifecycleState state = 1 [json_name = "state"];</code>
     * @return The state.
     */
    @java.lang.Override
    public addressiq.v1.Sdk.LifecycleState getState() {
      addressiq.v1.Sdk.LifecycleState result = addressiq.v1.Sdk.LifecycleState.forNumber(state_);
      return result == null ? addressiq.v1.Sdk.LifecycleState.UNRECOGNIZED : result;
    }
    /**
     * <code>.addressiq.v1.LifecycleState state = 1 [json_name = "state"];</code>
     * @param value The enum numeric value on the wire for state to set.
     */
    private void setStateValue(int value) {
        state_ = value;
    }
    /**
     * <code>.addressiq.v1.LifecycleState state = 1 [json_name = "state"];</code>
     * @param value The state to set.
     */
    private void setState(addressiq.v1.Sdk.LifecycleState value) {
      state_ = value.getNumber();

    }
    /**
     * <code>.addressiq.v1.LifecycleState state = 1 [json_name = "state"];</code>
     */
    private void clearState() {

      state_ = 0;
    }

    public static final int APP_USER_ID_FIELD_NUMBER = 2;
    private java.lang.String appUserId_;
    /**
     * <code>string app_user_id = 2 [json_name = "appUserId"];</code>
     * @return The appUserId.
     */
    @java.lang.Override
    public java.lang.String getAppUserId() {
      return appUserId_;
    }
    /**
     * <code>string app_user_id = 2 [json_name = "appUserId"];</code>
     * @return The bytes for appUserId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAppUserIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(appUserId_);
    }
    /**
     * <code>string app_user_id = 2 [json_name = "appUserId"];</code>
     * @param value The appUserId to set.
     */
    private void setAppUserId(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      appUserId_ = value;
    }
    /**
     * <code>string app_user_id = 2 [json_name = "appUserId"];</code>
     */
    private void clearAppUserId() {

      appUserId_ = getDefaultInstance().getAppUserId();
    }
    /**
     * <code>string app_user_id = 2 [json_name = "appUserId"];</code>
     * @param value The bytes for appUserId to set.
     */
    private void setAppUserIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      appUserId_ = value.toStringUtf8();

    }

    public static final int VERIFICATION_ID_FIELD_NUMBER = 3;
    private java.lang.String verificationId_;
    /**
     * <code>string verification_id = 3 [json_name = "verificationId"];</code>
     * @return The verificationId.
     */
    @java.lang.Override
    public java.lang.String getVerificationId() {
      return verificationId_;
    }
    /**
     * <code>string verification_id = 3 [json_name = "verificationId"];</code>
     * @return The bytes for verificationId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVerificationIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(verificationId_);
    }
    /**
     * <code>string verification_id = 3 [json_name = "verificationId"];</code>
     * @param value The verificationId to set.
     */
    private void setVerificationId(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      verificationId_ = value;
    }
    /**
     * <code>string verification_id = 3 [json_name = "verificationId"];</code>
     */
    private void clearVerificationId() {

      verificationId_ = getDefaultInstance().getVerificationId();
    }
    /**
     * <code>string verification_id = 3 [json_name = "verificationId"];</code>
     * @param value The bytes for verificationId to set.
     */
    private void setVerificationIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      verificationId_ = value.toStringUtf8();

    }

    public static final int LOCATION_CODE_FIELD_NUMBER = 4;
    private java.lang.String locationCode_;
    /**
     * <code>string location_code = 4 [json_name = "locationCode"];</code>
     * @return The locationCode.
     */
    @java.lang.Override
    public java.lang.String getLocationCode() {
      return locationCode_;
    }
    /**
     * <code>string location_code = 4 [json_name = "locationCode"];</code>
     * @return The bytes for locationCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLocationCodeBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(locationCode_);
    }
    /**
     * <code>string location_code = 4 [json_name = "locationCode"];</code>
     * @param value The locationCode to set.
     */
    private void setLocationCode(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      locationCode_ = value;
    }
    /**
     * <code>string location_code = 4 [json_name = "locationCode"];</code>
     */
    private void clearLocationCode() {

      locationCode_ = getDefaultInstance().getLocationCode();
    }
    /**
     * <code>string location_code = 4 [json_name = "locationCode"];</code>
     * @param value The bytes for locationCode to set.
     */
    private void setLocationCodeBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      locationCode_ = value.toStringUtf8();

    }

    public static final int PAUSED_FOR_MS_FIELD_NUMBER = 5;
    private long pausedForMs_;
    /**
     * <code>int64 paused_for_ms = 5 [json_name = "pausedForMs"];</code>
     * @return The pausedForMs.
     */
    @java.lang.Override
    public long getPausedForMs() {
      return pausedForMs_;
    }
    /**
     * <code>int64 paused_for_ms = 5 [json_name = "pausedForMs"];</code>
     * @param value The pausedForMs to set.
     */
    private void setPausedForMs(long value) {
      
      pausedForMs_ = value;
    }
    /**
     * <code>int64 paused_for_ms = 5 [json_name = "pausedForMs"];</code>
     */
    private void clearPausedForMs() {

      pausedForMs_ = 0L;
    }

    public static addressiq.v1.Sdk.VerificationLifecycleState parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static addressiq.v1.Sdk.VerificationLifecycleState parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static addressiq.v1.Sdk.VerificationLifecycleState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static addressiq.v1.Sdk.VerificationLifecycleState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static addressiq.v1.Sdk.VerificationLifecycleState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static addressiq.v1.Sdk.VerificationLifecycleState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static addressiq.v1.Sdk.VerificationLifecycleState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static addressiq.v1.Sdk.VerificationLifecycleState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static addressiq.v1.Sdk.VerificationLifecycleState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static addressiq.v1.Sdk.VerificationLifecycleState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static addressiq.v1.Sdk.VerificationLifecycleState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static addressiq.v1.Sdk.VerificationLifecycleState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(addressiq.v1.Sdk.VerificationLifecycleState prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code addressiq.v1.VerificationLifecycleState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          addressiq.v1.Sdk.VerificationLifecycleState, Builder> implements
        // @@protoc_insertion_point(builder_implements:addressiq.v1.VerificationLifecycleState)
        addressiq.v1.Sdk.VerificationLifecycleStateOrBuilder {
      // Construct using addressiq.v1.Sdk.VerificationLifecycleState.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.addressiq.v1.LifecycleState state = 1 [json_name = "state"];</code>
       * @return The enum numeric value on the wire for state.
       */
      @java.lang.Override
      public int getStateValue() {
        return instance.getStateValue();
      }
      /**
       * <code>.addressiq.v1.LifecycleState state = 1 [json_name = "state"];</code>
       * @param value The state to set.
       * @return This builder for chaining.
       */
      public Builder setStateValue(int value) {
        copyOnWrite();
        instance.setStateValue(value);
        return this;
      }
      /**
       * <code>.addressiq.v1.LifecycleState state = 1 [json_name = "state"];</code>
       * @return The state.
       */
      @java.lang.Override
      public addressiq.v1.Sdk.LifecycleState getState() {
        return instance.getState();
      }
      /**
       * <code>.addressiq.v1.LifecycleState state = 1 [json_name = "state"];</code>
       * @param value The enum numeric value on the wire for state to set.
       * @return This builder for chaining.
       */
      public Builder setState(addressiq.v1.Sdk.LifecycleState value) {
        copyOnWrite();
        instance.setState(value);
        return this;
      }
      /**
       * <code>.addressiq.v1.LifecycleState state = 1 [json_name = "state"];</code>
       * @return This builder for chaining.
       */
      public Builder clearState() {
        copyOnWrite();
        instance.clearState();
        return this;
      }

      /**
       * <code>string app_user_id = 2 [json_name = "appUserId"];</code>
       * @return The appUserId.
       */
      @java.lang.Override
      public java.lang.String getAppUserId() {
        return instance.getAppUserId();
      }
      /**
       * <code>string app_user_id = 2 [json_name = "appUserId"];</code>
       * @return The bytes for appUserId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getAppUserIdBytes() {
        return instance.getAppUserIdBytes();
      }
      /**
       * <code>string app_user_id = 2 [json_name = "appUserId"];</code>
       * @param value The appUserId to set.
       * @return This builder for chaining.
       */
      public Builder setAppUserId(
          java.lang.String value) {
        copyOnWrite();
        instance.setAppUserId(value);
        return this;
      }
      /**
       * <code>string app_user_id = 2 [json_name = "appUserId"];</code>
       * @return This builder for chaining.
       */
      public Builder clearAppUserId() {
        copyOnWrite();
        instance.clearAppUserId();
        return this;
      }
      /**
       * <code>string app_user_id = 2 [json_name = "appUserId"];</code>
       * @param value The bytes for appUserId to set.
       * @return This builder for chaining.
       */
      public Builder setAppUserIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAppUserIdBytes(value);
        return this;
      }

      /**
       * <code>string verification_id = 3 [json_name = "verificationId"];</code>
       * @return The verificationId.
       */
      @java.lang.Override
      public java.lang.String getVerificationId() {
        return instance.getVerificationId();
      }
      /**
       * <code>string verification_id = 3 [json_name = "verificationId"];</code>
       * @return The bytes for verificationId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getVerificationIdBytes() {
        return instance.getVerificationIdBytes();
      }
      /**
       * <code>string verification_id = 3 [json_name = "verificationId"];</code>
       * @param value The verificationId to set.
       * @return This builder for chaining.
       */
      public Builder setVerificationId(
          java.lang.String value) {
        copyOnWrite();
        instance.setVerificationId(value);
        return this;
      }
      /**
       * <code>string verification_id = 3 [json_name = "verificationId"];</code>
       * @return This builder for chaining.
       */
      public Builder clearVerificationId() {
        copyOnWrite();
        instance.clearVerificationId();
        return this;
      }
      /**
       * <code>string verification_id = 3 [json_name = "verificationId"];</code>
       * @param value The bytes for verificationId to set.
       * @return This builder for chaining.
       */
      public Builder setVerificationIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setVerificationIdBytes(value);
        return this;
      }

      /**
       * <code>string location_code = 4 [json_name = "locationCode"];</code>
       * @return The locationCode.
       */
      @java.lang.Override
      public java.lang.String getLocationCode() {
        return instance.getLocationCode();
      }
      /**
       * <code>string location_code = 4 [json_name = "locationCode"];</code>
       * @return The bytes for locationCode.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getLocationCodeBytes() {
        return instance.getLocationCodeBytes();
      }
      /**
       * <code>string location_code = 4 [json_name = "locationCode"];</code>
       * @param value The locationCode to set.
       * @return This builder for chaining.
       */
      public Builder setLocationCode(
          java.lang.String value) {
        copyOnWrite();
        instance.setLocationCode(value);
        return this;
      }
      /**
       * <code>string location_code = 4 [json_name = "locationCode"];</code>
       * @return This builder for chaining.
       */
      public Builder clearLocationCode() {
        copyOnWrite();
        instance.clearLocationCode();
        return this;
      }
      /**
       * <code>string location_code = 4 [json_name = "locationCode"];</code>
       * @param value The bytes for locationCode to set.
       * @return This builder for chaining.
       */
      public Builder setLocationCodeBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setLocationCodeBytes(value);
        return this;
      }

      /**
       * <code>int64 paused_for_ms = 5 [json_name = "pausedForMs"];</code>
       * @return The pausedForMs.
       */
      @java.lang.Override
      public long getPausedForMs() {
        return instance.getPausedForMs();
      }
      /**
       * <code>int64 paused_for_ms = 5 [json_name = "pausedForMs"];</code>
       * @param value The pausedForMs to set.
       * @return This builder for chaining.
       */
      public Builder setPausedForMs(long value) {
        copyOnWrite();
        instance.setPausedForMs(value);
        return this;
      }
      /**
       * <code>int64 paused_for_ms = 5 [json_name = "pausedForMs"];</code>
       * @return This builder for chaining.
       */
      public Builder clearPausedForMs() {
        copyOnWrite();
        instance.clearPausedForMs();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:addressiq.v1.VerificationLifecycleState)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new addressiq.v1.Sdk.VerificationLifecycleState();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "state_",
              "appUserId_",
              "verificationId_",
              "locationCode_",
              "pausedForMs_",
            };
            java.lang.String info =
                "\u0000\u0005\u0000\u0000\u0001\u0005\u0005\u0000\u0000\u0000\u0001\f\u0002\u0208" +
                "\u0003\u0208\u0004\u0208\u0005\u0002";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<addressiq.v1.Sdk.VerificationLifecycleState> parser = PARSER;
          if (parser == null) {
            synchronized (addressiq.v1.Sdk.VerificationLifecycleState.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<addressiq.v1.Sdk.VerificationLifecycleState>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:addressiq.v1.VerificationLifecycleState)
    private static final addressiq.v1.Sdk.VerificationLifecycleState DEFAULT_INSTANCE;
    static {
      VerificationLifecycleState defaultInstance = new VerificationLifecycleState();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        VerificationLifecycleState.class, defaultInstance);
    }

    public static addressiq.v1.Sdk.VerificationLifecycleState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<VerificationLifecycleState> PARSER;

    public static com.google.protobuf.Parser<VerificationLifecycleState> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface PermissionStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:addressiq.v1.PermissionState)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.addressiq.v1.PermissionStatus foreground_location = 1 [json_name = "foregroundLocation"];</code>
     * @return The enum numeric value on the wire for foregroundLocation.
     */
    int getForegroundLocationValue();
    /**
     * <code>.addressiq.v1.PermissionStatus foreground_location = 1 [json_name = "foregroundLocation"];</code>
     * @return The foregroundLocation.
     */
    addressiq.v1.Sdk.PermissionStatus getForegroundLocation();

    /**
     * <code>.addressiq.v1.PermissionStatus background_location = 2 [json_name = "backgroundLocation"];</code>
     * @return The enum numeric value on the wire for backgroundLocation.
     */
    int getBackgroundLocationValue();
    /**
     * <code>.addressiq.v1.PermissionStatus background_location = 2 [json_name = "backgroundLocation"];</code>
     * @return The backgroundLocation.
     */
    addressiq.v1.Sdk.PermissionStatus getBackgroundLocation();

    /**
     * <code>.addressiq.v1.PermissionStatus notifications = 3 [json_name = "notifications"];</code>
     * @return The enum numeric value on the wire for notifications.
     */
    int getNotificationsValue();
    /**
     * <code>.addressiq.v1.PermissionStatus notifications = 3 [json_name = "notifications"];</code>
     * @return The notifications.
     */
    addressiq.v1.Sdk.PermissionStatus getNotifications();
  }
  /**
   * Protobuf type {@code addressiq.v1.PermissionState}
   */
  public  static final class PermissionState extends
      com.google.protobuf.GeneratedMessageLite<
          PermissionState, PermissionState.Builder> implements
      // @@protoc_insertion_point(message_implements:addressiq.v1.PermissionState)
      PermissionStateOrBuilder {
    private PermissionState() {
    }
    public static final int FOREGROUND_LOCATION_FIELD_NUMBER = 1;
    private int foregroundLocation_;
    /**
     * <code>.addressiq.v1.PermissionStatus foreground_location = 1 [json_name = "foregroundLocation"];</code>
     * @return The enum numeric value on the wire for foregroundLocation.
     */
    @java.lang.Override
    public int getForegroundLocationValue() {
      return foregroundLocation_;
    }
    /**
     * <code>.addressiq.v1.PermissionStatus foreground_location = 1 [json_name = "foregroundLocation"];</code>
     * @return The foregroundLocation.
     */
    @java.lang.Override
    public addressiq.v1.Sdk.PermissionStatus getForegroundLocation() {
      addressiq.v1.Sdk.PermissionStatus result = addressiq.v1.Sdk.PermissionStatus.forNumber(foregroundLocation_);
      return result == null ? addressiq.v1.Sdk.PermissionStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.addressiq.v1.PermissionStatus foreground_location = 1 [json_name = "foregroundLocation"];</code>
     * @param value The enum numeric value on the wire for foregroundLocation to set.
     */
    private void setForegroundLocationValue(int value) {
        foregroundLocation_ = value;
    }
    /**
     * <code>.addressiq.v1.PermissionStatus foreground_location = 1 [json_name = "foregroundLocation"];</code>
     * @param value The foregroundLocation to set.
     */
    private void setForegroundLocation(addressiq.v1.Sdk.PermissionStatus value) {
      foregroundLocation_ = value.getNumber();

    }
    /**
     * <code>.addressiq.v1.PermissionStatus foreground_location = 1 [json_name = "foregroundLocation"];</code>
     */
    private void clearForegroundLocation() {

      foregroundLocation_ = 0;
    }

    public static final int BACKGROUND_LOCATION_FIELD_NUMBER = 2;
    private int backgroundLocation_;
    /**
     * <code>.addressiq.v1.PermissionStatus background_location = 2 [json_name = "backgroundLocation"];</code>
     * @return The enum numeric value on the wire for backgroundLocation.
     */
    @java.lang.Override
    public int getBackgroundLocationValue() {
      return backgroundLocation_;
    }
    /**
     * <code>.addressiq.v1.PermissionStatus background_location = 2 [json_name = "backgroundLocation"];</code>
     * @return The backgroundLocation.
     */
    @java.lang.Override
    public addressiq.v1.Sdk.PermissionStatus getBackgroundLocation() {
      addressiq.v1.Sdk.PermissionStatus result = addressiq.v1.Sdk.PermissionStatus.forNumber(backgroundLocation_);
      return result == null ? addressiq.v1.Sdk.PermissionStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.addressiq.v1.PermissionStatus background_location = 2 [json_name = "backgroundLocation"];</code>
     * @param value The enum numeric value on the wire for backgroundLocation to set.
     */
    private void setBackgroundLocationValue(int value) {
        backgroundLocation_ = value;
    }
    /**
     * <code>.addressiq.v1.PermissionStatus background_location = 2 [json_name = "backgroundLocation"];</code>
     * @param value The backgroundLocation to set.
     */
    private void setBackgroundLocation(addressiq.v1.Sdk.PermissionStatus value) {
      backgroundLocation_ = value.getNumber();

    }
    /**
     * <code>.addressiq.v1.PermissionStatus background_location = 2 [json_name = "backgroundLocation"];</code>
     */
    private void clearBackgroundLocation() {

      backgroundLocation_ = 0;
    }

    public static final int NOTIFICATIONS_FIELD_NUMBER = 3;
    private int notifications_;
    /**
     * <code>.addressiq.v1.PermissionStatus notifications = 3 [json_name = "notifications"];</code>
     * @return The enum numeric value on the wire for notifications.
     */
    @java.lang.Override
    public int getNotificationsValue() {
      return notifications_;
    }
    /**
     * <code>.addressiq.v1.PermissionStatus notifications = 3 [json_name = "notifications"];</code>
     * @return The notifications.
     */
    @java.lang.Override
    public addressiq.v1.Sdk.PermissionStatus getNotifications() {
      addressiq.v1.Sdk.PermissionStatus result = addressiq.v1.Sdk.PermissionStatus.forNumber(notifications_);
      return result == null ? addressiq.v1.Sdk.PermissionStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.addressiq.v1.PermissionStatus notifications = 3 [json_name = "notifications"];</code>
     * @param value The enum numeric value on the wire for notifications to set.
     */
    private void setNotificationsValue(int value) {
        notifications_ = value;
    }
    /**
     * <code>.addressiq.v1.PermissionStatus notifications = 3 [json_name = "notifications"];</code>
     * @param value The notifications to set.
     */
    private void setNotifications(addressiq.v1.Sdk.PermissionStatus value) {
      notifications_ = value.getNumber();

    }
    /**
     * <code>.addressiq.v1.PermissionStatus notifications = 3 [json_name = "notifications"];</code>
     */
    private void clearNotifications() {

      notifications_ = 0;
    }

    public static addressiq.v1.Sdk.PermissionState parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static addressiq.v1.Sdk.PermissionState parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static addressiq.v1.Sdk.PermissionState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static addressiq.v1.Sdk.PermissionState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static addressiq.v1.Sdk.PermissionState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static addressiq.v1.Sdk.PermissionState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static addressiq.v1.Sdk.PermissionState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static addressiq.v1.Sdk.PermissionState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static addressiq.v1.Sdk.PermissionState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static addressiq.v1.Sdk.PermissionState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static addressiq.v1.Sdk.PermissionState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static addressiq.v1.Sdk.PermissionState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(addressiq.v1.Sdk.PermissionState prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code addressiq.v1.PermissionState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          addressiq.v1.Sdk.PermissionState, Builder> implements
        // @@protoc_insertion_point(builder_implements:addressiq.v1.PermissionState)
        addressiq.v1.Sdk.PermissionStateOrBuilder {
      // Construct using addressiq.v1.Sdk.PermissionState.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.addressiq.v1.PermissionStatus foreground_location = 1 [json_name = "foregroundLocation"];</code>
       * @return The enum numeric value on the wire for foregroundLocation.
       */
      @java.lang.Override
      public int getForegroundLocationValue() {
        return instance.getForegroundLocationValue();
      }
      /**
       * <code>.addressiq.v1.PermissionStatus foreground_location = 1 [json_name = "foregroundLocation"];</code>
       * @param value The foregroundLocation to set.
       * @return This builder for chaining.
       */
      public Builder setForegroundLocationValue(int value) {
        copyOnWrite();
        instance.setForegroundLocationValue(value);
        return this;
      }
      /**
       * <code>.addressiq.v1.PermissionStatus foreground_location = 1 [json_name = "foregroundLocation"];</code>
       * @return The foregroundLocation.
       */
      @java.lang.Override
      public addressiq.v1.Sdk.PermissionStatus getForegroundLocation() {
        return instance.getForegroundLocation();
      }
      /**
       * <code>.addressiq.v1.PermissionStatus foreground_location = 1 [json_name = "foregroundLocation"];</code>
       * @param value The enum numeric value on the wire for foregroundLocation to set.
       * @return This builder for chaining.
       */
      public Builder setForegroundLocation(addressiq.v1.Sdk.PermissionStatus value) {
        copyOnWrite();
        instance.setForegroundLocation(value);
        return this;
      }
      /**
       * <code>.addressiq.v1.PermissionStatus foreground_location = 1 [json_name = "foregroundLocation"];</code>
       * @return This builder for chaining.
       */
      public Builder clearForegroundLocation() {
        copyOnWrite();
        instance.clearForegroundLocation();
        return this;
      }

      /**
       * <code>.addressiq.v1.PermissionStatus background_location = 2 [json_name = "backgroundLocation"];</code>
       * @return The enum numeric value on the wire for backgroundLocation.
       */
      @java.lang.Override
      public int getBackgroundLocationValue() {
        return instance.getBackgroundLocationValue();
      }
      /**
       * <code>.addressiq.v1.PermissionStatus background_location = 2 [json_name = "backgroundLocation"];</code>
       * @param value The backgroundLocation to set.
       * @return This builder for chaining.
       */
      public Builder setBackgroundLocationValue(int value) {
        copyOnWrite();
        instance.setBackgroundLocationValue(value);
        return this;
      }
      /**
       * <code>.addressiq.v1.PermissionStatus background_location = 2 [json_name = "backgroundLocation"];</code>
       * @return The backgroundLocation.
       */
      @java.lang.Override
      public addressiq.v1.Sdk.PermissionStatus getBackgroundLocation() {
        return instance.getBackgroundLocation();
      }
      /**
       * <code>.addressiq.v1.PermissionStatus background_location = 2 [json_name = "backgroundLocation"];</code>
       * @param value The enum numeric value on the wire for backgroundLocation to set.
       * @return This builder for chaining.
       */
      public Builder setBackgroundLocation(addressiq.v1.Sdk.PermissionStatus value) {
        copyOnWrite();
        instance.setBackgroundLocation(value);
        return this;
      }
      /**
       * <code>.addressiq.v1.PermissionStatus background_location = 2 [json_name = "backgroundLocation"];</code>
       * @return This builder for chaining.
       */
      public Builder clearBackgroundLocation() {
        copyOnWrite();
        instance.clearBackgroundLocation();
        return this;
      }

      /**
       * <code>.addressiq.v1.PermissionStatus notifications = 3 [json_name = "notifications"];</code>
       * @return The enum numeric value on the wire for notifications.
       */
      @java.lang.Override
      public int getNotificationsValue() {
        return instance.getNotificationsValue();
      }
      /**
       * <code>.addressiq.v1.PermissionStatus notifications = 3 [json_name = "notifications"];</code>
       * @param value The notifications to set.
       * @return This builder for chaining.
       */
      public Builder setNotificationsValue(int value) {
        copyOnWrite();
        instance.setNotificationsValue(value);
        return this;
      }
      /**
       * <code>.addressiq.v1.PermissionStatus notifications = 3 [json_name = "notifications"];</code>
       * @return The notifications.
       */
      @java.lang.Override
      public addressiq.v1.Sdk.PermissionStatus getNotifications() {
        return instance.getNotifications();
      }
      /**
       * <code>.addressiq.v1.PermissionStatus notifications = 3 [json_name = "notifications"];</code>
       * @param value The enum numeric value on the wire for notifications to set.
       * @return This builder for chaining.
       */
      public Builder setNotifications(addressiq.v1.Sdk.PermissionStatus value) {
        copyOnWrite();
        instance.setNotifications(value);
        return this;
      }
      /**
       * <code>.addressiq.v1.PermissionStatus notifications = 3 [json_name = "notifications"];</code>
       * @return This builder for chaining.
       */
      public Builder clearNotifications() {
        copyOnWrite();
        instance.clearNotifications();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:addressiq.v1.PermissionState)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new addressiq.v1.Sdk.PermissionState();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "foregroundLocation_",
              "backgroundLocation_",
              "notifications_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\f\u0002\f\u0003" +
                "\f";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<addressiq.v1.Sdk.PermissionState> parser = PARSER;
          if (parser == null) {
            synchronized (addressiq.v1.Sdk.PermissionState.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<addressiq.v1.Sdk.PermissionState>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:addressiq.v1.PermissionState)
    private static final addressiq.v1.Sdk.PermissionState DEFAULT_INSTANCE;
    static {
      PermissionState defaultInstance = new PermissionState();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        PermissionState.class, defaultInstance);
    }

    public static addressiq.v1.Sdk.PermissionState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PermissionState> PARSER;

    public static com.google.protobuf.Parser<PermissionState> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface InvalidateSessionRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:addressiq.v1.InvalidateSessionRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string app_user_id = 1 [json_name = "appUserId"];</code>
     * @return The appUserId.
     */
    java.lang.String getAppUserId();
    /**
     * <code>string app_user_id = 1 [json_name = "appUserId"];</code>
     * @return The bytes for appUserId.
     */
    com.google.protobuf.ByteString
        getAppUserIdBytes();

    /**
     * <code>string verification_code = 2 [json_name = "verificationCode"];</code>
     * @return The verificationCode.
     */
    java.lang.String getVerificationCode();
    /**
     * <code>string verification_code = 2 [json_name = "verificationCode"];</code>
     * @return The bytes for verificationCode.
     */
    com.google.protobuf.ByteString
        getVerificationCodeBytes();
  }
  /**
   * Protobuf type {@code addressiq.v1.InvalidateSessionRequest}
   */
  public  static final class InvalidateSessionRequest extends
      com.google.protobuf.GeneratedMessageLite<
          InvalidateSessionRequest, InvalidateSessionRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:addressiq.v1.InvalidateSessionRequest)
      InvalidateSessionRequestOrBuilder {
    private InvalidateSessionRequest() {
      appUserId_ = "";
      verificationCode_ = "";
    }
    public static final int APP_USER_ID_FIELD_NUMBER = 1;
    private java.lang.String appUserId_;
    /**
     * <code>string app_user_id = 1 [json_name = "appUserId"];</code>
     * @return The appUserId.
     */
    @java.lang.Override
    public java.lang.String getAppUserId() {
      return appUserId_;
    }
    /**
     * <code>string app_user_id = 1 [json_name = "appUserId"];</code>
     * @return The bytes for appUserId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAppUserIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(appUserId_);
    }
    /**
     * <code>string app_user_id = 1 [json_name = "appUserId"];</code>
     * @param value The appUserId to set.
     */
    private void setAppUserId(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      appUserId_ = value;
    }
    /**
     * <code>string app_user_id = 1 [json_name = "appUserId"];</code>
     */
    private void clearAppUserId() {

      appUserId_ = getDefaultInstance().getAppUserId();
    }
    /**
     * <code>string app_user_id = 1 [json_name = "appUserId"];</code>
     * @param value The bytes for appUserId to set.
     */
    private void setAppUserIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      appUserId_ = value.toStringUtf8();

    }

    public static final int VERIFICATION_CODE_FIELD_NUMBER = 2;
    private java.lang.String verificationCode_;
    /**
     * <code>string verification_code = 2 [json_name = "verificationCode"];</code>
     * @return The verificationCode.
     */
    @java.lang.Override
    public java.lang.String getVerificationCode() {
      return verificationCode_;
    }
    /**
     * <code>string verification_code = 2 [json_name = "verificationCode"];</code>
     * @return The bytes for verificationCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVerificationCodeBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(verificationCode_);
    }
    /**
     * <code>string verification_code = 2 [json_name = "verificationCode"];</code>
     * @param value The verificationCode to set.
     */
    private void setVerificationCode(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      verificationCode_ = value;
    }
    /**
     * <code>string verification_code = 2 [json_name = "verificationCode"];</code>
     */
    private void clearVerificationCode() {

      verificationCode_ = getDefaultInstance().getVerificationCode();
    }
    /**
     * <code>string verification_code = 2 [json_name = "verificationCode"];</code>
     * @param value The bytes for verificationCode to set.
     */
    private void setVerificationCodeBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      verificationCode_ = value.toStringUtf8();

    }

    public static addressiq.v1.Sdk.InvalidateSessionRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static addressiq.v1.Sdk.InvalidateSessionRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static addressiq.v1.Sdk.InvalidateSessionRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static addressiq.v1.Sdk.InvalidateSessionRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static addressiq.v1.Sdk.InvalidateSessionRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static addressiq.v1.Sdk.InvalidateSessionRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static addressiq.v1.Sdk.InvalidateSessionRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static addressiq.v1.Sdk.InvalidateSessionRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static addressiq.v1.Sdk.InvalidateSessionRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static addressiq.v1.Sdk.InvalidateSessionRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static addressiq.v1.Sdk.InvalidateSessionRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static addressiq.v1.Sdk.InvalidateSessionRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(addressiq.v1.Sdk.InvalidateSessionRequest prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code addressiq.v1.InvalidateSessionRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          addressiq.v1.Sdk.InvalidateSessionRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:addressiq.v1.InvalidateSessionRequest)
        addressiq.v1.Sdk.InvalidateSessionRequestOrBuilder {
      // Construct using addressiq.v1.Sdk.InvalidateSessionRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string app_user_id = 1 [json_name = "appUserId"];</code>
       * @return The appUserId.
       */
      @java.lang.Override
      public java.lang.String getAppUserId() {
        return instance.getAppUserId();
      }
      /**
       * <code>string app_user_id = 1 [json_name = "appUserId"];</code>
       * @return The bytes for appUserId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getAppUserIdBytes() {
        return instance.getAppUserIdBytes();
      }
      /**
       * <code>string app_user_id = 1 [json_name = "appUserId"];</code>
       * @param value The appUserId to set.
       * @return This builder for chaining.
       */
      public Builder setAppUserId(
          java.lang.String value) {
        copyOnWrite();
        instance.setAppUserId(value);
        return this;
      }
      /**
       * <code>string app_user_id = 1 [json_name = "appUserId"];</code>
       * @return This builder for chaining.
       */
      public Builder clearAppUserId() {
        copyOnWrite();
        instance.clearAppUserId();
        return this;
      }
      /**
       * <code>string app_user_id = 1 [json_name = "appUserId"];</code>
       * @param value The bytes for appUserId to set.
       * @return This builder for chaining.
       */
      public Builder setAppUserIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAppUserIdBytes(value);
        return this;
      }

      /**
       * <code>string verification_code = 2 [json_name = "verificationCode"];</code>
       * @return The verificationCode.
       */
      @java.lang.Override
      public java.lang.String getVerificationCode() {
        return instance.getVerificationCode();
      }
      /**
       * <code>string verification_code = 2 [json_name = "verificationCode"];</code>
       * @return The bytes for verificationCode.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getVerificationCodeBytes() {
        return instance.getVerificationCodeBytes();
      }
      /**
       * <code>string verification_code = 2 [json_name = "verificationCode"];</code>
       * @param value The verificationCode to set.
       * @return This builder for chaining.
       */
      public Builder setVerificationCode(
          java.lang.String value) {
        copyOnWrite();
        instance.setVerificationCode(value);
        return this;
      }
      /**
       * <code>string verification_code = 2 [json_name = "verificationCode"];</code>
       * @return This builder for chaining.
       */
      public Builder clearVerificationCode() {
        copyOnWrite();
        instance.clearVerificationCode();
        return this;
      }
      /**
       * <code>string verification_code = 2 [json_name = "verificationCode"];</code>
       * @param value The bytes for verificationCode to set.
       * @return This builder for chaining.
       */
      public Builder setVerificationCodeBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setVerificationCodeBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:addressiq.v1.InvalidateSessionRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new addressiq.v1.Sdk.InvalidateSessionRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "appUserId_",
              "verificationCode_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<addressiq.v1.Sdk.InvalidateSessionRequest> parser = PARSER;
          if (parser == null) {
            synchronized (addressiq.v1.Sdk.InvalidateSessionRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<addressiq.v1.Sdk.InvalidateSessionRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:addressiq.v1.InvalidateSessionRequest)
    private static final addressiq.v1.Sdk.InvalidateSessionRequest DEFAULT_INSTANCE;
    static {
      InvalidateSessionRequest defaultInstance = new InvalidateSessionRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        InvalidateSessionRequest.class, defaultInstance);
    }

    public static addressiq.v1.Sdk.InvalidateSessionRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<InvalidateSessionRequest> PARSER;

    public static com.google.protobuf.Parser<InvalidateSessionRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface InvalidateSessionResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:addressiq.v1.InvalidateSessionResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>bool revoked = 1 [json_name = "revoked"];</code>
     * @return The revoked.
     */
    boolean getRevoked();
  }
  /**
   * Protobuf type {@code addressiq.v1.InvalidateSessionResponse}
   */
  public  static final class InvalidateSessionResponse extends
      com.google.protobuf.GeneratedMessageLite<
          InvalidateSessionResponse, InvalidateSessionResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:addressiq.v1.InvalidateSessionResponse)
      InvalidateSessionResponseOrBuilder {
    private InvalidateSessionResponse() {
    }
    public static final int REVOKED_FIELD_NUMBER = 1;
    private boolean revoked_;
    /**
     * <code>bool revoked = 1 [json_name = "revoked"];</code>
     * @return The revoked.
     */
    @java.lang.Override
    public boolean getRevoked() {
      return revoked_;
    }
    /**
     * <code>bool revoked = 1 [json_name = "revoked"];</code>
     * @param value The revoked to set.
     */
    private void setRevoked(boolean value) {
      
      revoked_ = value;
    }
    /**
     * <code>bool revoked = 1 [json_name = "revoked"];</code>
     */
    private void clearRevoked() {

      revoked_ = false;
    }

    public static addressiq.v1.Sdk.InvalidateSessionResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static addressiq.v1.Sdk.InvalidateSessionResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static addressiq.v1.Sdk.InvalidateSessionResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static addressiq.v1.Sdk.InvalidateSessionResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static addressiq.v1.Sdk.InvalidateSessionResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static addressiq.v1.Sdk.InvalidateSessionResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static addressiq.v1.Sdk.InvalidateSessionResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static addressiq.v1.Sdk.InvalidateSessionResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static addressiq.v1.Sdk.InvalidateSessionResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static addressiq.v1.Sdk.InvalidateSessionResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static addressiq.v1.Sdk.InvalidateSessionResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static addressiq.v1.Sdk.InvalidateSessionResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(addressiq.v1.Sdk.InvalidateSessionResponse prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code addressiq.v1.InvalidateSessionResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          addressiq.v1.Sdk.InvalidateSessionResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:addressiq.v1.InvalidateSessionResponse)
        addressiq.v1.Sdk.InvalidateSessionResponseOrBuilder {
      // Construct using addressiq.v1.Sdk.InvalidateSessionResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>bool revoked = 1 [json_name = "revoked"];</code>
       * @return The revoked.
       */
      @java.lang.Override
      public boolean getRevoked() {
        return instance.getRevoked();
      }
      /**
       * <code>bool revoked = 1 [json_name = "revoked"];</code>
       * @param value The revoked to set.
       * @return This builder for chaining.
       */
      public Builder setRevoked(boolean value) {
        copyOnWrite();
        instance.setRevoked(value);
        return this;
      }
      /**
       * <code>bool revoked = 1 [json_name = "revoked"];</code>
       * @return This builder for chaining.
       */
      public Builder clearRevoked() {
        copyOnWrite();
        instance.clearRevoked();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:addressiq.v1.InvalidateSessionResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new addressiq.v1.Sdk.InvalidateSessionResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "revoked_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0007";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<addressiq.v1.Sdk.InvalidateSessionResponse> parser = PARSER;
          if (parser == null) {
            synchronized (addressiq.v1.Sdk.InvalidateSessionResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<addressiq.v1.Sdk.InvalidateSessionResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:addressiq.v1.InvalidateSessionResponse)
    private static final addressiq.v1.Sdk.InvalidateSessionResponse DEFAULT_INSTANCE;
    static {
      InvalidateSessionResponse defaultInstance = new InvalidateSessionResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        InvalidateSessionResponse.class, defaultInstance);
    }

    public static addressiq.v1.Sdk.InvalidateSessionResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<InvalidateSessionResponse> PARSER;

    public static com.google.protobuf.Parser<InvalidateSessionResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
