// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressiq/v1/verification.proto

// Protobuf Java Version: 3.25.3
package addressiq.v1;

public final class VerificationOuterClass {
  private VerificationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code addressiq.v1.VerificationType}
   */
  public enum VerificationType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>VERIFICATION_TYPE_UNSPECIFIED = 0;</code>
     */
    VERIFICATION_TYPE_UNSPECIFIED(0),
    /**
     * <code>DIGITAL = 1;</code>
     */
    DIGITAL(1),
    /**
     * <code>PHYSICAL = 2;</code>
     */
    PHYSICAL(2),
    /**
     * <code>COMBINED = 3;</code>
     */
    COMBINED(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>VERIFICATION_TYPE_UNSPECIFIED = 0;</code>
     */
    public static final int VERIFICATION_TYPE_UNSPECIFIED_VALUE = 0;
    /**
     * <code>DIGITAL = 1;</code>
     */
    public static final int DIGITAL_VALUE = 1;
    /**
     * <code>PHYSICAL = 2;</code>
     */
    public static final int PHYSICAL_VALUE = 2;
    /**
     * <code>COMBINED = 3;</code>
     */
    public static final int COMBINED_VALUE = 3;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static VerificationType valueOf(int value) {
      return forNumber(value);
    }

    public static VerificationType forNumber(int value) {
      switch (value) {
        case 0: return VERIFICATION_TYPE_UNSPECIFIED;
        case 1: return DIGITAL;
        case 2: return PHYSICAL;
        case 3: return COMBINED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<VerificationType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        VerificationType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<VerificationType>() {
            @java.lang.Override
            public VerificationType findValueByNumber(int number) {
              return VerificationType.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return VerificationTypeVerifier.INSTANCE;
    }

    private static final class VerificationTypeVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new VerificationTypeVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return VerificationType.forNumber(number) != null;
            }
          };

    private final int value;

    private VerificationType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:addressiq.v1.VerificationType)
  }

  /**
   * Protobuf enum {@code addressiq.v1.VerificationStatus}
   */
  public enum VerificationStatus
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>VERIFICATION_STATUS_UNSPECIFIED = 0;</code>
     */
    VERIFICATION_STATUS_UNSPECIFIED(0),
    /**
     * <code>PENDING = 1;</code>
     */
    PENDING(1),
    /**
     * <code>ASSIGNED = 2;</code>
     */
    ASSIGNED(2),
    /**
     * <code>IN_PROGRESS = 3;</code>
     */
    IN_PROGRESS(3),
    /**
     * <code>VERIFIED = 4;</code>
     */
    VERIFIED(4),
    /**
     * <code>NOT_AT_ADDRESS = 5;</code>
     */
    NOT_AT_ADDRESS(5),
    /**
     * <code>STATUS_UNKNOWN = 6;</code>
     */
    STATUS_UNKNOWN(6),
    /**
     * <code>FAILED = 7;</code>
     */
    FAILED(7),
    /**
     * <code>EXPIRED = 8;</code>
     */
    EXPIRED(8),
    /**
     * <code>CANCELLED = 9;</code>
     */
    CANCELLED(9),
    /**
     * <code>UNDER_REVIEW = 10;</code>
     */
    UNDER_REVIEW(10),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>VERIFICATION_STATUS_UNSPECIFIED = 0;</code>
     */
    public static final int VERIFICATION_STATUS_UNSPECIFIED_VALUE = 0;
    /**
     * <code>PENDING = 1;</code>
     */
    public static final int PENDING_VALUE = 1;
    /**
     * <code>ASSIGNED = 2;</code>
     */
    public static final int ASSIGNED_VALUE = 2;
    /**
     * <code>IN_PROGRESS = 3;</code>
     */
    public static final int IN_PROGRESS_VALUE = 3;
    /**
     * <code>VERIFIED = 4;</code>
     */
    public static final int VERIFIED_VALUE = 4;
    /**
     * <code>NOT_AT_ADDRESS = 5;</code>
     */
    public static final int NOT_AT_ADDRESS_VALUE = 5;
    /**
     * <code>STATUS_UNKNOWN = 6;</code>
     */
    public static final int STATUS_UNKNOWN_VALUE = 6;
    /**
     * <code>FAILED = 7;</code>
     */
    public static final int FAILED_VALUE = 7;
    /**
     * <code>EXPIRED = 8;</code>
     */
    public static final int EXPIRED_VALUE = 8;
    /**
     * <code>CANCELLED = 9;</code>
     */
    public static final int CANCELLED_VALUE = 9;
    /**
     * <code>UNDER_REVIEW = 10;</code>
     */
    public static final int UNDER_REVIEW_VALUE = 10;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static VerificationStatus valueOf(int value) {
      return forNumber(value);
    }

    public static VerificationStatus forNumber(int value) {
      switch (value) {
        case 0: return VERIFICATION_STATUS_UNSPECIFIED;
        case 1: return PENDING;
        case 2: return ASSIGNED;
        case 3: return IN_PROGRESS;
        case 4: return VERIFIED;
        case 5: return NOT_AT_ADDRESS;
        case 6: return STATUS_UNKNOWN;
        case 7: return FAILED;
        case 8: return EXPIRED;
        case 9: return CANCELLED;
        case 10: return UNDER_REVIEW;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<VerificationStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        VerificationStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<VerificationStatus>() {
            @java.lang.Override
            public VerificationStatus findValueByNumber(int number) {
              return VerificationStatus.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return VerificationStatusVerifier.INSTANCE;
    }

    private static final class VerificationStatusVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new VerificationStatusVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return VerificationStatus.forNumber(number) != null;
            }
          };

    private final int value;

    private VerificationStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:addressiq.v1.VerificationStatus)
  }

  /**
   * Protobuf enum {@code addressiq.v1.ReviewState}
   */
  public enum ReviewState
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>REVIEW_STATE_UNSPECIFIED = 0;</code>
     */
    REVIEW_STATE_UNSPECIFIED(0),
    /**
     * <code>NONE = 1;</code>
     */
    NONE(1),
    /**
     * <code>FLAGGED = 2;</code>
     */
    FLAGGED(2),
    /**
     * <code>MANUAL_REVIEW = 3;</code>
     */
    MANUAL_REVIEW(3),
    /**
     * <code>ESCALATED = 4;</code>
     */
    ESCALATED(4),
    /**
     * <code>RESOLVED = 5;</code>
     */
    RESOLVED(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>REVIEW_STATE_UNSPECIFIED = 0;</code>
     */
    public static final int REVIEW_STATE_UNSPECIFIED_VALUE = 0;
    /**
     * <code>NONE = 1;</code>
     */
    public static final int NONE_VALUE = 1;
    /**
     * <code>FLAGGED = 2;</code>
     */
    public static final int FLAGGED_VALUE = 2;
    /**
     * <code>MANUAL_REVIEW = 3;</code>
     */
    public static final int MANUAL_REVIEW_VALUE = 3;
    /**
     * <code>ESCALATED = 4;</code>
     */
    public static final int ESCALATED_VALUE = 4;
    /**
     * <code>RESOLVED = 5;</code>
     */
    public static final int RESOLVED_VALUE = 5;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ReviewState valueOf(int value) {
      return forNumber(value);
    }

    public static ReviewState forNumber(int value) {
      switch (value) {
        case 0: return REVIEW_STATE_UNSPECIFIED;
        case 1: return NONE;
        case 2: return FLAGGED;
        case 3: return MANUAL_REVIEW;
        case 4: return ESCALATED;
        case 5: return RESOLVED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ReviewState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ReviewState> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ReviewState>() {
            @java.lang.Override
            public ReviewState findValueByNumber(int number) {
              return ReviewState.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return ReviewStateVerifier.INSTANCE;
    }

    private static final class ReviewStateVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new ReviewStateVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return ReviewState.forNumber(number) != null;
            }
          };

    private final int value;

    private ReviewState(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:addressiq.v1.ReviewState)
  }

  public interface VerificationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:addressiq.v1.Verification)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string verification_code = 2 [json_name = "verificationCode"];</code>
     * @return The verificationCode.
     */
    java.lang.String getVerificationCode();
    /**
     * <code>string verification_code = 2 [json_name = "verificationCode"];</code>
     * @return The bytes for verificationCode.
     */
    com.google.protobuf.ByteString
        getVerificationCodeBytes();

    /**
     * <code>string organization_id = 3 [json_name = "organizationId"];</code>
     * @return The organizationId.
     */
    java.lang.String getOrganizationId();
    /**
     * <code>string organization_id = 3 [json_name = "organizationId"];</code>
     * @return The bytes for organizationId.
     */
    com.google.protobuf.ByteString
        getOrganizationIdBytes();

    /**
     * <code>string app_id = 4 [json_name = "appId"];</code>
     * @return The appId.
     */
    java.lang.String getAppId();
    /**
     * <code>string app_id = 4 [json_name = "appId"];</code>
     * @return The bytes for appId.
     */
    com.google.protobuf.ByteString
        getAppIdBytes();

    /**
     * <code>string branch_id = 5 [json_name = "branchId"];</code>
     * @return The branchId.
     */
    java.lang.String getBranchId();
    /**
     * <code>string branch_id = 5 [json_name = "branchId"];</code>
     * @return The bytes for branchId.
     */
    com.google.protobuf.ByteString
        getBranchIdBytes();

    /**
     * <code>string app_user_id = 6 [json_name = "appUserId"];</code>
     * @return The appUserId.
     */
    java.lang.String getAppUserId();
    /**
     * <code>string app_user_id = 6 [json_name = "appUserId"];</code>
     * @return The bytes for appUserId.
     */
    com.google.protobuf.ByteString
        getAppUserIdBytes();

    /**
     * <code>string location_id = 7 [json_name = "locationId"];</code>
     * @return The locationId.
     */
    java.lang.String getLocationId();
    /**
     * <code>string location_id = 7 [json_name = "locationId"];</code>
     * @return The bytes for locationId.
     */
    com.google.protobuf.ByteString
        getLocationIdBytes();

    /**
     * <code>.addressiq.v1.VerificationType type = 8 [json_name = "type"];</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.addressiq.v1.VerificationType type = 8 [json_name = "type"];</code>
     * @return The type.
     */
    addressiq.v1.VerificationOuterClass.VerificationType getType();

    /**
     * <pre>
     * slug
     * </pre>
     *
     * <code>string provider = 9 [json_name = "provider"];</code>
     * @return The provider.
     */
    java.lang.String getProvider();
    /**
     * <pre>
     * slug
     * </pre>
     *
     * <code>string provider = 9 [json_name = "provider"];</code>
     * @return The bytes for provider.
     */
    com.google.protobuf.ByteString
        getProviderBytes();

    /**
     * <code>string provider_reference_id = 10 [json_name = "providerReferenceId"];</code>
     * @return The providerReferenceId.
     */
    java.lang.String getProviderReferenceId();
    /**
     * <code>string provider_reference_id = 10 [json_name = "providerReferenceId"];</code>
     * @return The bytes for providerReferenceId.
     */
    com.google.protobuf.ByteString
        getProviderReferenceIdBytes();

    /**
     * <code>.addressiq.v1.VerificationStatus status = 11 [json_name = "status"];</code>
     * @return The enum numeric value on the wire for status.
     */
    int getStatusValue();
    /**
     * <code>.addressiq.v1.VerificationStatus status = 11 [json_name = "status"];</code>
     * @return The status.
     */
    addressiq.v1.VerificationOuterClass.VerificationStatus getStatus();

    /**
     * <code>.addressiq.v1.ReviewState review_state = 12 [json_name = "reviewState"];</code>
     * @return The enum numeric value on the wire for reviewState.
     */
    int getReviewStateValue();
    /**
     * <code>.addressiq.v1.ReviewState review_state = 12 [json_name = "reviewState"];</code>
     * @return The reviewState.
     */
    addressiq.v1.VerificationOuterClass.ReviewState getReviewState();

    /**
     * <code>double confidence_score = 13 [json_name = "confidenceScore"];</code>
     * @return The confidenceScore.
     */
    double getConfidenceScore();

    /**
     * <code>.google.protobuf.Timestamp window_ends_at = 14 [json_name = "windowEndsAt"];</code>
     * @return Whether the windowEndsAt field is set.
     */
    boolean hasWindowEndsAt();
    /**
     * <code>.google.protobuf.Timestamp window_ends_at = 14 [json_name = "windowEndsAt"];</code>
     * @return The windowEndsAt.
     */
    com.google.protobuf.Timestamp getWindowEndsAt();

    /**
     * <code>.google.protobuf.Timestamp resolved_at = 15 [json_name = "resolvedAt"];</code>
     * @return Whether the resolvedAt field is set.
     */
    boolean hasResolvedAt();
    /**
     * <code>.google.protobuf.Timestamp resolved_at = 15 [json_name = "resolvedAt"];</code>
     * @return The resolvedAt.
     */
    com.google.protobuf.Timestamp getResolvedAt();
  }
  /**
   * Protobuf type {@code addressiq.v1.Verification}
   */
  public  static final class Verification extends
      com.google.protobuf.GeneratedMessageLite<
          Verification, Verification.Builder> implements
      // @@protoc_insertion_point(message_implements:addressiq.v1.Verification)
      VerificationOrBuilder {
    private Verification() {
      id_ = "";
      verificationCode_ = "";
      organizationId_ = "";
      appId_ = "";
      branchId_ = "";
      appUserId_ = "";
      locationId_ = "";
      provider_ = "";
      providerReferenceId_ = "";
    }
    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.String id_;
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      return id_;
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(id_);
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The id to set.
     */
    private void setId(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      id_ = value;
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     */
    private void clearId() {

      id_ = getDefaultInstance().getId();
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The bytes for id to set.
     */
    private void setIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      id_ = value.toStringUtf8();

    }

    public static final int VERIFICATION_CODE_FIELD_NUMBER = 2;
    private java.lang.String verificationCode_;
    /**
     * <code>string verification_code = 2 [json_name = "verificationCode"];</code>
     * @return The verificationCode.
     */
    @java.lang.Override
    public java.lang.String getVerificationCode() {
      return verificationCode_;
    }
    /**
     * <code>string verification_code = 2 [json_name = "verificationCode"];</code>
     * @return The bytes for verificationCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVerificationCodeBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(verificationCode_);
    }
    /**
     * <code>string verification_code = 2 [json_name = "verificationCode"];</code>
     * @param value The verificationCode to set.
     */
    private void setVerificationCode(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      verificationCode_ = value;
    }
    /**
     * <code>string verification_code = 2 [json_name = "verificationCode"];</code>
     */
    private void clearVerificationCode() {

      verificationCode_ = getDefaultInstance().getVerificationCode();
    }
    /**
     * <code>string verification_code = 2 [json_name = "verificationCode"];</code>
     * @param value The bytes for verificationCode to set.
     */
    private void setVerificationCodeBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      verificationCode_ = value.toStringUtf8();

    }

    public static final int ORGANIZATION_ID_FIELD_NUMBER = 3;
    private java.lang.String organizationId_;
    /**
     * <code>string organization_id = 3 [json_name = "organizationId"];</code>
     * @return The organizationId.
     */
    @java.lang.Override
    public java.lang.String getOrganizationId() {
      return organizationId_;
    }
    /**
     * <code>string organization_id = 3 [json_name = "organizationId"];</code>
     * @return The bytes for organizationId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOrganizationIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(organizationId_);
    }
    /**
     * <code>string organization_id = 3 [json_name = "organizationId"];</code>
     * @param value The organizationId to set.
     */
    private void setOrganizationId(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      organizationId_ = value;
    }
    /**
     * <code>string organization_id = 3 [json_name = "organizationId"];</code>
     */
    private void clearOrganizationId() {

      organizationId_ = getDefaultInstance().getOrganizationId();
    }
    /**
     * <code>string organization_id = 3 [json_name = "organizationId"];</code>
     * @param value The bytes for organizationId to set.
     */
    private void setOrganizationIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      organizationId_ = value.toStringUtf8();

    }

    public static final int APP_ID_FIELD_NUMBER = 4;
    private java.lang.String appId_;
    /**
     * <code>string app_id = 4 [json_name = "appId"];</code>
     * @return The appId.
     */
    @java.lang.Override
    public java.lang.String getAppId() {
      return appId_;
    }
    /**
     * <code>string app_id = 4 [json_name = "appId"];</code>
     * @return The bytes for appId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAppIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(appId_);
    }
    /**
     * <code>string app_id = 4 [json_name = "appId"];</code>
     * @param value The appId to set.
     */
    private void setAppId(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      appId_ = value;
    }
    /**
     * <code>string app_id = 4 [json_name = "appId"];</code>
     */
    private void clearAppId() {

      appId_ = getDefaultInstance().getAppId();
    }
    /**
     * <code>string app_id = 4 [json_name = "appId"];</code>
     * @param value The bytes for appId to set.
     */
    private void setAppIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      appId_ = value.toStringUtf8();

    }

    public static final int BRANCH_ID_FIELD_NUMBER = 5;
    private java.lang.String branchId_;
    /**
     * <code>string branch_id = 5 [json_name = "branchId"];</code>
     * @return The branchId.
     */
    @java.lang.Override
    public java.lang.String getBranchId() {
      return branchId_;
    }
    /**
     * <code>string branch_id = 5 [json_name = "branchId"];</code>
     * @return The bytes for branchId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBranchIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(branchId_);
    }
    /**
     * <code>string branch_id = 5 [json_name = "branchId"];</code>
     * @param value The branchId to set.
     */
    private void setBranchId(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      branchId_ = value;
    }
    /**
     * <code>string branch_id = 5 [json_name = "branchId"];</code>
     */
    private void clearBranchId() {

      branchId_ = getDefaultInstance().getBranchId();
    }
    /**
     * <code>string branch_id = 5 [json_name = "branchId"];</code>
     * @param value The bytes for branchId to set.
     */
    private void setBranchIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      branchId_ = value.toStringUtf8();

    }

    public static final int APP_USER_ID_FIELD_NUMBER = 6;
    private java.lang.String appUserId_;
    /**
     * <code>string app_user_id = 6 [json_name = "appUserId"];</code>
     * @return The appUserId.
     */
    @java.lang.Override
    public java.lang.String getAppUserId() {
      return appUserId_;
    }
    /**
     * <code>string app_user_id = 6 [json_name = "appUserId"];</code>
     * @return The bytes for appUserId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAppUserIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(appUserId_);
    }
    /**
     * <code>string app_user_id = 6 [json_name = "appUserId"];</code>
     * @param value The appUserId to set.
     */
    private void setAppUserId(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      appUserId_ = value;
    }
    /**
     * <code>string app_user_id = 6 [json_name = "appUserId"];</code>
     */
    private void clearAppUserId() {

      appUserId_ = getDefaultInstance().getAppUserId();
    }
    /**
     * <code>string app_user_id = 6 [json_name = "appUserId"];</code>
     * @param value The bytes for appUserId to set.
     */
    private void setAppUserIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      appUserId_ = value.toStringUtf8();

    }

    public static final int LOCATION_ID_FIELD_NUMBER = 7;
    private java.lang.String locationId_;
    /**
     * <code>string location_id = 7 [json_name = "locationId"];</code>
     * @return The locationId.
     */
    @java.lang.Override
    public java.lang.String getLocationId() {
      return locationId_;
    }
    /**
     * <code>string location_id = 7 [json_name = "locationId"];</code>
     * @return The bytes for locationId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLocationIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(locationId_);
    }
    /**
     * <code>string location_id = 7 [json_name = "locationId"];</code>
     * @param value The locationId to set.
     */
    private void setLocationId(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      locationId_ = value;
    }
    /**
     * <code>string location_id = 7 [json_name = "locationId"];</code>
     */
    private void clearLocationId() {

      locationId_ = getDefaultInstance().getLocationId();
    }
    /**
     * <code>string location_id = 7 [json_name = "locationId"];</code>
     * @param value The bytes for locationId to set.
     */
    private void setLocationIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      locationId_ = value.toStringUtf8();

    }

    public static final int TYPE_FIELD_NUMBER = 8;
    private int type_;
    /**
     * <code>.addressiq.v1.VerificationType type = 8 [json_name = "type"];</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.addressiq.v1.VerificationType type = 8 [json_name = "type"];</code>
     * @return The type.
     */
    @java.lang.Override
    public addressiq.v1.VerificationOuterClass.VerificationType getType() {
      addressiq.v1.VerificationOuterClass.VerificationType result = addressiq.v1.VerificationOuterClass.VerificationType.forNumber(type_);
      return result == null ? addressiq.v1.VerificationOuterClass.VerificationType.UNRECOGNIZED : result;
    }
    /**
     * <code>.addressiq.v1.VerificationType type = 8 [json_name = "type"];</code>
     * @param value The enum numeric value on the wire for type to set.
     */
    private void setTypeValue(int value) {
        type_ = value;
    }
    /**
     * <code>.addressiq.v1.VerificationType type = 8 [json_name = "type"];</code>
     * @param value The type to set.
     */
    private void setType(addressiq.v1.VerificationOuterClass.VerificationType value) {
      type_ = value.getNumber();

    }
    /**
     * <code>.addressiq.v1.VerificationType type = 8 [json_name = "type"];</code>
     */
    private void clearType() {

      type_ = 0;
    }

    public static final int PROVIDER_FIELD_NUMBER = 9;
    private java.lang.String provider_;
    /**
     * <pre>
     * slug
     * </pre>
     *
     * <code>string provider = 9 [json_name = "provider"];</code>
     * @return The provider.
     */
    @java.lang.Override
    public java.lang.String getProvider() {
      return provider_;
    }
    /**
     * <pre>
     * slug
     * </pre>
     *
     * <code>string provider = 9 [json_name = "provider"];</code>
     * @return The bytes for provider.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProviderBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(provider_);
    }
    /**
     * <pre>
     * slug
     * </pre>
     *
     * <code>string provider = 9 [json_name = "provider"];</code>
     * @param value The provider to set.
     */
    private void setProvider(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      provider_ = value;
    }
    /**
     * <pre>
     * slug
     * </pre>
     *
     * <code>string provider = 9 [json_name = "provider"];</code>
     */
    private void clearProvider() {

      provider_ = getDefaultInstance().getProvider();
    }
    /**
     * <pre>
     * slug
     * </pre>
     *
     * <code>string provider = 9 [json_name = "provider"];</code>
     * @param value The bytes for provider to set.
     */
    private void setProviderBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      provider_ = value.toStringUtf8();

    }

    public static final int PROVIDER_REFERENCE_ID_FIELD_NUMBER = 10;
    private java.lang.String providerReferenceId_;
    /**
     * <code>string provider_reference_id = 10 [json_name = "providerReferenceId"];</code>
     * @return The providerReferenceId.
     */
    @java.lang.Override
    public java.lang.String getProviderReferenceId() {
      return providerReferenceId_;
    }
    /**
     * <code>string provider_reference_id = 10 [json_name = "providerReferenceId"];</code>
     * @return The bytes for providerReferenceId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProviderReferenceIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(providerReferenceId_);
    }
    /**
     * <code>string provider_reference_id = 10 [json_name = "providerReferenceId"];</code>
     * @param value The providerReferenceId to set.
     */
    private void setProviderReferenceId(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      providerReferenceId_ = value;
    }
    /**
     * <code>string provider_reference_id = 10 [json_name = "providerReferenceId"];</code>
     */
    private void clearProviderReferenceId() {

      providerReferenceId_ = getDefaultInstance().getProviderReferenceId();
    }
    /**
     * <code>string provider_reference_id = 10 [json_name = "providerReferenceId"];</code>
     * @param value The bytes for providerReferenceId to set.
     */
    private void setProviderReferenceIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      providerReferenceId_ = value.toStringUtf8();

    }

    public static final int STATUS_FIELD_NUMBER = 11;
    private int status_;
    /**
     * <code>.addressiq.v1.VerificationStatus status = 11 [json_name = "status"];</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.addressiq.v1.VerificationStatus status = 11 [json_name = "status"];</code>
     * @return The status.
     */
    @java.lang.Override
    public addressiq.v1.VerificationOuterClass.VerificationStatus getStatus() {
      addressiq.v1.VerificationOuterClass.VerificationStatus result = addressiq.v1.VerificationOuterClass.VerificationStatus.forNumber(status_);
      return result == null ? addressiq.v1.VerificationOuterClass.VerificationStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.addressiq.v1.VerificationStatus status = 11 [json_name = "status"];</code>
     * @param value The enum numeric value on the wire for status to set.
     */
    private void setStatusValue(int value) {
        status_ = value;
    }
    /**
     * <code>.addressiq.v1.VerificationStatus status = 11 [json_name = "status"];</code>
     * @param value The status to set.
     */
    private void setStatus(addressiq.v1.VerificationOuterClass.VerificationStatus value) {
      status_ = value.getNumber();

    }
    /**
     * <code>.addressiq.v1.VerificationStatus status = 11 [json_name = "status"];</code>
     */
    private void clearStatus() {

      status_ = 0;
    }

    public static final int REVIEW_STATE_FIELD_NUMBER = 12;
    private int reviewState_;
    /**
     * <code>.addressiq.v1.ReviewState review_state = 12 [json_name = "reviewState"];</code>
     * @return The enum numeric value on the wire for reviewState.
     */
    @java.lang.Override
    public int getReviewStateValue() {
      return reviewState_;
    }
    /**
     * <code>.addressiq.v1.ReviewState review_state = 12 [json_name = "reviewState"];</code>
     * @return The reviewState.
     */
    @java.lang.Override
    public addressiq.v1.VerificationOuterClass.ReviewState getReviewState() {
      addressiq.v1.VerificationOuterClass.ReviewState result = addressiq.v1.VerificationOuterClass.ReviewState.forNumber(reviewState_);
      return result == null ? addressiq.v1.VerificationOuterClass.ReviewState.UNRECOGNIZED : result;
    }
    /**
     * <code>.addressiq.v1.ReviewState review_state = 12 [json_name = "reviewState"];</code>
     * @param value The enum numeric value on the wire for reviewState to set.
     */
    private void setReviewStateValue(int value) {
        reviewState_ = value;
    }
    /**
     * <code>.addressiq.v1.ReviewState review_state = 12 [json_name = "reviewState"];</code>
     * @param value The reviewState to set.
     */
    private void setReviewState(addressiq.v1.VerificationOuterClass.ReviewState value) {
      reviewState_ = value.getNumber();

    }
    /**
     * <code>.addressiq.v1.ReviewState review_state = 12 [json_name = "reviewState"];</code>
     */
    private void clearReviewState() {

      reviewState_ = 0;
    }

    public static final int CONFIDENCE_SCORE_FIELD_NUMBER = 13;
    private double confidenceScore_;
    /**
     * <code>double confidence_score = 13 [json_name = "confidenceScore"];</code>
     * @return The confidenceScore.
     */
    @java.lang.Override
    public double getConfidenceScore() {
      return confidenceScore_;
    }
    /**
     * <code>double confidence_score = 13 [json_name = "confidenceScore"];</code>
     * @param value The confidenceScore to set.
     */
    private void setConfidenceScore(double value) {
      
      confidenceScore_ = value;
    }
    /**
     * <code>double confidence_score = 13 [json_name = "confidenceScore"];</code>
     */
    private void clearConfidenceScore() {

      confidenceScore_ = 0D;
    }

    public static final int WINDOW_ENDS_AT_FIELD_NUMBER = 14;
    private com.google.protobuf.Timestamp windowEndsAt_;
    /**
     * <code>.google.protobuf.Timestamp window_ends_at = 14 [json_name = "windowEndsAt"];</code>
     */
    @java.lang.Override
    public boolean hasWindowEndsAt() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp window_ends_at = 14 [json_name = "windowEndsAt"];</code>
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getWindowEndsAt() {
      return windowEndsAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : windowEndsAt_;
    }
    /**
     * <code>.google.protobuf.Timestamp window_ends_at = 14 [json_name = "windowEndsAt"];</code>
     */
    private void setWindowEndsAt(com.google.protobuf.Timestamp value) {
      value.getClass();
  windowEndsAt_ = value;
      bitField0_ |= 0x00000001;
      }
    /**
     * <code>.google.protobuf.Timestamp window_ends_at = 14 [json_name = "windowEndsAt"];</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeWindowEndsAt(com.google.protobuf.Timestamp value) {
      value.getClass();
  if (windowEndsAt_ != null &&
          windowEndsAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
        windowEndsAt_ =
          com.google.protobuf.Timestamp.newBuilder(windowEndsAt_).mergeFrom(value).buildPartial();
      } else {
        windowEndsAt_ = value;
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>.google.protobuf.Timestamp window_ends_at = 14 [json_name = "windowEndsAt"];</code>
     */
    private void clearWindowEndsAt() {  windowEndsAt_ = null;
      bitField0_ = (bitField0_ & ~0x00000001);
    }

    public static final int RESOLVED_AT_FIELD_NUMBER = 15;
    private com.google.protobuf.Timestamp resolvedAt_;
    /**
     * <code>.google.protobuf.Timestamp resolved_at = 15 [json_name = "resolvedAt"];</code>
     */
    @java.lang.Override
    public boolean hasResolvedAt() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp resolved_at = 15 [json_name = "resolvedAt"];</code>
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getResolvedAt() {
      return resolvedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : resolvedAt_;
    }
    /**
     * <code>.google.protobuf.Timestamp resolved_at = 15 [json_name = "resolvedAt"];</code>
     */
    private void setResolvedAt(com.google.protobuf.Timestamp value) {
      value.getClass();
  resolvedAt_ = value;
      bitField0_ |= 0x00000002;
      }
    /**
     * <code>.google.protobuf.Timestamp resolved_at = 15 [json_name = "resolvedAt"];</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeResolvedAt(com.google.protobuf.Timestamp value) {
      value.getClass();
  if (resolvedAt_ != null &&
          resolvedAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
        resolvedAt_ =
          com.google.protobuf.Timestamp.newBuilder(resolvedAt_).mergeFrom(value).buildPartial();
      } else {
        resolvedAt_ = value;
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>.google.protobuf.Timestamp resolved_at = 15 [json_name = "resolvedAt"];</code>
     */
    private void clearResolvedAt() {  resolvedAt_ = null;
      bitField0_ = (bitField0_ & ~0x00000002);
    }

    public static addressiq.v1.VerificationOuterClass.Verification parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static addressiq.v1.VerificationOuterClass.Verification parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static addressiq.v1.VerificationOuterClass.Verification parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static addressiq.v1.VerificationOuterClass.Verification parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static addressiq.v1.VerificationOuterClass.Verification parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static addressiq.v1.VerificationOuterClass.Verification parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static addressiq.v1.VerificationOuterClass.Verification parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static addressiq.v1.VerificationOuterClass.Verification parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static addressiq.v1.VerificationOuterClass.Verification parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static addressiq.v1.VerificationOuterClass.Verification parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static addressiq.v1.VerificationOuterClass.Verification parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static addressiq.v1.VerificationOuterClass.Verification parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(addressiq.v1.VerificationOuterClass.Verification prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code addressiq.v1.Verification}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          addressiq.v1.VerificationOuterClass.Verification, Builder> implements
        // @@protoc_insertion_point(builder_implements:addressiq.v1.Verification)
        addressiq.v1.VerificationOuterClass.VerificationOrBuilder {
      // Construct using addressiq.v1.VerificationOuterClass.Verification.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string id = 1 [json_name = "id"];</code>
       * @return The id.
       */
      @java.lang.Override
      public java.lang.String getId() {
        return instance.getId();
      }
      /**
       * <code>string id = 1 [json_name = "id"];</code>
       * @return The bytes for id.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getIdBytes() {
        return instance.getIdBytes();
      }
      /**
       * <code>string id = 1 [json_name = "id"];</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        copyOnWrite();
        instance.setId(value);
        return this;
      }
      /**
       * <code>string id = 1 [json_name = "id"];</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        copyOnWrite();
        instance.clearId();
        return this;
      }
      /**
       * <code>string id = 1 [json_name = "id"];</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setIdBytes(value);
        return this;
      }

      /**
       * <code>string verification_code = 2 [json_name = "verificationCode"];</code>
       * @return The verificationCode.
       */
      @java.lang.Override
      public java.lang.String getVerificationCode() {
        return instance.getVerificationCode();
      }
      /**
       * <code>string verification_code = 2 [json_name = "verificationCode"];</code>
       * @return The bytes for verificationCode.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getVerificationCodeBytes() {
        return instance.getVerificationCodeBytes();
      }
      /**
       * <code>string verification_code = 2 [json_name = "verificationCode"];</code>
       * @param value The verificationCode to set.
       * @return This builder for chaining.
       */
      public Builder setVerificationCode(
          java.lang.String value) {
        copyOnWrite();
        instance.setVerificationCode(value);
        return this;
      }
      /**
       * <code>string verification_code = 2 [json_name = "verificationCode"];</code>
       * @return This builder for chaining.
       */
      public Builder clearVerificationCode() {
        copyOnWrite();
        instance.clearVerificationCode();
        return this;
      }
      /**
       * <code>string verification_code = 2 [json_name = "verificationCode"];</code>
       * @param value The bytes for verificationCode to set.
       * @return This builder for chaining.
       */
      public Builder setVerificationCodeBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setVerificationCodeBytes(value);
        return this;
      }

      /**
       * <code>string organization_id = 3 [json_name = "organizationId"];</code>
       * @return The organizationId.
       */
      @java.lang.Override
      public java.lang.String getOrganizationId() {
        return instance.getOrganizationId();
      }
      /**
       * <code>string organization_id = 3 [json_name = "organizationId"];</code>
       * @return The bytes for organizationId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getOrganizationIdBytes() {
        return instance.getOrganizationIdBytes();
      }
      /**
       * <code>string organization_id = 3 [json_name = "organizationId"];</code>
       * @param value The organizationId to set.
       * @return This builder for chaining.
       */
      public Builder setOrganizationId(
          java.lang.String value) {
        copyOnWrite();
        instance.setOrganizationId(value);
        return this;
      }
      /**
       * <code>string organization_id = 3 [json_name = "organizationId"];</code>
       * @return This builder for chaining.
       */
      public Builder clearOrganizationId() {
        copyOnWrite();
        instance.clearOrganizationId();
        return this;
      }
      /**
       * <code>string organization_id = 3 [json_name = "organizationId"];</code>
       * @param value The bytes for organizationId to set.
       * @return This builder for chaining.
       */
      public Builder setOrganizationIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setOrganizationIdBytes(value);
        return this;
      }

      /**
       * <code>string app_id = 4 [json_name = "appId"];</code>
       * @return The appId.
       */
      @java.lang.Override
      public java.lang.String getAppId() {
        return instance.getAppId();
      }
      /**
       * <code>string app_id = 4 [json_name = "appId"];</code>
       * @return The bytes for appId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getAppIdBytes() {
        return instance.getAppIdBytes();
      }
      /**
       * <code>string app_id = 4 [json_name = "appId"];</code>
       * @param value The appId to set.
       * @return This builder for chaining.
       */
      public Builder setAppId(
          java.lang.String value) {
        copyOnWrite();
        instance.setAppId(value);
        return this;
      }
      /**
       * <code>string app_id = 4 [json_name = "appId"];</code>
       * @return This builder for chaining.
       */
      public Builder clearAppId() {
        copyOnWrite();
        instance.clearAppId();
        return this;
      }
      /**
       * <code>string app_id = 4 [json_name = "appId"];</code>
       * @param value The bytes for appId to set.
       * @return This builder for chaining.
       */
      public Builder setAppIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAppIdBytes(value);
        return this;
      }

      /**
       * <code>string branch_id = 5 [json_name = "branchId"];</code>
       * @return The branchId.
       */
      @java.lang.Override
      public java.lang.String getBranchId() {
        return instance.getBranchId();
      }
      /**
       * <code>string branch_id = 5 [json_name = "branchId"];</code>
       * @return The bytes for branchId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getBranchIdBytes() {
        return instance.getBranchIdBytes();
      }
      /**
       * <code>string branch_id = 5 [json_name = "branchId"];</code>
       * @param value The branchId to set.
       * @return This builder for chaining.
       */
      public Builder setBranchId(
          java.lang.String value) {
        copyOnWrite();
        instance.setBranchId(value);
        return this;
      }
      /**
       * <code>string branch_id = 5 [json_name = "branchId"];</code>
       * @return This builder for chaining.
       */
      public Builder clearBranchId() {
        copyOnWrite();
        instance.clearBranchId();
        return this;
      }
      /**
       * <code>string branch_id = 5 [json_name = "branchId"];</code>
       * @param value The bytes for branchId to set.
       * @return This builder for chaining.
       */
      public Builder setBranchIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setBranchIdBytes(value);
        return this;
      }

      /**
       * <code>string app_user_id = 6 [json_name = "appUserId"];</code>
       * @return The appUserId.
       */
      @java.lang.Override
      public java.lang.String getAppUserId() {
        return instance.getAppUserId();
      }
      /**
       * <code>string app_user_id = 6 [json_name = "appUserId"];</code>
       * @return The bytes for appUserId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getAppUserIdBytes() {
        return instance.getAppUserIdBytes();
      }
      /**
       * <code>string app_user_id = 6 [json_name = "appUserId"];</code>
       * @param value The appUserId to set.
       * @return This builder for chaining.
       */
      public Builder setAppUserId(
          java.lang.String value) {
        copyOnWrite();
        instance.setAppUserId(value);
        return this;
      }
      /**
       * <code>string app_user_id = 6 [json_name = "appUserId"];</code>
       * @return This builder for chaining.
       */
      public Builder clearAppUserId() {
        copyOnWrite();
        instance.clearAppUserId();
        return this;
      }
      /**
       * <code>string app_user_id = 6 [json_name = "appUserId"];</code>
       * @param value The bytes for appUserId to set.
       * @return This builder for chaining.
       */
      public Builder setAppUserIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAppUserIdBytes(value);
        return this;
      }

      /**
       * <code>string location_id = 7 [json_name = "locationId"];</code>
       * @return The locationId.
       */
      @java.lang.Override
      public java.lang.String getLocationId() {
        return instance.getLocationId();
      }
      /**
       * <code>string location_id = 7 [json_name = "locationId"];</code>
       * @return The bytes for locationId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getLocationIdBytes() {
        return instance.getLocationIdBytes();
      }
      /**
       * <code>string location_id = 7 [json_name = "locationId"];</code>
       * @param value The locationId to set.
       * @return This builder for chaining.
       */
      public Builder setLocationId(
          java.lang.String value) {
        copyOnWrite();
        instance.setLocationId(value);
        return this;
      }
      /**
       * <code>string location_id = 7 [json_name = "locationId"];</code>
       * @return This builder for chaining.
       */
      public Builder clearLocationId() {
        copyOnWrite();
        instance.clearLocationId();
        return this;
      }
      /**
       * <code>string location_id = 7 [json_name = "locationId"];</code>
       * @param value The bytes for locationId to set.
       * @return This builder for chaining.
       */
      public Builder setLocationIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setLocationIdBytes(value);
        return this;
      }

      /**
       * <code>.addressiq.v1.VerificationType type = 8 [json_name = "type"];</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override
      public int getTypeValue() {
        return instance.getTypeValue();
      }
      /**
       * <code>.addressiq.v1.VerificationType type = 8 [json_name = "type"];</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        copyOnWrite();
        instance.setTypeValue(value);
        return this;
      }
      /**
       * <code>.addressiq.v1.VerificationType type = 8 [json_name = "type"];</code>
       * @return The type.
       */
      @java.lang.Override
      public addressiq.v1.VerificationOuterClass.VerificationType getType() {
        return instance.getType();
      }
      /**
       * <code>.addressiq.v1.VerificationType type = 8 [json_name = "type"];</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setType(addressiq.v1.VerificationOuterClass.VerificationType value) {
        copyOnWrite();
        instance.setType(value);
        return this;
      }
      /**
       * <code>.addressiq.v1.VerificationType type = 8 [json_name = "type"];</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        copyOnWrite();
        instance.clearType();
        return this;
      }

      /**
       * <pre>
       * slug
       * </pre>
       *
       * <code>string provider = 9 [json_name = "provider"];</code>
       * @return The provider.
       */
      @java.lang.Override
      public java.lang.String getProvider() {
        return instance.getProvider();
      }
      /**
       * <pre>
       * slug
       * </pre>
       *
       * <code>string provider = 9 [json_name = "provider"];</code>
       * @return The bytes for provider.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getProviderBytes() {
        return instance.getProviderBytes();
      }
      /**
       * <pre>
       * slug
       * </pre>
       *
       * <code>string provider = 9 [json_name = "provider"];</code>
       * @param value The provider to set.
       * @return This builder for chaining.
       */
      public Builder setProvider(
          java.lang.String value) {
        copyOnWrite();
        instance.setProvider(value);
        return this;
      }
      /**
       * <pre>
       * slug
       * </pre>
       *
       * <code>string provider = 9 [json_name = "provider"];</code>
       * @return This builder for chaining.
       */
      public Builder clearProvider() {
        copyOnWrite();
        instance.clearProvider();
        return this;
      }
      /**
       * <pre>
       * slug
       * </pre>
       *
       * <code>string provider = 9 [json_name = "provider"];</code>
       * @param value The bytes for provider to set.
       * @return This builder for chaining.
       */
      public Builder setProviderBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setProviderBytes(value);
        return this;
      }

      /**
       * <code>string provider_reference_id = 10 [json_name = "providerReferenceId"];</code>
       * @return The providerReferenceId.
       */
      @java.lang.Override
      public java.lang.String getProviderReferenceId() {
        return instance.getProviderReferenceId();
      }
      /**
       * <code>string provider_reference_id = 10 [json_name = "providerReferenceId"];</code>
       * @return The bytes for providerReferenceId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getProviderReferenceIdBytes() {
        return instance.getProviderReferenceIdBytes();
      }
      /**
       * <code>string provider_reference_id = 10 [json_name = "providerReferenceId"];</code>
       * @param value The providerReferenceId to set.
       * @return This builder for chaining.
       */
      public Builder setProviderReferenceId(
          java.lang.String value) {
        copyOnWrite();
        instance.setProviderReferenceId(value);
        return this;
      }
      /**
       * <code>string provider_reference_id = 10 [json_name = "providerReferenceId"];</code>
       * @return This builder for chaining.
       */
      public Builder clearProviderReferenceId() {
        copyOnWrite();
        instance.clearProviderReferenceId();
        return this;
      }
      /**
       * <code>string provider_reference_id = 10 [json_name = "providerReferenceId"];</code>
       * @param value The bytes for providerReferenceId to set.
       * @return This builder for chaining.
       */
      public Builder setProviderReferenceIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setProviderReferenceIdBytes(value);
        return this;
      }

      /**
       * <code>.addressiq.v1.VerificationStatus status = 11 [json_name = "status"];</code>
       * @return The enum numeric value on the wire for status.
       */
      @java.lang.Override
      public int getStatusValue() {
        return instance.getStatusValue();
      }
      /**
       * <code>.addressiq.v1.VerificationStatus status = 11 [json_name = "status"];</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusValue(int value) {
        copyOnWrite();
        instance.setStatusValue(value);
        return this;
      }
      /**
       * <code>.addressiq.v1.VerificationStatus status = 11 [json_name = "status"];</code>
       * @return The status.
       */
      @java.lang.Override
      public addressiq.v1.VerificationOuterClass.VerificationStatus getStatus() {
        return instance.getStatus();
      }
      /**
       * <code>.addressiq.v1.VerificationStatus status = 11 [json_name = "status"];</code>
       * @param value The enum numeric value on the wire for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(addressiq.v1.VerificationOuterClass.VerificationStatus value) {
        copyOnWrite();
        instance.setStatus(value);
        return this;
      }
      /**
       * <code>.addressiq.v1.VerificationStatus status = 11 [json_name = "status"];</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        copyOnWrite();
        instance.clearStatus();
        return this;
      }

      /**
       * <code>.addressiq.v1.ReviewState review_state = 12 [json_name = "reviewState"];</code>
       * @return The enum numeric value on the wire for reviewState.
       */
      @java.lang.Override
      public int getReviewStateValue() {
        return instance.getReviewStateValue();
      }
      /**
       * <code>.addressiq.v1.ReviewState review_state = 12 [json_name = "reviewState"];</code>
       * @param value The reviewState to set.
       * @return This builder for chaining.
       */
      public Builder setReviewStateValue(int value) {
        copyOnWrite();
        instance.setReviewStateValue(value);
        return this;
      }
      /**
       * <code>.addressiq.v1.ReviewState review_state = 12 [json_name = "reviewState"];</code>
       * @return The reviewState.
       */
      @java.lang.Override
      public addressiq.v1.VerificationOuterClass.ReviewState getReviewState() {
        return instance.getReviewState();
      }
      /**
       * <code>.addressiq.v1.ReviewState review_state = 12 [json_name = "reviewState"];</code>
       * @param value The enum numeric value on the wire for reviewState to set.
       * @return This builder for chaining.
       */
      public Builder setReviewState(addressiq.v1.VerificationOuterClass.ReviewState value) {
        copyOnWrite();
        instance.setReviewState(value);
        return this;
      }
      /**
       * <code>.addressiq.v1.ReviewState review_state = 12 [json_name = "reviewState"];</code>
       * @return This builder for chaining.
       */
      public Builder clearReviewState() {
        copyOnWrite();
        instance.clearReviewState();
        return this;
      }

      /**
       * <code>double confidence_score = 13 [json_name = "confidenceScore"];</code>
       * @return The confidenceScore.
       */
      @java.lang.Override
      public double getConfidenceScore() {
        return instance.getConfidenceScore();
      }
      /**
       * <code>double confidence_score = 13 [json_name = "confidenceScore"];</code>
       * @param value The confidenceScore to set.
       * @return This builder for chaining.
       */
      public Builder setConfidenceScore(double value) {
        copyOnWrite();
        instance.setConfidenceScore(value);
        return this;
      }
      /**
       * <code>double confidence_score = 13 [json_name = "confidenceScore"];</code>
       * @return This builder for chaining.
       */
      public Builder clearConfidenceScore() {
        copyOnWrite();
        instance.clearConfidenceScore();
        return this;
      }

      /**
       * <code>.google.protobuf.Timestamp window_ends_at = 14 [json_name = "windowEndsAt"];</code>
       */
      @java.lang.Override
      public boolean hasWindowEndsAt() {
        return instance.hasWindowEndsAt();
      }
      /**
       * <code>.google.protobuf.Timestamp window_ends_at = 14 [json_name = "windowEndsAt"];</code>
       */
      @java.lang.Override
      public com.google.protobuf.Timestamp getWindowEndsAt() {
        return instance.getWindowEndsAt();
      }
      /**
       * <code>.google.protobuf.Timestamp window_ends_at = 14 [json_name = "windowEndsAt"];</code>
       */
      public Builder setWindowEndsAt(com.google.protobuf.Timestamp value) {
        copyOnWrite();
        instance.setWindowEndsAt(value);
        return this;
        }
      /**
       * <code>.google.protobuf.Timestamp window_ends_at = 14 [json_name = "windowEndsAt"];</code>
       */
      public Builder setWindowEndsAt(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        copyOnWrite();
        instance.setWindowEndsAt(builderForValue.build());
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp window_ends_at = 14 [json_name = "windowEndsAt"];</code>
       */
      public Builder mergeWindowEndsAt(com.google.protobuf.Timestamp value) {
        copyOnWrite();
        instance.mergeWindowEndsAt(value);
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp window_ends_at = 14 [json_name = "windowEndsAt"];</code>
       */
      public Builder clearWindowEndsAt() {  copyOnWrite();
        instance.clearWindowEndsAt();
        return this;
      }

      /**
       * <code>.google.protobuf.Timestamp resolved_at = 15 [json_name = "resolvedAt"];</code>
       */
      @java.lang.Override
      public boolean hasResolvedAt() {
        return instance.hasResolvedAt();
      }
      /**
       * <code>.google.protobuf.Timestamp resolved_at = 15 [json_name = "resolvedAt"];</code>
       */
      @java.lang.Override
      public com.google.protobuf.Timestamp getResolvedAt() {
        return instance.getResolvedAt();
      }
      /**
       * <code>.google.protobuf.Timestamp resolved_at = 15 [json_name = "resolvedAt"];</code>
       */
      public Builder setResolvedAt(com.google.protobuf.Timestamp value) {
        copyOnWrite();
        instance.setResolvedAt(value);
        return this;
        }
      /**
       * <code>.google.protobuf.Timestamp resolved_at = 15 [json_name = "resolvedAt"];</code>
       */
      public Builder setResolvedAt(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        copyOnWrite();
        instance.setResolvedAt(builderForValue.build());
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp resolved_at = 15 [json_name = "resolvedAt"];</code>
       */
      public Builder mergeResolvedAt(com.google.protobuf.Timestamp value) {
        copyOnWrite();
        instance.mergeResolvedAt(value);
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp resolved_at = 15 [json_name = "resolvedAt"];</code>
       */
      public Builder clearResolvedAt() {  copyOnWrite();
        instance.clearResolvedAt();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:addressiq.v1.Verification)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new addressiq.v1.VerificationOuterClass.Verification();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "id_",
              "verificationCode_",
              "organizationId_",
              "appId_",
              "branchId_",
              "appUserId_",
              "locationId_",
              "type_",
              "provider_",
              "providerReferenceId_",
              "status_",
              "reviewState_",
              "confidenceScore_",
              "windowEndsAt_",
              "resolvedAt_",
            };
            java.lang.String info =
                "\u0000\u000f\u0000\u0001\u0001\u000f\u000f\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
                "\u0003\u0208\u0004\u0208\u0005\u0208\u0006\u0208\u0007\u0208\b\f\t\u0208\n\u0208" +
                "\u000b\f\f\f\r\u0000\u000e\u1009\u0000\u000f\u1009\u0001";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<addressiq.v1.VerificationOuterClass.Verification> parser = PARSER;
          if (parser == null) {
            synchronized (addressiq.v1.VerificationOuterClass.Verification.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<addressiq.v1.VerificationOuterClass.Verification>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:addressiq.v1.Verification)
    private static final addressiq.v1.VerificationOuterClass.Verification DEFAULT_INSTANCE;
    static {
      Verification defaultInstance = new Verification();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Verification.class, defaultInstance);
    }

    public static addressiq.v1.VerificationOuterClass.Verification getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Verification> PARSER;

    public static com.google.protobuf.Parser<Verification> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface LocationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:addressiq.v1.Location)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string location_code = 2 [json_name = "locationCode"];</code>
     * @return The locationCode.
     */
    java.lang.String getLocationCode();
    /**
     * <code>string location_code = 2 [json_name = "locationCode"];</code>
     * @return The bytes for locationCode.
     */
    com.google.protobuf.ByteString
        getLocationCodeBytes();

    /**
     * <code>.addressiq.v1.GeoPoint position = 3 [json_name = "position"];</code>
     * @return Whether the position field is set.
     */
    boolean hasPosition();
    /**
     * <code>.addressiq.v1.GeoPoint position = 3 [json_name = "position"];</code>
     * @return The position.
     */
    addressiq.v1.Common.GeoPoint getPosition();

    /**
     * <code>int32 geofence_radius_m = 4 [json_name = "geofenceRadiusM"];</code>
     * @return The geofenceRadiusM.
     */
    int getGeofenceRadiusM();

    /**
     * <pre>
     * Phase 3 — adaptive radius the SDK MUST honor when registering OS geofences.
     * </pre>
     *
     * <code>int32 adaptive_geofence_radius_meters = 5 [json_name = "adaptiveGeofenceRadiusMeters"];</code>
     * @return The adaptiveGeofenceRadiusMeters.
     */
    int getAdaptiveGeofenceRadiusMeters();

    /**
     * <code>.addressiq.v1.EnvironmentBucket environment = 6 [json_name = "environment"];</code>
     * @return The enum numeric value on the wire for environment.
     */
    int getEnvironmentValue();
    /**
     * <code>.addressiq.v1.EnvironmentBucket environment = 6 [json_name = "environment"];</code>
     * @return The environment.
     */
    addressiq.v1.Common.EnvironmentBucket getEnvironment();
  }
  /**
   * Protobuf type {@code addressiq.v1.Location}
   */
  public  static final class Location extends
      com.google.protobuf.GeneratedMessageLite<
          Location, Location.Builder> implements
      // @@protoc_insertion_point(message_implements:addressiq.v1.Location)
      LocationOrBuilder {
    private Location() {
      id_ = "";
      locationCode_ = "";
    }
    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.String id_;
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      return id_;
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(id_);
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The id to set.
     */
    private void setId(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      id_ = value;
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     */
    private void clearId() {

      id_ = getDefaultInstance().getId();
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The bytes for id to set.
     */
    private void setIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      id_ = value.toStringUtf8();

    }

    public static final int LOCATION_CODE_FIELD_NUMBER = 2;
    private java.lang.String locationCode_;
    /**
     * <code>string location_code = 2 [json_name = "locationCode"];</code>
     * @return The locationCode.
     */
    @java.lang.Override
    public java.lang.String getLocationCode() {
      return locationCode_;
    }
    /**
     * <code>string location_code = 2 [json_name = "locationCode"];</code>
     * @return The bytes for locationCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLocationCodeBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(locationCode_);
    }
    /**
     * <code>string location_code = 2 [json_name = "locationCode"];</code>
     * @param value The locationCode to set.
     */
    private void setLocationCode(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      locationCode_ = value;
    }
    /**
     * <code>string location_code = 2 [json_name = "locationCode"];</code>
     */
    private void clearLocationCode() {

      locationCode_ = getDefaultInstance().getLocationCode();
    }
    /**
     * <code>string location_code = 2 [json_name = "locationCode"];</code>
     * @param value The bytes for locationCode to set.
     */
    private void setLocationCodeBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      locationCode_ = value.toStringUtf8();

    }

    public static final int POSITION_FIELD_NUMBER = 3;
    private addressiq.v1.Common.GeoPoint position_;
    /**
     * <code>.addressiq.v1.GeoPoint position = 3 [json_name = "position"];</code>
     */
    @java.lang.Override
    public boolean hasPosition() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.addressiq.v1.GeoPoint position = 3 [json_name = "position"];</code>
     */
    @java.lang.Override
    public addressiq.v1.Common.GeoPoint getPosition() {
      return position_ == null ? addressiq.v1.Common.GeoPoint.getDefaultInstance() : position_;
    }
    /**
     * <code>.addressiq.v1.GeoPoint position = 3 [json_name = "position"];</code>
     */
    private void setPosition(addressiq.v1.Common.GeoPoint value) {
      value.getClass();
  position_ = value;
      bitField0_ |= 0x00000001;
      }
    /**
     * <code>.addressiq.v1.GeoPoint position = 3 [json_name = "position"];</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergePosition(addressiq.v1.Common.GeoPoint value) {
      value.getClass();
  if (position_ != null &&
          position_ != addressiq.v1.Common.GeoPoint.getDefaultInstance()) {
        position_ =
          addressiq.v1.Common.GeoPoint.newBuilder(position_).mergeFrom(value).buildPartial();
      } else {
        position_ = value;
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>.addressiq.v1.GeoPoint position = 3 [json_name = "position"];</code>
     */
    private void clearPosition() {  position_ = null;
      bitField0_ = (bitField0_ & ~0x00000001);
    }

    public static final int GEOFENCE_RADIUS_M_FIELD_NUMBER = 4;
    private int geofenceRadiusM_;
    /**
     * <code>int32 geofence_radius_m = 4 [json_name = "geofenceRadiusM"];</code>
     * @return The geofenceRadiusM.
     */
    @java.lang.Override
    public int getGeofenceRadiusM() {
      return geofenceRadiusM_;
    }
    /**
     * <code>int32 geofence_radius_m = 4 [json_name = "geofenceRadiusM"];</code>
     * @param value The geofenceRadiusM to set.
     */
    private void setGeofenceRadiusM(int value) {
      
      geofenceRadiusM_ = value;
    }
    /**
     * <code>int32 geofence_radius_m = 4 [json_name = "geofenceRadiusM"];</code>
     */
    private void clearGeofenceRadiusM() {

      geofenceRadiusM_ = 0;
    }

    public static final int ADAPTIVE_GEOFENCE_RADIUS_METERS_FIELD_NUMBER = 5;
    private int adaptiveGeofenceRadiusMeters_;
    /**
     * <pre>
     * Phase 3 — adaptive radius the SDK MUST honor when registering OS geofences.
     * </pre>
     *
     * <code>int32 adaptive_geofence_radius_meters = 5 [json_name = "adaptiveGeofenceRadiusMeters"];</code>
     * @return The adaptiveGeofenceRadiusMeters.
     */
    @java.lang.Override
    public int getAdaptiveGeofenceRadiusMeters() {
      return adaptiveGeofenceRadiusMeters_;
    }
    /**
     * <pre>
     * Phase 3 — adaptive radius the SDK MUST honor when registering OS geofences.
     * </pre>
     *
     * <code>int32 adaptive_geofence_radius_meters = 5 [json_name = "adaptiveGeofenceRadiusMeters"];</code>
     * @param value The adaptiveGeofenceRadiusMeters to set.
     */
    private void setAdaptiveGeofenceRadiusMeters(int value) {
      
      adaptiveGeofenceRadiusMeters_ = value;
    }
    /**
     * <pre>
     * Phase 3 — adaptive radius the SDK MUST honor when registering OS geofences.
     * </pre>
     *
     * <code>int32 adaptive_geofence_radius_meters = 5 [json_name = "adaptiveGeofenceRadiusMeters"];</code>
     */
    private void clearAdaptiveGeofenceRadiusMeters() {

      adaptiveGeofenceRadiusMeters_ = 0;
    }

    public static final int ENVIRONMENT_FIELD_NUMBER = 6;
    private int environment_;
    /**
     * <code>.addressiq.v1.EnvironmentBucket environment = 6 [json_name = "environment"];</code>
     * @return The enum numeric value on the wire for environment.
     */
    @java.lang.Override
    public int getEnvironmentValue() {
      return environment_;
    }
    /**
     * <code>.addressiq.v1.EnvironmentBucket environment = 6 [json_name = "environment"];</code>
     * @return The environment.
     */
    @java.lang.Override
    public addressiq.v1.Common.EnvironmentBucket getEnvironment() {
      addressiq.v1.Common.EnvironmentBucket result = addressiq.v1.Common.EnvironmentBucket.forNumber(environment_);
      return result == null ? addressiq.v1.Common.EnvironmentBucket.UNRECOGNIZED : result;
    }
    /**
     * <code>.addressiq.v1.EnvironmentBucket environment = 6 [json_name = "environment"];</code>
     * @param value The enum numeric value on the wire for environment to set.
     */
    private void setEnvironmentValue(int value) {
        environment_ = value;
    }
    /**
     * <code>.addressiq.v1.EnvironmentBucket environment = 6 [json_name = "environment"];</code>
     * @param value The environment to set.
     */
    private void setEnvironment(addressiq.v1.Common.EnvironmentBucket value) {
      environment_ = value.getNumber();

    }
    /**
     * <code>.addressiq.v1.EnvironmentBucket environment = 6 [json_name = "environment"];</code>
     */
    private void clearEnvironment() {

      environment_ = 0;
    }

    public static addressiq.v1.VerificationOuterClass.Location parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static addressiq.v1.VerificationOuterClass.Location parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static addressiq.v1.VerificationOuterClass.Location parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static addressiq.v1.VerificationOuterClass.Location parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static addressiq.v1.VerificationOuterClass.Location parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static addressiq.v1.VerificationOuterClass.Location parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static addressiq.v1.VerificationOuterClass.Location parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static addressiq.v1.VerificationOuterClass.Location parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static addressiq.v1.VerificationOuterClass.Location parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static addressiq.v1.VerificationOuterClass.Location parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static addressiq.v1.VerificationOuterClass.Location parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static addressiq.v1.VerificationOuterClass.Location parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(addressiq.v1.VerificationOuterClass.Location prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code addressiq.v1.Location}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          addressiq.v1.VerificationOuterClass.Location, Builder> implements
        // @@protoc_insertion_point(builder_implements:addressiq.v1.Location)
        addressiq.v1.VerificationOuterClass.LocationOrBuilder {
      // Construct using addressiq.v1.VerificationOuterClass.Location.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string id = 1 [json_name = "id"];</code>
       * @return The id.
       */
      @java.lang.Override
      public java.lang.String getId() {
        return instance.getId();
      }
      /**
       * <code>string id = 1 [json_name = "id"];</code>
       * @return The bytes for id.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getIdBytes() {
        return instance.getIdBytes();
      }
      /**
       * <code>string id = 1 [json_name = "id"];</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        copyOnWrite();
        instance.setId(value);
        return this;
      }
      /**
       * <code>string id = 1 [json_name = "id"];</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        copyOnWrite();
        instance.clearId();
        return this;
      }
      /**
       * <code>string id = 1 [json_name = "id"];</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setIdBytes(value);
        return this;
      }

      /**
       * <code>string location_code = 2 [json_name = "locationCode"];</code>
       * @return The locationCode.
       */
      @java.lang.Override
      public java.lang.String getLocationCode() {
        return instance.getLocationCode();
      }
      /**
       * <code>string location_code = 2 [json_name = "locationCode"];</code>
       * @return The bytes for locationCode.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getLocationCodeBytes() {
        return instance.getLocationCodeBytes();
      }
      /**
       * <code>string location_code = 2 [json_name = "locationCode"];</code>
       * @param value The locationCode to set.
       * @return This builder for chaining.
       */
      public Builder setLocationCode(
          java.lang.String value) {
        copyOnWrite();
        instance.setLocationCode(value);
        return this;
      }
      /**
       * <code>string location_code = 2 [json_name = "locationCode"];</code>
       * @return This builder for chaining.
       */
      public Builder clearLocationCode() {
        copyOnWrite();
        instance.clearLocationCode();
        return this;
      }
      /**
       * <code>string location_code = 2 [json_name = "locationCode"];</code>
       * @param value The bytes for locationCode to set.
       * @return This builder for chaining.
       */
      public Builder setLocationCodeBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setLocationCodeBytes(value);
        return this;
      }

      /**
       * <code>.addressiq.v1.GeoPoint position = 3 [json_name = "position"];</code>
       */
      @java.lang.Override
      public boolean hasPosition() {
        return instance.hasPosition();
      }
      /**
       * <code>.addressiq.v1.GeoPoint position = 3 [json_name = "position"];</code>
       */
      @java.lang.Override
      public addressiq.v1.Common.GeoPoint getPosition() {
        return instance.getPosition();
      }
      /**
       * <code>.addressiq.v1.GeoPoint position = 3 [json_name = "position"];</code>
       */
      public Builder setPosition(addressiq.v1.Common.GeoPoint value) {
        copyOnWrite();
        instance.setPosition(value);
        return this;
        }
      /**
       * <code>.addressiq.v1.GeoPoint position = 3 [json_name = "position"];</code>
       */
      public Builder setPosition(
          addressiq.v1.Common.GeoPoint.Builder builderForValue) {
        copyOnWrite();
        instance.setPosition(builderForValue.build());
        return this;
      }
      /**
       * <code>.addressiq.v1.GeoPoint position = 3 [json_name = "position"];</code>
       */
      public Builder mergePosition(addressiq.v1.Common.GeoPoint value) {
        copyOnWrite();
        instance.mergePosition(value);
        return this;
      }
      /**
       * <code>.addressiq.v1.GeoPoint position = 3 [json_name = "position"];</code>
       */
      public Builder clearPosition() {  copyOnWrite();
        instance.clearPosition();
        return this;
      }

      /**
       * <code>int32 geofence_radius_m = 4 [json_name = "geofenceRadiusM"];</code>
       * @return The geofenceRadiusM.
       */
      @java.lang.Override
      public int getGeofenceRadiusM() {
        return instance.getGeofenceRadiusM();
      }
      /**
       * <code>int32 geofence_radius_m = 4 [json_name = "geofenceRadiusM"];</code>
       * @param value The geofenceRadiusM to set.
       * @return This builder for chaining.
       */
      public Builder setGeofenceRadiusM(int value) {
        copyOnWrite();
        instance.setGeofenceRadiusM(value);
        return this;
      }
      /**
       * <code>int32 geofence_radius_m = 4 [json_name = "geofenceRadiusM"];</code>
       * @return This builder for chaining.
       */
      public Builder clearGeofenceRadiusM() {
        copyOnWrite();
        instance.clearGeofenceRadiusM();
        return this;
      }

      /**
       * <pre>
       * Phase 3 — adaptive radius the SDK MUST honor when registering OS geofences.
       * </pre>
       *
       * <code>int32 adaptive_geofence_radius_meters = 5 [json_name = "adaptiveGeofenceRadiusMeters"];</code>
       * @return The adaptiveGeofenceRadiusMeters.
       */
      @java.lang.Override
      public int getAdaptiveGeofenceRadiusMeters() {
        return instance.getAdaptiveGeofenceRadiusMeters();
      }
      /**
       * <pre>
       * Phase 3 — adaptive radius the SDK MUST honor when registering OS geofences.
       * </pre>
       *
       * <code>int32 adaptive_geofence_radius_meters = 5 [json_name = "adaptiveGeofenceRadiusMeters"];</code>
       * @param value The adaptiveGeofenceRadiusMeters to set.
       * @return This builder for chaining.
       */
      public Builder setAdaptiveGeofenceRadiusMeters(int value) {
        copyOnWrite();
        instance.setAdaptiveGeofenceRadiusMeters(value);
        return this;
      }
      /**
       * <pre>
       * Phase 3 — adaptive radius the SDK MUST honor when registering OS geofences.
       * </pre>
       *
       * <code>int32 adaptive_geofence_radius_meters = 5 [json_name = "adaptiveGeofenceRadiusMeters"];</code>
       * @return This builder for chaining.
       */
      public Builder clearAdaptiveGeofenceRadiusMeters() {
        copyOnWrite();
        instance.clearAdaptiveGeofenceRadiusMeters();
        return this;
      }

      /**
       * <code>.addressiq.v1.EnvironmentBucket environment = 6 [json_name = "environment"];</code>
       * @return The enum numeric value on the wire for environment.
       */
      @java.lang.Override
      public int getEnvironmentValue() {
        return instance.getEnvironmentValue();
      }
      /**
       * <code>.addressiq.v1.EnvironmentBucket environment = 6 [json_name = "environment"];</code>
       * @param value The environment to set.
       * @return This builder for chaining.
       */
      public Builder setEnvironmentValue(int value) {
        copyOnWrite();
        instance.setEnvironmentValue(value);
        return this;
      }
      /**
       * <code>.addressiq.v1.EnvironmentBucket environment = 6 [json_name = "environment"];</code>
       * @return The environment.
       */
      @java.lang.Override
      public addressiq.v1.Common.EnvironmentBucket getEnvironment() {
        return instance.getEnvironment();
      }
      /**
       * <code>.addressiq.v1.EnvironmentBucket environment = 6 [json_name = "environment"];</code>
       * @param value The enum numeric value on the wire for environment to set.
       * @return This builder for chaining.
       */
      public Builder setEnvironment(addressiq.v1.Common.EnvironmentBucket value) {
        copyOnWrite();
        instance.setEnvironment(value);
        return this;
      }
      /**
       * <code>.addressiq.v1.EnvironmentBucket environment = 6 [json_name = "environment"];</code>
       * @return This builder for chaining.
       */
      public Builder clearEnvironment() {
        copyOnWrite();
        instance.clearEnvironment();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:addressiq.v1.Location)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new addressiq.v1.VerificationOuterClass.Location();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "id_",
              "locationCode_",
              "position_",
              "geofenceRadiusM_",
              "adaptiveGeofenceRadiusMeters_",
              "environment_",
            };
            java.lang.String info =
                "\u0000\u0006\u0000\u0001\u0001\u0006\u0006\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
                "\u0003\u1009\u0000\u0004\u0004\u0005\u0004\u0006\f";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<addressiq.v1.VerificationOuterClass.Location> parser = PARSER;
          if (parser == null) {
            synchronized (addressiq.v1.VerificationOuterClass.Location.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<addressiq.v1.VerificationOuterClass.Location>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:addressiq.v1.Location)
    private static final addressiq.v1.VerificationOuterClass.Location DEFAULT_INSTANCE;
    static {
      Location defaultInstance = new Location();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Location.class, defaultInstance);
    }

    public static addressiq.v1.VerificationOuterClass.Location getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Location> PARSER;

    public static com.google.protobuf.Parser<Location> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
